Netflix/conductor

- docs/docs/metadata/systask.md
Nothing much more to add there.
I think I found a small typo so I fixed it, not really a big fix.
> Fix small typo in documentation about task types

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
- contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java
- core/src/main/java/com/netflix/conductor/core/execution/SystemTask.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/WorkflowServiceTest.java
* Fix issue with Optional tasks within the dynamic forks
* Reorganize code around above
* Fix an issue where the task inputs are getting mixed up with other instances when using task template due to a concurrency bug
* Fix the bug where workflows where marked as completed if the last task is a decision task but one of the decision fork task has failed and is scheduled for retry.
> 1.7.2-RC-Final

- contribs/build.gradle
- contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java
- contribs/src/test/java/com/netflix/conductor/contribs/http/TestHttpTask.java
This small PR adds support for calling HTTP endpoints secured with OAuth 1.0
If the OAuth parameters (consumer key and consumer secret) are present in the input parameters for the HTTP tasks, those will be used for authentication against the endpoint.
We tested this internally successfully with our OAuth endpoints.
> Add OAuth 1.0 authentication support to HTTP tasks

- docs/docs/intro/index.md
I'm reading/following the quickstart documentation (more specifically the intro) and I saw that it was possible to use `docker-compose` and I thought it'd be good to have this information there.
About the `clone` change, I was following the quickstart guide and then it raised a silly error.
> $ git clone git@github.com/Netflix/conductor.git
> fatal: repository 'git@github.com/Netflix/conductor.git' does not exist
> adds information about how to run it on docker compose

- docker/server/Dockerfile
- docker/serverAndUI/Dockerfile
- docker/ui/Dockerfile
The plugin `nebula.netflixoss` (walk) requires a "full" cloned repo otherwise, the build will fail.
```
FAILURE: Build failed with an exception.
* Where:
Build file '/conductor/build.gradle' line: 13
* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.6.0']
> Failed to apply plugin [class 'nebula.plugin.bintray.NebulaBintrayPublishingPlugin']
> Walk failure.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```
> adds full cloned repository

- contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java
When debugging failing HTTP tasks, it's helpful to include the HTTP reason phrase instead of exposing only the status code. This is specially useful for non common status codes.
Here is an example output for an HTTP task returning a 424 (Failed Dependency) response code:
```
{
"response": {
"headers": {
...
},
"reasonPhrase": "Failed Dependency",
"body": {
"code": "EXTERNAL_ERROR",
"message": "An error occurred while creating or modifying your account"
},
"statusCode": 424
}
}
```
> HTTP task : add HTTP reason phrase in the response metadata

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
- docs/docs/metadata/index.md
Hello,
We thought it would be useful to allow workflow designers to add a description in tasks. For instance, considering a generic task like the HTTP system task, its usage may differ from one to another. Thus, being able to specify what is happening could be useful.
Thanks in advance for any feedback!
Nicolas
> Add an optional description in WorkflowTask model

- docker/server/Dockerfile
- docker/server/Dockerfile.build
- docker/server/README.md
- docker/server/bin/startup.sh
- docker/ui/Dockerfile
- docker/ui/README.md
- docker/ui/bin/startup.sh
Pull Request for Issue #280 
Objectives
-----------
* Migrate server build to a 2-step process where the server is built using the java:8-jdk and is then copied to a java:8-jre-alpine runtime image.
* Migrate ui build to a node:alpine image.
* Run ui and api in the foreground.
* Log to STDOUT instead of log files.
Details
-------
* Modified the dockerfiles to use Alpine as the base image.
* Modified the dockerfiles to load the code from the local context in order to allow users to build docker images which contain changes which have not yet been merged into netflix/conductor:master.
* Modified the startup scripts to remove the `nohup` command and to instead run the application in the foreground.  
* Modified the startup scripts to remove the stream redirect into log files so that the …
> Migrate docker images to Alpine Linux

- ui/src/server.js
This PR is simply to allow overriding the NodeJS port for the UI using an environment variable (NODE_PORT)
> Allow overriding UI port with environment variable

- docker/README.md
- docker/docker-compose.yaml
Update README to include dependency on running `gradlew build`
Change build context in docker-compose to enable child Dockerfiles to reference the ./server and ./ui paths
> Docker compose fix

- redis-persistence/build.gradle
As mentioned in https://github.com/Netflix/conductor/issues/290, the dependency for `dyno-jedis` needs to be `1.5.6+`
Recent upgrade of `dyno-queues-redis` from `1.0.6` to `1.0.7` has downgraded `dyno-jedis` to 1.4.7 causing the issue #290.
Explicitly adding the dependency in `redis-persistence/build.gradle` to the latest (`1.5.9`, same as `dyno-core`) fixes the issue
> Fix incorrect dyno-jedis dependency version

- server/build.gradle
Currently, if you try to override system properties when launching the conductor server, those are not taken into consideration
Example : `../gradlew server -DloadSample=false -Dport=8888`
This PR adds a missing line in the gradle build to allow overrides from the command-line
> Fix : Cannot override system properties when launching the conductor server using the gradle command-line

- client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java
Without this PR, this worker keeps polling tasks even though it is currently fully occupied, the consequence is that:
a). even if we start another instance (B) of worker to help, it may not be able to get any tasks, it would be idle even though A has tasks on the queue waiting to be executed
b). if the max size of the queue is reached, tasks would be dropped as exception happens
> polling tasks only when worker is not fully occupied

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
…ecated and using it is known to cause issues with long running tasks.
> Always return 0 for the responsetimeout.

- mysql-persistence/build.gradle
We found out that Flyway versions greater than 4.1.x are not compatible with Percona XtraDB Cluster (see open issue on Flyway project: https://github.com/flyway/flyway/issues/1556)
So as a temporary workaround, I'm downgrading to the latest Flyway version that doesn't use the locking mode incompatible with Percona which is **4.0.3**
> Downgrade Flyway version because of incompatibility with Percona 5.7 in strict mode

- docker/ui/Dockerfile
The docker build for the `conductor-ui` image fails due to missing python:
```
> dtrace-provider@0.8.6 install /app/ui/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at …
```
> Include python for node.js build

- contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java
Currently, the documentation mentions that for HTTP tasks the "contentType" parameter is supported but it turns out that it's always hardcoded to `APPLICATION_JSON`.
This PR simply adds support for using the `contentType` parameter to set the request content type if present.
If not falls back to `APPLICATION_JSON` as default.
> add support for specifying the request content type in HTTP Task

- contribs/src/main/java/com/netflix/conductor/core/events/sqs/SQSEventQueueProvider.java
- core/src/main/java/com/netflix/conductor/core/events/EventQueues.java
- core/src/main/java/com/netflix/conductor/core/events/queue/dyno/DynoEventQueueProvider.java
- core/src/test/java/com/netflix/conductor/core/events/MockQueueProvider.java
- core/src/test/java/com/netflix/conductor/core/events/TestEventProcessor.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestEvent.java
Replace the `QueueType` enum with a plain `String`. It currently works as a bit of a constraint, preventing the addition of queue types that are not known at compile time.
Aside from allowing unknown queue types to be registered at runtime, there is also a behavior change. If previously known queue types were not registered for some reason (e.g. starting up without the contribs module, so `QueueType.sqs` was not registered), would result in returning `null` at the `EventQueues.getQueue` level.
> Replace QueueType with String

- mysql-persistence/.gitignore
- mysql-persistence/build.gradle
- mysql-persistence/dependencies.lock
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/ExecuteFunction.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/LazyToString.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLBaseDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLWorkflowModule.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/Query.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/QueryFunction.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/ResultSetHandler.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/TransactionalFunction.java
- mysql-persistence/src/main/resources/db/migration/V2__queue_message_timestamps.sql
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/EmbeddedDatabase.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLBaseDAOTest.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAOTest.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAOTest.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLQueueDAOTest.java
- mysql-persistence/src/test/resources/logback-test.xml
- versionsOfDependencies.gradle
@picaron This is a sample of the `java.sql.*` only implementation from #424 , I've included the `MetadataDAO` implementation- all the new work is in the `com.netflix.conductor.dao.jdbc` package so that it's easier to compare side by side with the existing `com.netflix.conductor.dao.mysql` package.
Maintain the same developer flow and ergonomics that @picaron set with the usage of the Sql2o library and `MySQLBaseDAO`.
I essentially reused all existing queries, just swapping out named params for standard `PreparedStatement` bind question marks, `?`.
I created a few `@FunctionalInterface` instances for Java 8 style `Consumer` and `Function` patterns that allow for `SQLExceptions` to be handled by wrapper methods in the `JdbcBaseDAO` and `Query` classes.
The `jdbc.JdbcBaseDAO` mimics the …
> Sql2o removal for MySQL JDBC

- gradle/wrapper/gradle-wrapper.properties
This has better support for Java 10 as well as various other features and fixes.
> Upgrade to latest Gradle version 4.7.

- redis-persistence/src/main/java/com/netflix/conductor/dao/RedisESWorkflowModule.java
- server/src/main/java/com/netflix/conductor/server/ServerModule.java
There was already some duplicated code in these two modules, but the Redis module was not actually used anywhere.  I think that this simplifies things quite a bit and makes it consistent with how we are loading the MySQL module.  Also, this seems like a better place to contain the initialization code, since it is co-located with the actual bindings and scoped to the module that actually needs them.
> Move Dyno configuration from ServerModule to RedisESWorkflowModule.

- client/dependencies.lock
- contribs/dependencies.lock
- core/dependencies.lock
- es5-persistence/dependencies.lock
- jersey/dependencies.lock
- mysql-persistence/dependencies.lock
- redis-persistence/dependencies.lock
- server/dependencies.lock
- test-harness/dependencies.lock
- versionsOfDependencies.gradle
Bumped up spectator to version v0.68.0
Conductor was using a very old version of spectator: 0.40.0.
This works fine; however, gauges were not being passed through to underlying
registries if you wanted to integrate or collect metrics via datadog or some
other integraton framework.
However, in version 0.45.0, Spectator eventually added support to passing gauges
through to underlying registries (https://github.com/Netflix/spectator/pull/353).
This is just an attempt to upgrade the spectator version to the latest.
> Bump spectator version to version 0.68.0

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/WorkflowServiceTest.java
Since tasks in progress for the workflow instance is checked every time a task is scheduled, system tasks do not need explicit handling of the `executed` flag, they will follow the same path as user defined tasks.
> Fix for scheduling tasks after executing system tasks

- ui/src/components/workflow/executions/WorkflowList.js
Because it's a server side pagination - this UI fix will cause some side effects: 
Even though it shows 100 total items at the bottom of the page, we'll only display  97 or so;
instead of total 1000, the user will only see 997 etc.
> filter out COMPLETED workflows from the returned lists of the RUNNING items

- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAOTest.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLPushPopQueueDAOTest.java
@cyzhao . I see dev builds are failing because I am running some of MYSQL test cases with 5 concurrent threads. It may be related with embedded database used in the MYSQL Testcases
https://github.com/Netflix/conductor/blob/1c31b5b94ea04a07c53687709679d2f96e97c8ed/mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLBaseDAOTest.java#L31
The embedded database may be failing when running with concurrent threads. I have changed two just 2 concurrent threads instead of 5.
Please review and approve the PR at your convenience.
> updated mysql test cases with two threads

- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- docker/server/config/config-local.properties
- docker/server/config/config-mysql-grpc.properties
- docker/server/config/config-mysql.properties
- docker/server/config/config.properties
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/es5/EmbeddedElasticSearchV5Provider.java
Currently, the property `db` determines how we run the storage (redis, mysql...) and the indexing(elastic search). The main disadvantage of this approach is the lack of flexibility: we cannot run an `in-memory db` and `external elastic search` or viceversa.
This PR adds a property `workflow.elasticsearch.instanceType` so we are able to run an external or in-memory instance regardless of the option chosen for db.
In addition to that, this may benefit also how tests are run on the CI tool as we could have a in memory db with an external hosted elastic search instance.
> Elasticsearch property decoupling from db

- contribs/src/test/java/com/netflix/conductor/contribs/http/TestHttpTask.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/dao/QueueDAO.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- core/src/main/java/com/netflix/conductor/service/TaskService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLQueueDAOTest.java
- redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/queue/DynoQueueDAO.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/WorkflowServiceTest.java
* Evaluate response timeout seconds only if the task is IN_PROGRESS and not present in the queue. This means that the task was put into the queue with a callbackAfterSeconds value.
* Reset callbackAfterSeconds for a task when it is given to a worker for execution through a poll.
> fix response timeout seconds evaluation

- docker/server/Dockerfile
- docker/serverAndUI/Dockerfile
This replaces the base images for Conductor Server with openjdk. The "java" images were deprecated 12/31/2016, so the versions of alpine and JRE 8 are rather old in these images.
In testing, I found some issues with these versions of JRE / Alpine when deploying to Docker in Windows using the overlay file system. Elasticache was unable to run due to file system errors.
> Dockerfile java image updates

- docker/ui/Dockerfile
Gulp and perhaps other dependencies have issues with 10.  Ref: https://github.com/gulpjs/gulp/issues/2162.
The short term fix is to pin the Dockerfile node version to 9 until someone can update the dependencies to work with 10.
> Pin the Nodejs version to 9. 

- grpc-server/build.gradle
- grpc-server/src/main/java/com/netflix/conductor/grpc/server/GRPCServer.java
- grpc-server/src/main/java/com/netflix/conductor/grpc/server/GRPCServerConfiguration.java
- grpc-server/src/main/java/com/netflix/conductor/grpc/server/GRPCServerProvider.java
- Having the ability of enabling reflection on the grpc server will allow grpc clients to know which services are exposed.
- The feature can be controlled through the property `conductor.grpc.server.reflection.enabled`. By default the feature is enabled.
> GRPC server reflection support 

- docker/grpc/docker-compose.dependencies.yaml
- server/src/main/java/com/netflix/conductor/bootstrap/Main.java
There were some issues with the docker-compose configuration for elastic search.  They were preventing the application from starting correctly.  It seems like they were due mostly to change in the underlying ES version and its configuration.
I also improved the error handling and output of `Main` in order to make these failures more clear.
> Fix elastic search configuration issues.

- core/src/main/java/com/netflix/conductor/service/MetadataService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
- core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAO.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAOTest.java
- redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisMetadataDAO.java
- redis-persistence/src/test/java/com/netflix/conductor/dao/dynomite/RedisMetadataDAOTest.java
enforcing responseTimeoutSeconds field to be not null whenever task definition gets created or updated (default is 1h)
> add responseTimeoutSeconds field validation

- core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
Not sure why this was not set originally, but setting the `reasonForIncompletion` message on the subworkflow task if the subworkflow failed. This allows error messages to propagate to the parent without needing to drill down to the subworkflow if something failed.
> fix: Set the reasonForIncompletion on the subworkflow task if subworkflow failed

- client/python/conductor/conductor.py
-> When **GET /metadata/workflow/{name}** is called without a version, conductor returns the latest version
Line 110: Conductor python library defaults to version=1 instead
-> When **GET /workflow/running/{name}** is called without version, conductor returns all the running workflows for all versions
Line 203: Conductor python library default, only gets version=1 instead
-> When **POST /workflow** is sent an object without the 'version' key, it starts the latest version of that workflow
Line 211: Conductor python library defaults to run the version=1 instead
Line 266: unneccessary ';' at the end of line
Line 287: wfc.terminateWorkflow(wfId) returns nothing
**This commit fixes the problems stated above**
> Fixed minor inconsistencies in conductor's python api

- common/src/main/java/com/netflix/conductor/common/metadata/events/EventHandler.java
- contribs/src/main/java/com/netflix/conductor/contribs/queue/QueueAdminResource.java
- contribs/src/main/java/com/netflix/conductor/contribs/queue/QueueManager.java
- contribs/src/test/java/com/netflix/conductor/contribs/queue/sqs/TestQueueManager.java
- core/src/main/java/com/netflix/conductor/core/events/ActionProcessor.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- core/src/test/java/com/netflix/conductor/core/events/TestActionProcessor.java
- grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
- grpc/src/main/proto/model/eventhandler.proto
- Currently, the event handler uses the workflowId and taskRefName in the message payload to lookup the task. Updated the event handler to lookup the task by taskId if it is available in the message payload. 
-Updated to ack the message when no matching waiting tasks are found for the message.
> Updated event handling to lookup tasks by id if available

- common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java
- common/src/test/java/com/netflix/conductor/common/run/TestTaskSummary.java
In `TaskSummary` class,  missed no-arguments constructor, but it is necessary for jersy `getEntity` method to parse to object. If missed, a exception broken out, for example:
```
Caused by: com.sun.jersey.api.client.ClientHandlerException: 
com.fasterxml.jackson.databind.JsonMappingException: 
Can not construct instance of com.netflix.conductor.common.run.TaskSummary: 
no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
```
So, add no-arguments constructor to resolve it .
> fix TaskSummary Serializing, missed no-arguments constructor

- client/src/test/java/com/netflix/conductor/client/http/MetadataClientTest.java
- client/src/test/java/com/netflix/conductor/client/metadata/workflow/TestWorkflowTask.java
- client/src/test/resources/tasks.json
- common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
- core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/EventTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/JoinTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/WaitTaskMapper.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapperTest.java
- grpc/src/main/proto/model/task.proto
- grpc/src/main/proto/model/taskdef.proto
- redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisExecutionDAO.java
- Changed responseTimeoutSeconds type to `long` from `int` to avoid overflows.
- For a `SUB_WORKFLOW` task spawned from a dynamic fork task, the sub workflow version and definition needs to be pulled in from the DAO.
- Do not update end time if it is already set, only set end time for tasks in terminal state.
> Refactor and fixes

- client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java
- client/src/test/java/com/netflix/conductor/client/task/WorkflowTaskCoordinatorTests.java
- core/src/main/java/com/netflix/conductor/service/TaskService.java
- server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
Do not return the task from the client to the server if the ack fails or throws an exception. The task will be available to be polled again in this case after the unack timeout. 
The catch all in the task service ensures that even if the ack fails on the server side due to an exception with the queueDAO, the client sees an ack failure and does not process the task.
> Donot return task ack failed

- jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java
UpdateTask produced the task-id as string. As the json producer does not quote the string
correctly, json consumer will fail, as the id is taken as literal. Changing the producer to text/plain should fix this problem. However to avoid breaking changes, application/json is still produced.
> Change UpdateTask resource to produce text/plain

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/PollData.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
Removed the fallback to the default domain if an active domain is not found.
Changed this such that it falls back to the lowest priority domain specified in the list.
> remove fallback to default domain

- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
Added missing "https" for ElasticSearch Rest.  Made the ElasticSearch cluster color configurable.  This defaults to "green" but you can set "workflow.elasticsearch.cluster.health.color" to yellow.  This allows Conductor to work with AWS ElasticSearch clusters with 1 node that never change to green.
> Added missing "https" for ElasticSearch Rest

- docs/docs/server/index.md
when specifying multiple nodes with ; between them (as in redis), it fails to connect
> docs: note that es cluster configuration should be one node

- server/src/main/java/com/netflix/conductor/server/RedisClusterModule.java
- JedisCommands with READ_CLIENT_INJECTION_NAME
- Shard Supplier
@cyzhao This is dev tested with redis cluster setup and executed a workflow successfully
> adds missing binding for redis cluster module

- client/python/conductor/conductor.py
- jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java
As raised in #764 the task update API response has changed and no longer returns a JSON formatted string. This breaks the Python client when it tries to parse the response as a JSON response. 
This change updates the task POST endpoint to allow `'Accept': 'text/plain'` headers and implements the corresponding change in the Python client so that it does not expect a JSON response. I have left the `MediaType.APPLICATION_JSON` as valid response type so that any clients that are currently expecting such a response do not break with the change assuming they are able to parse the non JSON formatted string.
> Fix Python client task update procedure 

- docker/docker-compose.yaml
This patch reduces the amount of logs that get stored on the filesystem with the docker-compose. Running throughput tests on my local machine consumes gigs per minute without this.
> Truncated logging in docker-compose

- contribs/src/test/java/com/netflix/conductor/contribs/http/TestHttpTask.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
workflow does not have task definition attached to http tasks so we can get it on demand when necessary rather than adding it to every workflow.
> fix retries logic for failed http tasks

- client/go/conductorworker.go
Previously, when there was an error returned from a `ConductorWorker` `Execute` function, there was no indication of what the error returned was. In this PR, I modified the `log.Println` to print the error message returned
> add error message to failed executeFunction

- client/python/conductor/ConductorWorker.py
I verified that in your ConductorWorker in Python you aren't verifying if the task was ACKed before executing it, enabling two different workers to be executing the same task.
I expect this commit will resolve the issue.
> Verify if task is ACKnowledgeable before executing it on Python worker

- client/python/conductor/conductor.py
Naming of the _registerTaskDef_ function is misleading since `PUT /metadata/taskdefs` [updates a task definition](https://netflix.github.io/conductor/runtime/#task-workflow-metadata). Proper name should be _updateTaskDef_
> fix(py-client): proper naming for task def update function

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
- common/src/test/java/com/netflix/conductor/common/workflow/WorkflowDefTest.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapperTest.java
- core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
Description:
Change WorkflowDef default schema version to 2.
Implications:
This require changes in way you define input parameters for WorkflowTask. For schema version 1 you don't need to pass $ for input parameter expression resolution but for schema version 2 you need to pass in following format ${workflow.input...} for mapping.
```
WorkflowTask workflowTask = new WorkflowTask();
Map<String, Object> ip1 = new HashMap<>();
if (schemaVersion <= 1) {
ip1.put("p1", "workflow.input.param1");
ip1.put("p2", "workflow.input.param2");
} else {
ip1.put("p1", "${workflow.input.param1}");
ip1.put("p2", "${workflow.input.param2}");
}
workflowTask.setInputParameters(ip1);
```
> Change WorkflowDef default schema version to 2

- client/go/conductorworker.go
Previously, when an non-nil error value was returned from the `executeFunction`, the conductorworker was returning early, before sending an update to conductor that the task failed.
In this PR, I modified the `Execute` method to properly handle errors
> ConductorWorker execute function error is now handled

- client/go/conductorhttpclient.go
Previously, the ConductorHttpClient methods were all returning `nil` instead of the error.
> conductor ConductorHttpClient methods now return errors

- client/src/main/java/com/netflix/conductor/client/exceptions/ConductorClientException.java
- client/src/main/java/com/netflix/conductor/client/exceptions/ErrorResponse.java
- client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
- common/src/main/java/com/netflix/conductor/common/validation/ValidationError.java
- core/src/main/java/com/netflix/conductor/service/AdminService.java
- core/src/main/java/com/netflix/conductor/service/TaskService.java
- core/src/test/java/com/netflix/conductor/service/TaskServiceTest.java
Description:
- Reverting the change where workerId is required in /tasks/{taskId}/ack API.
- Removing some queryParam which were made required in service layer.
> revert changes for workerId required in /tasks/ack API

- client/python/conductor/conductor.py
The [latest changes](https://github.com/Netflix/conductor/commit/757d917c06ec49ae85eb414445e61706f5f18bb0) of the _ConductorWorker.poll_and_execute_ function broke the client for me since the return value of _TaskClient.ackTask_ is wrong (at least for python3.7). The result of the _self.post_ function call in _ackTask_ returns the boolean _True_ instead of the expected _'true'_ string and therefore _ackTask_ returns _False_ even though the ack request was successful. The root of this is the ___return_ function where _resp.json()_ parses the value _true_ of response body to the boolean _True_.
> [python client] fixed TaskClient.ackTask return value

- redis-persistence/dependencies.lock
- redis-persistence/src/main/java/com/netflix/conductor/jedis/ConfigurationHostSupplierProvider.java
- redis-persistence/src/test/java/com/netflix/conductor/jedis/ConfigurationHostSupplierProviderTest.java
- server/README.md
- server/dependencies.lock
- test-harness/dependencies.lock
- versionsOfDependencies.gradle
This updates Conductor to use changes in the `dyno` library to connect to Redis instances requiring password authentication.  It does so by parsing an optional 4th colon-delimited string from `workflow.dynomite.cluster.hosts` to set the password on the underlying `Jedis` client. (shown below)
I'm looking for any feedback to support getting this change merged.
---
See Netflix/dyno#244 for the underlying changes, included as transitive dependency with `dyno-queues:2.0.0-rc5` upgrade.
https://github.com/Netflix/dyno/blob/v1.6.5/dyno-jedis/src/main/java/com/netflix/dyno/jedis/JedisConnectionFactory.java#L80-L93
> Redis Authentication Support

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
First modify the current workflow state and then schedule the task. Otherwise, the status of the workflow may be incorrect, which may cause the COMPLETE state to return to the RUNNING state.
> fix concurrent workflow state modify problem.

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/metadata/MetadataMapperService.java
- jersey/src/main/java/com/netflix/conductor/server/resources/WebAppExceptionMapper.java
* Added precondition check to determine exact place for NPE
* Fixed NPE in WebApplicationExceptionMapper
> Fixed NullpointerException in couple of places

- core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
- core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
Description:
Previous validation required caseParam field to be set for DECISION task which broke the Workflow task using caseExpression field in Decision Task. This PR fixes the validation by making caseParam or caseExpression as required.
> (fix): Allow caseParam or caseExpression as required for Decision task

- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchDAOV6.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchRestDAOV6.java
As the ES5 DAO code was updated in master recently, but ES6 was not, I am filling this gap by this pull request to keep the consistent behavior across them.
> Fixed the behavior of the ES6 DAO to be the same as ES5 DAO

- CONTRIBUTING.md
One of the steps for `CONTRIBUTING.md` referred to forking `Dynomite`.
Fixed that by changing it to `conductor`.
> Fix Minor error in `CONTRIBUTING.md`

- README.md
Changed the "Getting Started" with conductor link to https://netflix.github.io/conductor/gettingstarted/basicconcepts/.
The old link was a 404.
> Fixed 404 link in README.md

- contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java
- contribs/src/main/java/com/netflix/conductor/contribs/http/RestClientManager.java
- contribs/src/test/java/com/netflix/conductor/contribs/http/TestHttpTask.java
- contribs/src/test/java/com/netflix/conductor/contribs/http/TestRestClientManager.java
- server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
1) Adds ReadTimeout and connection timeout to HTTP Tasks. 
We take the parameters from HTTP input. If they are not present,  then timeouts from config are used. 
2) I have removed the input parameter in the RestManager.getClient method as it is an unused parameter. 
3)  RestManager.getClient uses threadlocal to create clients as we are modying the client object from various threads currently.
> Adds HTTP TaskTimeouts

- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraExecutionDAO.java
- client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
- contribs/src/main/java/com/netflix/conductor/contribs/http/RestClientManager.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Lambda.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapperTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
- Removing all the new tasks created if creation/enqueuing of a task fails, essentially resetting workflow state.
- If exception is thrown during starting a new workflow, remove this workflow from the database before propagating the exception back in the response.
- Terminate the workflow with failure, if script evaluation fails in a decision task.
- Cleaned up some logs.
> rollback workflow to previous state if new task creation/enqueuing fails

- ui/src/api/wfegraph.js
- ui/src/components/common/Grapher.js
When hovering on a task it will show the description of the task to make it easier to understand the purpose of the task in both the workflow definition and execution pages.
>  Show tooltip based on task description in UI

- server/src/main/resources/swagger-ui/index.html
This replaces the "http://localhost:8080" in SwaggerUI with the current origin
> Fix SwaggerUI URL detection

- es5-persistence/README.md
- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAOV5.java
- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
- es5-persistence/src/test/java/com/netflix/conductor/elasticsearch/TestElasticSearchConfiguration.java
- es6-persistence/README.md
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchDAOV6.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchRestDAOV6.java
- es6-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
- es6-persistence/src/test/java/com/netflix/conductor/elasticsearch/TestElasticSearchConfiguration.java
Issue: 
The executor service used in async functions of Indexdao's has workerQueue Size as unbounded. 
new LinkedBlockingQueue<>() -> This creates a blocking queue size of Integer.MAX_VALUE. 
During high throughput, tasks are queued in the Linkedblocking queue due to which memory is exhausted. This is causing GC issues. 
Following are the changes. 
1. I am limiting the size to 100 by default
2. Read from configuration if this needs to be changed. 
@cyzhao @apanicker-nflx @mashurex @kishorebanala
> Limit configuration for worker queue size of Async Index Dao

- common/src/main/java/com/netflix/conductor/common/utils/ConstraintParamUtil.java
- common/src/test/java/com/netflix/conductor/common/utils/ConstraintParamUtilTest.java
- common/src/test/java/com/netflix/conductor/common/workflow/WorkflowDefTest.java
Hi everyone. This PR is motivated by the conversation that we had in issue #1115. 
It seems that there is a validation step in the code that doesn't allow empty strings to be input parameters. However, I don't see why we should not have empty strings as input parameters. It was possible before, and it resulted in errors for me in an updated version of conductor.
I ran the unit tests but didn't define and execute a workflow with empty strings as input parameters after my changes (yet...)
> Remove validation of empty strings.

- es6-persistence/dependencies.lock
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchRestDAOV6.java
Addresses #1147 
When Gradle is reconfigured to compile against the `conductor-es6-persistence` module, the project fails to compile as follows:
```
| => ../gradlew clean build -x test
> Configure project :
Inferred project: conductor, version: 2.13.0-SNAPSHOT
Publication nebula not found in project :.
> Task :conductor-es6-persistence:compileJava FAILED
/path-to-conductor/es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchRestDAOV6.java:144: error: incompatible types: RestClient cannot be converted to RestClientBuilder
this.elasticSearchClient = new RestHighLevelClient(restClientBuilder.build());
^
Note: /path-to-conductor/es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchRestDAOV6.java uses or overrides a deprecated API.
Note: …
```
> Fixes compilation for ES6 configuration

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Reset task start time when rerunning a workflow from a specific task to prevent workflow from timing out using the old value of start time.
> Issue 1148 : Reset start time when rerunning a workflow from that task

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/TaskType.java
- contribs/build.gradle
- contribs/src/main/java/com/netflix/conductor/contribs/kafka/KafkaProducerManager.java
- contribs/src/main/java/com/netflix/conductor/contribs/kafka/KafkaPublishTask.java
- contribs/src/test/java/com/netflix/conductor/contribs/kafka/TestKafkaProducerManager.java
- contribs/src/test/java/com/netflix/conductor/contribs/kafka/TestKafkaPublishTask.java
- core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/KafkaPublishTaskMapper.java
- core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/KafkaPublishTaskMapperTest.java
- core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
- docs/docs/configuration/systask.md
- server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
- test-harness/src/test/resources/integration/scenarios/legacy/template_kafka_workflow.json
- test-harness/src/test/resources/integration/scenarios/legacy/template_workflow_kafka.json
This PR adds a templatized Kafka task to the conductor. User can specify a Kafka template to publish as follows. 
`"kafka_request": {
"topic": "test",
"value": "${workflow.input.value}",
"bootStrapServers":"localhost:9092",
"headers" :{
"Content":"${workflow.input.header}"
},
"key":"123",
"keySerializer":"org.apache.kafka.common.serialization.IntegerSerializer"
}
`
With this, the conductor can work with microservices listening to Kafka queues. 
@cyzhao @kishorebanala  @apanicker-nflx Please take a look if you think this can be a useful addition to the conductor.
> Adds kafka task

- client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
We use these APIs within our codebase to get event handler definitions.
> Use protected scope instead of the default scope

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/CassandraConfiguration.java
This PR fixes an apparent typo in one of three property names related to Cassandra replication that could lead to confusion during configuration/implementation.
<pre>
workflow.cassandra.replication.strategy
workflow.cassandra.replication.factor.key
workflow.cassandra.<strong>replicaton</strong>.factor.value
</pre>
> Fix typo in Cassandra replication factor property name

- client/python/conductor/ConductorWorker.py
Introduces the 'reasonForIncompletion' key into the task result returned by the python client. This key is used to display the failure reason for a task in the conductor UI. It is implemented as an optional key so that successful tasks need not designate a reason, and to maintain backwards compatibility.
> Add reasonForIncompletion to ConductorWorker.py

- client/python/README.md
Description:
Remove pip package name python readme as it is not valid.
> Fix/update readme: Remove pip install command from python readme

- docs/docs/configuration/taskdef.md
it says the `timeoutSeconds` field takes its input in terms of milliseconds, when in reality, it takes it in terms of seconds. :)
> Update timeout description

- docs/docs/configuration/systask.md
Fixed a typo line 81. The JSON was missing a comma between the two parameters in the example:
``` json
{
"sink": "sqs:example_sqs_queue_name"
"asyncComplete": false
}
```
> Fix a typo in systask.md

- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAOV5.java
- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
- es5-persistence/src/test/java/com/netflix/conductor/dao/es5/index/TestElasticSearchDAOV5.java
- es5-persistence/src/test/java/com/netflix/conductor/dao/es5/index/TestElasticSearchRestDAOV5.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/ESRestClientHttpEndToEndTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/ExclusiveJoinEndToEndTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/GrpcEndToEndTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/HttpEndToEndTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/MySQLGrpcEndToEndTest.java
This PR contains changes to index as batch in Elastic Search V5.
1) Batch size can be determined by property workflow.elasticsearch.index.batchSize.
2) Added prometheus metrics to determine queue size and indexing time.
3) Unit test
@kishorebanala @apanicker-nflx @naveenchlsn  Please look at it.
> Batch indexing in ES.

- mysql-persistence/src/main/java/com/netflix/conductor/mysql/MySQLDataSourceProvider.java
Side issue discover from https://github.com/Netflix/conductor/issues/1264
To reproduce the issue, simply do something to make flyway blowup.
for example either:
- go to database, schema_version/flyway_schema_history table - which ever you choosed to be history table, update one success to fail. 
- or update a migration script to cause checksum mismatch or bad syntax
The result is while seeing no Error/Exception, new Connection pools keep being created until MySQL runs out of connection. At this point the application will terminate, with Too many Exception error.
This change:
- Log what is specifically is the problem
- Close the connection pool before bubbling up
> close connections, log the error before propagting it up

- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraBaseDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraExecutionDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/util/Constants.java
- cassandra-persistence/src/main/java/com/netflix/conductor/util/Statements.java
- cassandra-persistence/src/test/java/com/netflix/conductor/dao/cassandra/CassandraExecutionDAOTest.java
- cassandra-persistence/src/test/java/com/netflix/conductor/util/StatementsTest.java
- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
- Added a `task_def_limit` table to track in progress tasks for a given task definition
> added concurrent execution limit impl to C* module

- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLBaseDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
See https://github.com/Netflix/conductor/issues/1263
make getWithTransaction() private, use getWithRetriedTransactions() where it was.
getWithTransactionWithOutErrorPropagation() is used by sweeper, no need to apply retry since it will naturally do so next round.
> deadlock is inavoidable, add retry on MySQL Deadlock

- common/src/main/java/com/netflix/conductor/common/utils/RetryUtil.java
This is for both server and client (Otherwise important failure like taskUpdate can be transient).
> permanent failure should log error

- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLBaseDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/Query.java
I've tried the recent retries feature for the MySQL deadlocks (https://github.com/Netflix/conductor/pull/1299) and found that there are no retries in most of the cases.
I've got to debug it and found the reason - there can be more than one nested exceptions of `ApplicationException`. Simple `throwable.getCause()` won't return a `SQLException` in this case.
In addition, I've check all places in the MySQL persistence module which throw `ApplicationException` and found one without passing the cause exception (fixed it here as well).
> MySQL deadlocks: Searching for a SQLException in all nested exceptions

- mysql-persistence/src/main/resources/db/migration/V4__1009_Fix_MySQLExecutionDAO_Index.sql
Fix for #1009 change unique_event_execution index
- Conditionally drop the `unique_event_execution` index if it exists (it should)
- Add a new `unique_event_execution` constraint using `execution_id` instead of `message_id`
The old index used `event_handler_name`, `event_name`, and `message_id` for uniqueness. The `message_id` part of the constraint causes issues with events that require multiple executions. `message_id` was swapped for `execution_id` for this case.
> Fix for MySQL unique_event_execution index bug

- common/build.gradle
- grpc/build.gradle
Hello
This commit fixes and enhances build script. Specifically, it first fixes an ordering violation between tasks `processResources` and `extractProto`. If `extractRepo` is applied before `processResouces`, the generated `proto` files are not copied into the build directory.
This is the diff of missing resources inside the build directory.
```
< resources/main/google
< resources/main/google/protobuf
< resources/main/google/protobuf/api.proto
< resources/main/google/protobuf/empty.proto
< resources/main/google/protobuf/type.proto
< resources/main/google/protobuf/compiler
< resources/main/google/protobuf/compiler/plugin.proto
< resources/main/google/protobuf/timestamp.proto
< resources/main/google/protobuf/wrappers.proto
< resources/main/google/protobuf/struct.proto
< …
```
> Fix and enhance build script

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- Added a method `resetWorkflow` to ExecutionDAOFacade to allow asynchronously archiving workflow during restarts.
- Changed `task_pending_time` metric to a gauge.
> reset workflow upon restarts

- postgres-persistence/src/main/resources/db/migration_postgres/V2__1009_Fix_PostgresExecutionDAO_Index.sql
This PR adds a postgres migration that modifies the unique_event_execution index to use execution_id instead of message_id for uniqueness. See #1099 and PR #1386 .
> postgres port of fix for #1009, modify unique_event_execution index

- azureblob-storage/.gitignore
- azureblob-storage/README.md
- azureblob-storage/build.gradle
- azureblob-storage/src/main/java/com/netflix/conductor/azureblob/AzureBlobConfiguration.java
- azureblob-storage/src/main/java/com/netflix/conductor/azureblob/AzureBlobModule.java
- azureblob-storage/src/main/java/com/netflix/conductor/azureblob/SystemPropertiesAzureBlobConfiguration.java
- azureblob-storage/src/main/java/com/netflix/conductor/storage/AzureBlobPayloadStorage.java
- azureblob-storage/src/test/java/com/netflix/conductor/config/InvalidTestConfiguration.java
- azureblob-storage/src/test/java/com/netflix/conductor/config/TestConfiguration.java
- azureblob-storage/src/test/java/com/netflix/conductor/storage/AzureBlobPayloadStorageTest.java
- docs/docs/externalpayloadstorage.md
Here is an implementation of the Azure Blob as ExternalStorage based on the new [Azure Java SDK](https://github.com/Azure/azure-sdk-for-java) which is still on preview.
I will re-update the PR once the java SDK is stable.
Documentation has been updated.
Following packages have been updated to resolve the downgrading of the dependency `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml` to 2.4.5 which is incompatible with azure blob storage sdk because of missing function [setDefaultUseWrapper](https://github.com/FasterXML/jackson-dataformat-xml/blob/2.9/src/main/java/com/fasterxml/jackson/dataformat/xml/XmlMapper.java#L133)
- `com.fasterxml.jackson.core:jackson-core` from 2.7.5 to 2.9.9
- `com.fasterxml.jackson.core:jackson-databind` from 2.7.5 to 2.9.9
- …
> Azure Blob External Storage

- docs/docs/labs/beginner.md
See #1501 for details. 
> The documentation is to be updated, but with recent updates to Conductor, we don't need to ack anymore.
> Remove the documentation on Task Ack in beginner lab

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Re: #1498 
Suggest to use the same **taskToDomain** of the terminating workflow for the failure workflow
> Set taskToDomain when starting failureWorkflow

- server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
When not using S3 as an ExternalPayloadStorageType, Conductor gets an IllegalArgumentException at startup. This bugfix gets rid of that exception. The actual exception is:
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
> get rid of ExternalPayloadStorageType exception on startup

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
- common/src/main/java/com/netflix/conductor/common/run/Workflow.java
- common/src/test/java/com/netflix/conductor/common/tasks/TaskTest.java
This PR provides a quick fix for deep copy method of Workflow. Copy method of Workflow is using the copy method from the Task model in a wrong way, since currently, the main purpose of the copy method is to help copy over required fields during retry operation.
> Fixed deep copy of task model.

- mysql-persistence/src/main/resources/db/migration/V5__correlation_id_index.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V3__correlation_id_index.sql
Currently queries on the workflow table by correlation_id are slow in large databases. This PR adds an index to the workflow table to fix this for both Postgres and MySql persistence modules
> Create Correlation id index on workflow table

- redis-lock/src/main/java/com/netflix/conductor/locking/redis/config/RedisLockConfiguration.java
- redis-lock/src/main/java/com/netflix/conductor/locking/redis/config/RedisLockModule.java
Hi,
I've added possibility to set password for redis server used for distributed lock. Password is optional (null by default) so that the old behavior is intact.
Resolves issue: https://github.com/Netflix/conductor/issues/1402
Pavel
> Set password for redis server used for distributed lock.

- contribs/src/main/java/com/netflix/conductor/contribs/ArchivingWorkflowModule.java
- contribs/src/main/java/com/netflix/conductor/contribs/listener/ArchivingWorkflowStatusListener.java
- contribs/src/test/java/com/netflix/conductor/contribs/listener/ArchivingWorkflowStatusListenerTest.java
- docs/docs/server.md
Implements issue https://github.com/Netflix/conductor/issues/1563
> Default workflow archiving module

- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraBaseDAO.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
When polling for a task, if a db operation fails on a dequeued task, this task will now be lost and the corresponding workflow will be unable to progress.
This PR addresses this issue by re-enqueueing this task with a delay so that the workflow will be unblocked.
Note that the priority of this task is set to 0 since this task need not wait for other tasks with different priority to be dequeued (as it was already dequeued once).
> added resiliency during task poll

- CONTRIBUTING.md
- LICENSE
- client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
- client/src/test/java/com/netflix/conductor/client/task/WorkflowTaskCoordinatorTests.java
- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java
- Prevent the mutation of task result object between retries in upload which can lead to precondition failures
- Update the Contributing guide with License header
- Ignore tests on deprecated `WorkflowTaskCoordinator` class
> do not mutate the taskresult object during upload retries

- docs/docs/configuration/taskdef.md
The lack of support for time-based rate limiting for a MySQL-backed Conductor seems completely undocumented. If it's documented, it's fairly hidden (I was not able to find it by specifically Googling "conductor rate limit"). It should be clearly documented in context.
> Document MySQL lack of rate limiting support

- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/BulkRequestBuilderWrapper.java
- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAOV5.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/BulkRequestBuilderWrapper.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchDAOV6.java
Fixes issue #1553. The most obvious thing I could think of is to wrap access to the BulkRequestBuilder object in `synchronized(){}`. In my own testing, this resolves the issue both for ES5 and ES6.
> Fixes issue #1553

- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
- server/src/main/java/com/netflix/conductor/noopindex/NoopEmbeddedElasticSearchProvider.java
- server/src/main/java/com/netflix/conductor/noopindex/NoopIndexDAO.java
- server/src/main/java/com/netflix/conductor/noopindex/NoopIndexModule.java
Adds a configuration parameter which, when set, completely disables use of ElasticSearch. Note that search operations which require ElasticSearch will silently fail by returning empty results.
The new configuration parameter is `workflow.indexing.enabled` with a default value of true. Setting it to false will completely disable use of ElasticSearch.
(Of course, with this configuration, significant parts of the Conductor UI will no longer function correctly. However, not all users of Conductor actually use the Conductor UI, so for such users that will not be an issue.)
> Make use of ElasticSearch optional

- common/src/main/java/com/netflix/conductor/common/constraints/OwnerEmailMandatoryConstraint.java
- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- core/src/main/java/com/netflix/conductor/service/MetadataServiceImpl.java
- core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
Addresses issue #1585 – adds a config setting `workflow.owner.email.mandatory` (with a default value of true) which controls whether ownerEmail attribute is mandatory on task definitions and workflow definitions. With the default value of true, the behaviour is the same as at present. If you change the value to false, then ownerEmail becomes an optional attribute.
Implementation is by replacing the `@NotEmpty(message = "ownerEmail cannot be empty")` annotation on ownerEmail with a new custom annotation `@OwnerEmailMandatoryConstraint`. We push the value of the config setting into the annotation validator; when the setting is true, it ensures the value is neither null nor an empty string; when the setting is false, the validation always succeeds.
> Add config setting to control whether ownerEmail is mandatory or not

- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
If the input to a FORK_JOIN_DYNAMIC task is empty (i.e. empty or non-existent dynamicForkTasksParam), ForkJoinDynamicTaskMapper.java gets a NullPointerException. This Pull Request fixes that by simulating an empty array of tasks.
> allow input to FORK_JOIN_DYNAMIC task to be empty

- mysql-persistence/src/main/resources/db/migration/V6__new_qm_index_with_priority.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V4__new_qm_index_with_priority.sql
When there is a large volume of scheduled tasks of a specific type in the queue_message table, the queries slow down significantly during polling because priority is not indexed and the ORDER BY clause uses priority. In our specific case there were 2.3 million tasks of a type and the  poll query for that type was taking 17 seconds. Adding priority to the combo_queue_message index brought that down to 4 seconds.
> add flyway files used to add priority to the combo_queue_message index

- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/query/parser/NameValue.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/query/parser/ComparisonOp.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/query/parser/ConstValue.java
- es5-persistence/src/test/java/com/netflix/conductor/elasticsearch/query/parser/TestComparisonOp.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/query/parser/NameValue.java
- es6-persistence/src/main/java/com/netflix/conductor/elasticsearch/query/parser/ComparisonOp.java
- es6-persistence/src/main/java/com/netflix/conductor/elasticsearch/query/parser/ConstValue.java
- es6-persistence/src/test/java/com/netflix/conductor/elasticsearch/query/parser/TestComparisonOp.java
Allow passing [Prefix Queries](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-prefix-query.html) e.g. `workflowType STARTS_WITH "add"`.
> Add prefix queries to es5,es6 using STARTS_WITH operator

- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
Fix typo in config key values:
- EVENT_MESSAGE_INDEXING_ENABLED_PROPERTY_NAME
- EVENT_EXECUTION_PERSISTENCE_TTL_SECS_PROPERTY_NAME
> Fix typo in config keys

- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraEventHandlerDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraExecutionDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraMetadataDAO.java
- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- core/src/main/java/com/netflix/conductor/core/events/SimpleActionProcessor.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/HTTPTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/ExecutionConfig.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/IsolatedTaskQueueProducer.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java
- core/src/main/java/com/netflix/conductor/core/utils/QueueUtils.java
- core/src/main/java/com/netflix/conductor/core/utils/SemaphoreUtil.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestIsolatedTaskQueueProducer.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskWorkerCoordinator.java
- core/src/test/java/com/netflix/conductor/core/utils/SemaphoreUtilTest.java
Instead of relying on in memory LinkedBlockingQueue to store dequeued task ids and execute them asynchronously using a threadpool, this PR provides an implementation to use a semaphore to control when a task id will be dequeued from a given system task queue based on if a thread is available for processing the task. The processing of the task will still happen asynchronously.
In the case of isolated system task queues, instead of using a separate LinkedBlockingQueue to feed the threadpool, each isolated task queue uses a separate semaphore to gate the processing of tasks in its threadpool.
> use semaphore instead of inmemory queue for processing system tasks

- docker/serverAndUI/Dockerfile
This fix the issue where
```
docker build ./docker/serverAndUI -f docker/serverAndUI/Dockerfile -t conductor:all-latest
```
can not be built because the container does not have npm. 
Check a few and found node 10.x is build-able - include NPM - and runable:
BUILD:
```
docker build ./docker/serverAndUI -f docker/serverAndUI/Dockerfile -t conductor:all-latest
```
RUN
```
docker run --rm --name conductor --rm -p 9000:8080 -p 5000:5000  -edb=memory -eworkflow.elasticsearch.instanceType=memory conductor:all-latest
```
> fix all in one dockerfile

- grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
- grpc/src/main/proto/model/taskdef.proto
Looks like `poll_timeout_seconds` field is missing in proto.
> Add the missing field (poll_timeout_seconds) to proto

- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraEventHandlerDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraMetadataDAO.java
- cassandra-persistence/src/test/java/com/netflix/conductor/dao/cassandra/CassandraDAOTest.java
In teardown of CassandraDAOTest "session is closed" errors occur. This happens because CassandraMetadataDAO and CassandraEventHandlerDAO launch threads that use session w/o checking if its closed. This PR adds a check to ensure session is not closed before using.
> Check if Cassandra session is closed before using

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/WorkflowLegacyMigrationTest.java
Updating Terminate task to explicitly call `WorkflowExecutor`'s `completeWorkflow` or `terminateWorkflow`, over ending the workflow loop within decide. This will ensure the cleanup actions as part of a Workflow are performed, eg., to call decide on parent workflow, or to invoke `WorkflowStatusListener`, if enabled.
While this still is a minor improvement on current work around for TERMINATE task, this can be further improved by moving away the ad-hoc logic from `WorkflowExecutor.decide`.
> Updating Terminate task

- contribs/build.gradle
- contribs/src/main/java/com/netflix/conductor/contribs/metrics/LoggingMetricsModule.java
- contribs/src/main/java/com/netflix/conductor/contribs/metrics/MetricsRegistryModule.java
- contribs/src/test/java/com/netflix/conductor/contribs/metrics/LoggingMetricsModuleTest.java
- docker/server/bin/startup.sh
- docker/server/config/config.properties
- docker/server/config/log4j-file-appender.properties
- docker/server/config/log4j.properties
- docs/docs/metrics/server.md
Add log4j metrics collector into contribs/ project.
This new component can be enabled via configuration and dump collected
metrics periodically into a log4j appender (file, console...).
Also allow log4j properties customization.
Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
> Metrics logging collector

- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/BulkRequestWrapper.java
- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/BulkRequestWrapper.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchRestDAOV6.java
As per https://github.com/Netflix/conductor/issues/1553, there is a race condition in `BulkRequestBuilder` class of ElasticSearch which is used in ElasticSearchDAO transport client. In our setup, this NullPointerException happens in case of ElasticSearchRestDAO as well. ElasticSearchRestDAO uses `BulkRequest` object which in turn uses `ArrayList` to maintain the index requests is not synchronized. Hence this problem occurs in Rest implementation as well. So using an approach similar to https://github.com/Netflix/conductor/pull/1554 to use thread-safe wrapper for Rest implementation as well. Verified that in high throughput scenario the NullPointerExceptions are happening no more. Thanks, @skissane for the initial solution.
> ElasticSearch Rest  BulkIndex NPE fix for Race condition

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java
When workflows get paused or resumed, indexDAO.indexWorkflow() is not invoked so the workflow status stays at RUNNING even if it is PAUSED. Therefore you cannot get an accurate list of workflows when using workflow/search with freeText of status:PAUSED. This calls indexWorkflow() when the workflow is paused or resumed.
> Update elasticsearch when workflows get paused/resumed

- ui/src/components/common/Grapher.js
This PR will add a "View Subworkflow" link to the pop up menu when viewing a subworkflow task of an execution.
Right now there is an option to view a parent workflow from inside of a subworkflow, but there is no option to view the subworkflow from the parent workflow.
This would help users who are troubleshooting or checking their executed workflows.
> Added link to view a subworkflow execution

- core/src/main/java/com/netflix/conductor/core/execution/mapper/DoWhileTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
As a System task, the DO_WHILE task should not be required to have a task definition as it makes it difficult to have it not time out. This PR makes it optional.
> Make the task definition optional for the DO_WHILE task

- docs/docs/labs/kitchensink.md
- server/src/main/java/com/netflix/conductor/jetty/server/JettyServer.java
- server/src/main/resources/kitchenSink-ephemeralWorkflowWithEphemeralTasks.json
- server/src/main/resources/kitchenSink-ephemeralWorkflowWithStoredTasks.json
- server/src/main/resources/kitchensink.json
- server/src/main/resources/sub_flow_1.json
Fix kitchensink example:
- set output of the task with `outputData` key
- set `ownerEmail` property to workflow and task definitions since it is mandatory
> Fix kitchensink example

- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAOV5.java
- es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
- es6-persistence/src/main/java/com/netflix/conductor/dao/es6/index/ElasticSearchDAOV6.java
- es6-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
When query elasticsearch if size is not specified ES server will serve only 10 first entries by default, this caused lost of task_log on conductor-ui
Assuming we have lots of task logs entries:
```
TASK_ID=$1
for i in {1..20};
do curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' "http://localhost:9000/api/tasks/$1/log" -d "$i";
done
```
Currently we can only see:
After the change, started with `task_elasticsearch_query_size=20`
```
docker run --rm --name conductor -p 9000:8080 -p 5000:5000  -edb=memory -eworkflow.elasticsearch.instanceType=memory -etask_elasticsearch_query_size=20 s50600822/conductor:all-tasklog-limit-4
```
> tasklog limit - allow more than 10 entries

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutorModule.java
- server/src/main/java/com/netflix/conductor/server/ServerModule.java
Monitor for calculating metrics `com.netflix.conductor.service.WorkflowMonitor`is not initialized and so metrics like `task_queue_depth`, `workflow_running` are not captured. So initializing it in `WorkflowExecutorModule`.
> Initialize workflow monitor

- docs/docs/externalpayloadstorage.md
Tiny improvement to docs:
Before:
After:
> Fixing table in documentation

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisPollDataDAO.java
Remove the reliance on PollDataDAO in the critical execution path of a workflow. If the poll data DAO is unavailable, fallback to the last domain in the provided list of domains for a task instead.
> use fallback domain if pollDataDAO is unavailable

- core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
My dowhile-retries PR used a HashMap to store relevant tasks from the loopOver tasks. This potentially processed tasks out of order and affected output. Made that map a LinkedHashMap to maintain the task order.
> DO_WHILE fix: make relevantTasks a LinkedHashMap to process tasks in order

- cassandra-persistence/src/test/java/com/netflix/conductor/config/TestConfiguration.java
- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- core/src/main/java/com/netflix/conductor/core/config/SystemPropertiesConfiguration.java
- core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java
- core/src/test/java/com/netflix/conductor/core/execution/TestConfiguration.java
- mysql-persistence/src/test/java/com/netflix/conductor/config/TestConfiguration.java
- postgres-persistence/src/test/java/com/netflix/conductor/config/TestConfiguration.java
- redis-persistence/src/test/java/com/netflix/conductor/config/TestConfiguration.java
- test-harness/src/test/java/com/netflix/conductor/tests/utils/MockConfiguration.java
Please consider making event execution indexing optional. Since it is not used for any logic directly, it can be made optional and can help reduce i/o.
> Optional event execution indexing

- client/src/main/java/com/netflix/conductor/client/telemetry/MetricsContainer.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/query/parser/ComparisonOp.java
- es5-persistence/src/test/java/com/netflix/conductor/elasticsearch/query/parser/TestComparisonOp.java
- es6-persistence/src/main/java/com/netflix/conductor/elasticsearch/query/parser/ComparisonOp.java
- es6-persistence/src/test/java/com/netflix/conductor/elasticsearch/query/parser/TestComparisonOp.java
- Fix `BETWEEN` operator
Fix the parsing of the operator
- Ensure task is cancelled when terminating a workflow
Remove tasks from the queue first so that polling for tasks will not retrieve these
Update task status to CANCELED 
Update workflow status to TERMINATED
> fix BETWEEN operator; ensure task cancellation when terminating workflow

- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/ExecutionConfig.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskExecutor.java
- core/src/main/java/com/netflix/conductor/core/utils/SemaphoreUtil.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskExecutor.java
- core/src/test/java/com/netflix/conductor/core/utils/SemaphoreUtilTest.java
Using batch polling for system tasks from the queues. It will be very helpful for high throughput scenarios where large number of system tasks are executed and can possibly reduce the i/o (number of lookups in queues). It can be controlled by `workflow.system.task.queue.pollCount` configuration.
> Support to batch poll system tasks

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/service/WorkflowService.java
- core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/service/WorkflowServiceTest.java
- jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
- test-harness/src/test/groovy/com/netflix/counductor/integration/test/SimpleWorkflowSpec.groovy
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
- Reset the callbacks for only non-terminal tasks in the workflow.
- Reset callbacks for only SIMPLE tasks for which the workers set invisibility callbacks.
> fix reset callbacks api

- client/python/conductor/ConductorWorker.py
The execution of a polled task was conditioned by the return of self.taskClient.ackTask which was required to be True. This was never happening because task Ack has been made a Nop and the python client has been left behind (as per discussion on gitter community).
I don't know whether ack TAsk should be removed altogether but in the meanwhile consider removing the if.
Please consider this as a followup of a discussion on gitter.im:
> > Hi all. I started evaluating Conductor with current docker images (server,ui,dynomite,elasticsearch). I am trying to write a complete rest client starting from python example. After polling succesfully for a task, the ack request returns Always false thus preventing execution. Now I forced the condition to true in the if stmt checking the ack outcome and …
> Removed blocking conditional on ack Task before execution

- contribs/src/main/java/com/netflix/conductor/contribs/AMQPModule.java
Rename StringMapKey for amqp queue from "amqp" to amqp_queue"
Issue: https://github.com/Netflix/conductor/issues/1745#issue-642554258
Related comments:
https://github.com/Netflix/conductor/pull/1589#issuecomment-641851944
> Fix issue in which messages are not handled by event-handler when using 'amqp:' key

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/ExecutionConfig.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/DoWhileTest.java
- test-harness/src/test/groovy/com/netflix/counductor/integration/test/SimpleWorkflowSpec.groovy
- test-harness/src/test/resources/simple_workflow_1_integration_test.json
- Fixed input param replacement in the retried tasks when a workflow a retried
- Allow TIMED_OUT tasks (hence the workflows) to be retried
> fix input param replacement when workflow is retried

- client/src/main/java/com/netflix/conductor/client/telemetry/MetricsContainer.java
fix typo in `MetricsContainer`:
WORFLOW_TYPE -> WORKFLOW_TYPE
> Fix typo in MetricsContainer 

- common/src/main/java/com/netflix/conductor/common/run/ExternalStorageLocation.java
fix typo about <li> , make `ExternalStorageLocation` doc more readable.
> Make ExternalStorageLocation doc more readable

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
We hit an issue where the actual exception was being ghosted/overriden by the fact that the remove workflow call would throw an exception as well (because the workflow was not able to be inserted). This can happen if there's a DB exception (like when we are using Mysql). In this case, we want to be able to get *both* exceptions logged so we can figure out what's happening :)
Before this fix, all that we would get in the log was
```
1825727 [qtp988170450-308] ERROR com.netflix.conductor.core.execution.WorkflowExecutor  - Could not remove the workflowId: eae62d92-9e28-49b1-8b35-091042ebbfe4
com.netflix.conductor.core.execution.ApplicationException: No such workflow found by id: eae62d92-9e28-49b1-8b35-091042ebbfe4
at com.netflix.conductor.core.orchestration.ExecutionDAOFacade.getWorkflowById …
```
> Better error handling when trying to create a workflow

- cassandra-persistence/src/main/java/com/netflix/conductor/dao/cassandra/CassandraExecutionDAO.java
- contribs/src/main/java/com/netflix/conductor/contribs/ArchiveWorkflowStatusListenerProvider.java
- contribs/src/main/java/com/netflix/conductor/contribs/ArchivingWorkflowModule.java
- contribs/src/main/java/com/netflix/conductor/contribs/listener/ArchivingWithTTLWorkflowStatusListener.java
- contribs/src/main/java/com/netflix/conductor/contribs/listener/ArchivingWorkflowStatusListener.java
- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java
- core/src/main/java/com/netflix/conductor/dao/ExecutionDAO.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/test/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacadeTest.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresExecutionDAO.java
- redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisExecutionDAO.java
Added new workflow status listener called `ArchivingWithTTLWorkflowStatusListener` that supports delayed archiving and setting time-to-live for the documents in Redis for now (can be extended to Cassandra later). 
`Delayed Archiving`: It is required in cases where short workflows are indexed after a delay and `updateIndex` will fail in those cases since the document might not exist. Further, when using async indexing, in case of high throughput scenarios, an asynchronous create document index request could be pending in the `indexQueue`, and the synchronous update request will fail due to missing document. 
`Time-to-live`: It is helpful in the case of `TERMINATED` workflows. If the parent workflow is terminated and then sub-workflow is canceled. In those cases, the task worker could still …
> Extend archive module to support TTL and delay

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
Recently a change was made to put the subWorkflowId attribute of Task.java at the root of the Task JSON. Prior to this it was stored in the inputData of the Task. The getSubWorkflowId() method was changed to get it from the root now but that doesn't account for sub_workflow tasks that were created before the change. This PR checks both places so that new code expecting it at the root level will still work with older sub_workflow tasks.
> get subWorkflowId from inputData if it is an old SUB_WORKFLOW task

- test-harness/src/test/groovy/com/netflix/counductor/integration/test/WorkflowAndTaskConfigurationSpec.groovy
Following tests are converted:
- Workflow with no tasks
- Task def template
> convert junit tests to spock specs

- ui/src/auth/strategies/ldapauth.js
Currently the groups returned from the LDAP server are only the direct memberships of the user.
Big enterprises usually use nested groups to allow easier creation of new employees.
I modified the ldap initialization script based on [this](https://stackoverflow.com/questions/51270427/passport-ldapauth-get-nested-groups)
> UI LDAP Auth - Add support for nested security groups

- zookeeper-lock/src/main/java/com/netflix/conductor/zookeeper/config/ZookeeperModule.java
When ExecutionLockService instance invoke lockProvider.get() will get different ZookeeperLock instance, so ZookeeperLock's zkLocks cache don't work and cause the zookeeper lock cannot be released.
> fix zookeeper lock can't release (#1758)

- ui/src/auth/README.md
Change to a better ACL example (allowing all GET operations beside /api) for better future compatibility in case people copy and paste that example to their configuration.
> Auth - Change to a better ACL example

- client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
Enable initializing task to domain configuration in the TaskRunnerConfigurer when the client is setup.
This can still be overridden using properties if needed.
> enable init taskToDomain in TaskRunnerConfigurer

- contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/AMQPObservableQueue.java
- contribs/src/test/java/com/netflix/conductor/contribs/queue/amqp/AMQPObservableQueueTest.java
This PR contains changes for configuring queues based on the settings provided in the URI. If no settings are provided, then default settings will be used to create the queue.
Closes #1771
> Configure listener queues based on the URI settings or config properties

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/counductor/integration/test/LambdaAndTerminalTaskSpec.groovy
- test-harness/src/test/resources/terminate_task_parent_workflow.json
- test-harness/src/test/resources/terminate_task_sub_workflow.json
@apanicker-nflx Sorry, it looks like you merged my PR #1608 right in the middle of my changes to support Kishore's last request to change an exception message. You merged it right as I had reverted WorkflowExecutor to the dev version so I could merge it. So now it doesn't contain any of my changes. This PR will add that code back. I see you made additional changes after that merge so I honored those changes in this PR.
> added back the changes necessary to handle subworkflow termination

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
Found the same issue in #1696 
Tasks in DO_WHILE task was not shown in conductor-ui. I found it's because DoWhile.execute() use a copy of workflow, and the tasks' seq in the copied workflow was not assigned.
I add the assignation of `seq` in Task.deepCopy() and the seq of tasks in DO_WHILE task appears in UI.
> 1696: correct task seq in DO_WHILE

- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresExecutionDAO.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresQueueDAO.java
The poll_data table is one example of many mysql and postgres tables that have an id column that is generated from a sequence. Most times these tables will be updated, inserts will only happen the first time the resource is inserted, after that many updates will be done. The current sql does an INSERT/ON CONFLICT for postgres and an INSERT/ON DUPLICATE KEY for mysql. This means that even though the error condition happens, the sequence is incremented but that new value is not used because the update happens (not the insert). In a system with large volumes, this causes large gaps in the id column as well as potentially maxing out the sequence (it happened to us).
The fix is to take out the INSERT/ON CONFLICT and replace it by an UPDATE. Only if the update fails does it do an insert.
Note …
> fix potential problem of database sequences maxing out

- core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/LambdaTaskMapper.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/LambdaTaskMapperTest.java
Add support for creating task definitions for LAMBDA tasks.
- Use `inputTemplate` for a shared `scriptExpression`
- This way different inputs for the script can be provided per task; utilising the inputs merge process
- I copied the way `HTTPTaskMapper` uses `parametersUtils.getTaskInputV2` providing a reference to a found `taskDefinition` from the `MetadataDAO`
- I also copied the structure of the unit tests of the HTTP mapper (one with task definition and one without)
> LAMBDA - add support for task definition's inputTemplate

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/TaskType.java
- core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/JsonJQTransformTaskMapper.java
- core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/JsonJQTransformTaskMapperTest.java
- core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
- docs/docs/configuration/systask.md
- test-harness/src/test/groovy/com/netflix/counductor/integration/test/JsonJQTransformTaskSpec.groovy
- test-harness/src/test/resources/simple_json_jq_transform_integration_test.json
Complete JSON_JQ_TRANSFORM development
Since this change JSON_JQ_TRANSFORM will no longer require a task definition (optional)
> JSON_JQ_TRANSFORM - complete system task development

- server/build.gradle
Fix for windows gradle long classpath issue. Fixes JavaExec tasks that error out with message "CreateProcess error=206, The filename or extension is too long"
Related:
#817
> Add support for long classpaths on Windows

- RELATED.md
I wrote a Serilog (arguably the most popular logging library for C#) sink to send log events to Netflix Conductor and thought I'd add a link to it here so other people can see and use it.
https://github.com/TwoUnderscorez/serilog-sinks-conductor-task-log
> Add a worker tool to RELATED.md

- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresMetadataDAO.java
- postgres-persistence/src/test/java/com/netflix/conductor/dao/postgres/PostgresMetadataDAOTest.java
Problems discovered in our testing of v28.0:
- adding workflow for a given name but not in increasing version order does not work - workflow out of order will not get added to the database but will incorrectly cause the latest_version column in the db to be set to its version.
- removing workflow does not update latest_version column
The first problem can cause a workflow not found when trying to retrieve the latest version of the workflow via the API - i.e. version number is not supplied.
> Postgres Workflow Metadata Update/Remove

- core/src/main/java/com/netflix/conductor/core/events/queue/dyno/DynoObservableQueue.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestEvent.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskWorkerCoordinator.java
**DynoQueue context:**
When a message is pushed to queue, it is first added to the queue, and message payload is maintained in a separate hash. When the message is popped from the queue, it is removed from the queue and the message payload still remains in the hash. Once the client acknowledges using (ACK), the message payload is removed from the hash and the message-id is removed from the UNACK set.
**Problem:**
When the ack is not performed by the client polling the message, it leads to a pile-up of messages payloads in the hash. This pile of messages consumes a lot of memory of Redis/Dynomite. ACK is not performed for the polled messages in the following places,
1. When system tasks are polled from the SystemTaskExecutor, the task messages are not acknowledged.
2. In the …
> Acknowledge message received after polling from the RedisDynoQueue to remove the message payload

- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAO.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAOTest.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresMetadataDAO.java
Duplication of the fix for MySql based on problems discovered in our testing of v28.0 with Postgres:
- adding workflow for a given name but not in increasing version order does not work - workflow out of order will not get added to the database but will incorrectly cause the latest_version column in the db to be set to its version.
- removing workflow does not update latest_version column
The first problem can cause a workflow not found when trying to retrieve the latest version of the workflow via the API - i.e. version number is not supplied.
Reference original PR #1826 for Postgres fix for the same.
> Fix/mysql workflow dao update / remove

- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
- es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchRestClientProvider.java
- es6-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java
- es6-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchRestClientProvider.java
By default, the connection request timeout is interpreted from the system default. Under high throughput scenarios, elasticsearch client timeout when getting the connection from the HTTP rest-client library.
> Add ability to configure the connection request timeout for Elasticsearch rest client

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Failure to remove from queue during terminate wouldn't cause any side effects, and can be cleaned up in subsequent operations. However, queue exceptions are catched as blockers in terminateWorkflow logic, ignoring subsequent operations in terminate logic like canceling the tasks, starting the failure workflow etc.
This PR will catch and log the queue remove exceptions, and continue with terminate workflow logic.
> Ignore queue exceptions in terminate workflow logic.

- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowRepairService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowSweeper.java
- core/src/main/java/com/netflix/conductor/dao/QueueDAO.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/main/java/com/netflix/conductor/service/AdminService.java
- core/src/main/java/com/netflix/conductor/service/AdminServiceImpl.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowRepairService.java
- jersey/src/main/java/com/netflix/conductor/server/resources/AdminResource.java
- redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/queue/DynoQueueDAO.java
- redis-persistence/src/main/java/com/netflix/conductor/dyno/DynomiteConfiguration.java
- test-harness/build.gradle
- test-harness/src/test/groovy/com/netflix/conductor/test/util/MockQueueDAOModule.java
- test-harness/src/test/groovy/com/netflix/conductor/test/util/WorkflowTestUtil.groovy
- test-harness/src/test/groovy/com/netflix/counductor/integration/test/TaskResiliencySpec.groovy
- test-harness/src/test/groovy/com/netflix/counductor/integration/test/WorkflowAndTaskConfigurationSpec.groovy
- test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
- test-harness/src/test/java/com/netflix/conductor/tests/utils/TestModule.java
- ui/package-lock.json
In the current implementation:
- Failure to schedule a task will terminate the workflow.
-- A Task scheduling can fail when failing to persist the task, or pushing the taskId to Task Queues.
- A task could remain stuck if the persistence layer and queuing layer doesn’t agree:
-- For eg: if the relevant message is lost in the Task queue.
The process for scheduling a task would remain the same as now:
1. Task status is set as SCHEDULED, and persisted.
2. Task is pushed to the Task queue.
In this PR, if Step 1 fails, we'll continue to terminate workflows (which is the existing behavior). If Step 2 fails, The next run of sweeper fixes the inconsistency by verifying the state of the message in the Queue. I.e if the Task is in SCHEDULED state, but a relevant message is not found in the Queue …
> Feature: Task resiliency from QueueDAO failures

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/counductor/integration/test/SubWorkflowSpec.groovy
- test-harness/src/test/resources/workflow_with_sub_workflow_1_integration_test.json
Retrying subworkflow when parent workflow has timed out does not reset the execution time of the parent workflow which will lead it to be timed out immediately during the retry.
This PR aims to resolve this by setting the field `lastRetriedTime` on the parent workflow when it is being evaluated upon the subworkflow retry.
> retry subworkflow will resume timed out parent workflow

- client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
the atomic count var is misused, Apache BasicThreadFactory will format the thread count to the thread name if the namingPattern is a regexp，maybe it's better to rename to workerNamePattern.
> fix workerNamePrefix problem

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
In workflows that have a lot of sub_workflow tasks, the rerun API is very slow because of the way it tries to find the task associated with rerunFromTaskId. If the task is directly under the workflow but there are sub_workflow tasks in the tasks list before the specified task, it will walk the chain of subworkflows looking for the task. This PR makes it first look at the tasks directly under the workflow before walking the sub_workflow chains.
> when rerunning workflow, to find the rerunFromTaskId task, check tasks directly under the workflow before checking sub_workflow tasks

- core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java
- core/src/main/java/com/netflix/conductor/dao/PollDataDAO.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresExecutionDAO.java
The /tasks/queue/polldata/all endpoint has a very convoluted way of getting PollData for all task types at once. In our system with tons of polling, it causes that endpoint to be very slow. This PR greatly simplifies how we do the queries for MySQL and Postgres. Cassandra still does it the old way because I have no way of testing it with that database.
> simplify how we get PollData for all task types at once

- core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
- core/src/main/java/com/netflix/conductor/core/config/EventModule.java
- core/src/main/java/com/netflix/conductor/core/events/SimpleEventProcessor.java
- server/src/main/java/com/netflix/conductor/server/ServerModule.java
- test-harness/src/test/java/com/netflix/conductor/tests/utils/MySQLTestModule.java
- test-harness/src/test/java/com/netflix/conductor/tests/utils/TestModule.java
1. Bindings for Event related classes, like _EventProvider_, _EventQueueProvider_ and _ActionProcessor_ are moved to a different module.
2. Methods in SimpleEventProcessor are _protected_ to allow for extension by inheritance.
> Changes that allow event processor to be extended

- docs/docs/labs/beginner.md
In [Create workflow definition](https://netflix.github.io/conductor/labs/beginner/#creating-workflow-definition) JSON example mandatory `ownerEmail` property is missing
> Add mandatory `ownerEmail` json property in example doc

- docker/server/config/config-local.properties
- docker/server/config/config.properties
- docker/serverAndUI/config/config-local.properties
- docker/serverAndUI/config/config.properties
- redis-persistence/src/main/java/com/netflix/conductor/dyno/DynomiteConfiguration.java
- server/src/main/java/com/netflix/conductor/bootstrap/BootstrapModule.java
- server/src/main/java/com/netflix/conductor/server/ServerModule.java
- server/src/main/resources/server.properties
I think this is an issue that has always existed, but hasn't mattered until now since the `DynomiteConfiguration` is now directly overriding the default behavior of `SystemPropertiesConfiguration`. 
The new change to repair workflows is supposed to default to false, but currently it's always true because all configurations were being set to `SystemPropertiesDynomiteConfiguration`. 
I think that this change is what the intention was, and now makes the default actually be false. 
**NOTE:** This tries to make the property set to true by default in the various pre-existing config properties. But, this setting needs to be only controlled by one of these system properties to work correctly.
I think this was made recently by @kishorebanala
> Fix the binding for ServerModule to the root SystemProps Configuration

- client/go/README.md
- client/go/conductorhttpclient.go
- client/go/conductorworker.go
- client/go/httpclient/httpclient.go
- client/go/startclient/startclient.go
This pull request adds minor updates to the GoLang client to match the [Worker specification](https://netflix.github.io/conductor/apispec/#polling-ack-and-update-task).
* Added `domain` parameter to PollForTask (and worker constructor by-proxy) to match spec
* Removed `workerid` parameter from AckTask to match spec
* `net/http` client is created once in `httpclient` constructor rather than per-request
* Added check and log warning for TaskResult being `nil` after running the `executeFunction`
> Updated go client Polling and Ack to match documented spec

- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLQueueDAOTest.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresQueueDAO.java
- postgres-persistence/src/test/java/com/netflix/conductor/dao/postgres/PostgresQueueDAOTest.java
This is a solution for Issue #1859. Tasks that were popped had their popped status set to false before they were acked so a future poll could get the same task. This PR only resets the popped flag for tasks that were popped in the past by a minute, not in the future by a minute.
> In processAllUnacks, change it so only the unacks from the past get reset

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowDef.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
- test-harness/src/test/resources/do_while_as_subtask_integration_test.json
Patch for #1816 .
If the last inner task of DO_WHILE was completed and call getNextTask() in decide(), I return the DO_WHILE task (In current code, it will return the next task of DO_WHILE).
And then, in DeciderService.getNextTask(), I check if the DO_WHILE task already exists in the workflow's tasks. If it exists, just ignore it.
> 1816: getNextTask will get wrong task if DO_WHILE task is embed in FORK or DECISION

- common/src/main/java/com/netflix/conductor/common/constraints/TaskReferenceNameUniqueConstraint.java
We hit an issue where I was expecting a validation error on workflow creation, but didnt get one. We had some tasks lower down some decision trees/forks that had the same taskReferenceName...... which shouldnt be allowed, but was.
The problem was that the Validation was just doing getTasks(), but really you need to be doing collectTasks().
Verified we get the correct validation error now.
> Fix bug in unique task reference name validation

- client/python/conductor/ConductorWorker.py
Have added the mandatory **_logs_** attribute into response format
> Python client - missing mandatory logs attribute

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
Optimize completion by removing updating all tasks.
- When there are hundreds of thousands of tasks in the workflow, this update will be expensive.
- all tasks should be done before workflow is completed.
> Optimize completion by removing updating all tasks

- core/src/main/java/com/netflix/conductor/core/execution/mapper/ExclusiveJoinTaskMapper.java
ExclusiveJoinTaskMapper should set joinTask startTime instead of endTime
> Fix ExclusiveJoinTaskMapper to set task startTime

- client/go/conductorhttpclient.go
- client/go/conductorworker.go
Go workers aren't able to correctly Ack that they've accepted a request due to missing parameters.
See #1923
> Added missing params to Go client Ack

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
On every iteration, apply task domains as set in the workflow execution.
This feature was missing and made do wile behave incorrectly when using
task domains (since the domains were reset for tasks inside the loop).
Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
> Preserve task domains for tasks inside do_while loop

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Avoid creating subworkflow object every time when handling subworkflow tasks.
> Avoid creating subworkflow object every time

- mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
As I understand, the current implementation is done in this way (everything or nothing) just because there is no way to get the updated row IDs from a MySQL response. And therefore the only consistent behavior is to completely cancel the partial update as it conflicts with another worker.
But it hurts a lot if there is a huge queue of tasks and a lot of workers trying to poll - they get stuck in a deadlock trying to do `set popped = true` for a bunch of messages.
In this change the messages are marker as popped one by one for each row and the popped ones are returned.
**EDIT**
Closes #577
> MySQL queues: reduce the impact of racing by popping the queue 1 by 1

- contribs/dependencies.lock
- es6-persistence/dependencies.lock
- server/dependencies.lock
- test-harness/dependencies.lock
- versionsOfDependencies.gradle
To allow using latest 6.8.x elasticsearch servers.
ES client should be backwards compatible, so ES versions 6.8.x and below are still supported.
No changes required in the code, just a dependency bump
Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
> Bump elasticsearch client to 6.8.x

- core/src/main/java/com/netflix/conductor/core/execution/tasks/IsolatedTaskQueueProducer.java
> fix ordering of params in isolated task queue producer

- client/go/conductorhttpclient.go
Configured the Ack and PollForTask methods to only include the "domain" parameter if explicitly requested. 
See #1952
> Updated go client to only include domain param when given

- contribs/src/main/java/com/netflix/conductor/contribs/kafka/KafkaPublishTask.java
- contribs/src/test/java/com/netflix/conductor/contribs/kafka/TestKafkaPublishTask.java
- docs/docs/apispec.md
- docs/docs/configuration/systask.md
Added asyncComplete  support to kafka publish task (like in the http task).
If the asyncComplete parameter is set to true, the task remain in IN_PROGRESS state and wait for an external event to complete.
> add asyncComplete support to Kafka publish task

- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresBaseDAO.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresExecutionDAO.java
- postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresQueueDAO.java
- postgres-persistence/src/test/java/com/netflix/conductor/dao/postgres/PostgresExecutionDAOTest.java
- postgres-persistence/src/test/java/com/netflix/conductor/dao/postgres/PostgresQueueDAOTest.java
- postgres-persistence/src/test/java/com/netflix/conductor/performance/PerformanceTest.java
- postgres-persistence/src/test/java/com/netflix/conductor/performance/TestPostgresConfiguration.java
by adding proper FOR SHARE / FOR UPDATE / SKIP LOCKED locks to DB queries
where it makes sense in order to reduce conflicts/deadlocks in DB
Most important case is when workers poll for work, they are not
interested in tasks that are locked (currently being updated) so they
can leverage 'SKIP LOCKED' to prevent DB locks and tx deadlocks.
This increases the performance of postgres dao
Additional improvements:
+ move thread.sleep out of DB transaction when tasks are being polled
with timeout parameter
+ add serialization_error to the list of causes triggerring TX retry
(this is happening under heavy load)
+ fix processUnack condition: it used to do the opposite. This has been
also fixed in the meantime by u447 <rick.fishman@bcbsfl.com>
+ add a performance test. This test can be executed …
> Improve postgresql DAO performance

- client/build.gradle
- client/dependencies.lock
- client/src/main/java/com/netflix/conductor/client/http/PayloadStorage.java
- client/src/test/java/com/netflix/conductor/client/http/PayloadStorageTest.java
- versionsOfDependencies.gradle
Fix for bug #1968. Throw exception if response code isn't 2xx.
> Fix for bug #1968 - handle response code in upload PayloadStorage

- client/python/conductor/ConductorWorker.py
Detecting errors happening when a workflow is running is somewhat difficult. When the workers log the problematic exec_function's name, it is much easier to detect the issue without having to view the Conductor UI.
> Python Client: Error print statement now also prints exec_function name.

- mysql-persistence/src/main/resources/db/migration/V7__new_queue_message_pk.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V5__new_queue_message_pk.sql
This PR modifies the primary key on the queue_message table to be queue_name, message_id columns for postgres and mysql. 
Currently, on the queue_message table, there is a primary key of 'id' (SERIAL) and a unique index of 'queue_name' and 'message_id' columns. (both columns non-null) Since, AFAICT, the id column is unused, the index should replace id as the primary key. 
The motivation behind this PR is to enable support for sharding the queue_message table using Citus. (see #1997) In order to shard, the queue_message table cannot have a unique constraint or primary key that does not include the partition (shard) column. By removing the id pk/column and replacing the pk with the existing unique index, the queue_message table can be sharded in Citus. (by queue_name or message_id)
While …
> modify primary key on queue_message table

- docs/docs/apispec.md
doc: Update apispec sort format from `<direction>:<fieldname>` to `<fieldname>:<direction>`.
The implementation uses the reversed format, than what is in the docs. Implementation is here:
https://github.com/Netflix/conductor/blob/be9e74ebd8ee784abb2b5d0eeb9d4c3786fe108f/jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java#L214
Note: Swagger UI already matches the implementation, so no change needed there.
> doc: Update apispec sort format from <direction>:<fieldname> to <fieldname>:<direction>

- docs/docs/labs/beginner.md
Hey 👋 
While checking out the documentation I've noticed some broken page references in the [Labs - Beginner](https://netflix.github.io/conductor/labs/beginner/) page.
This PR points the references to the correct path. I've made a local build of the docs and tested it as seen in the following gif:
Hope this helps, let me know if anything is missing 👍
> Fix broken page references in docs

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowRepairService.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Terminate.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestTerminate.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DecisionTaskSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateTaskSpec.groovy
- test-harness/src/test/resources/decision_and_terminate_integration_test.json
- test-harness/src/test/resources/terminate_task_sub_workflow.json
The execution of the `TERMINATE` task deviated from that of other tasks such that -
1. The task execution would modify the enclosing workflow but expect the orchestrator/state machine to persist the workflow changes
2. In order to accomodate this behavior, the state machine evaluation had to be hacked for detection and early termination of the workflow, leading to incomplete workflow evalutions. (The most obvious side-effect of this being the TERMINATE task would be added to the workflow with a seq of 0).
3. The incomplete state evaluation further led to the corner case such that when a DECISION task is followed by a TERMINATE task in one of its branches, the DECISION task would not be persisted by the state machine as part of the workflow data.
This PR aims to resolve the above …
> Fix case where decision task is followed by a terminate task

- cassandra-persistence/dependencies.lock
- client/build.gradle
- client/dependencies.lock
- client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
- common/dependencies.lock
- contribs/dependencies.lock
- core/dependencies.lock
- dependencies.lock
- es5-persistence/dependencies.lock
- es6-persistence/dependencies.lock
- grpc-client/dependencies.lock
- grpc-server/dependencies.lock
- grpc/dependencies.lock
- jersey/dependencies.lock
- mysql-persistence/dependencies.lock
- postgres-persistence/dependencies.lock
- redis-lock/dependencies.lock
- redis-persistence/dependencies.lock
- server/dependencies.lock
- test-harness/dependencies.lock
- ui/dependencies.lock
- zookeeper-lock/dependencies.lock
https://github.com/FasterXML/jackson-databind/issues/2683
> added support for newer jackson version in client

- ui/src/actions/metadata.js
Pretty sure this wasn't intended. Conforming code to structure.
The `ui/src/actions/metadata.js` file seems to have a typo and wasn't following the rest of the code structure. 
Basically added a variable to define a dispatch type, and changed it from returning an undefined object `e` to return the object `error`.
> UI Dispatch Fix

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowRepairService.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Terminate.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestTerminateTask.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DecisionTaskSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateSpec.groovy
- test-harness/src/test/resources/decision_and_terminate_integration_test.json
- test-harness/src/test/resources/terminate_task_sub_workflow.json
> backported fix for termiante task from #2056

- ui/src/api/wfe.js
'useLatestDefinition' should really be 'useLatestDefinitions' for this option to work correctly
> Fix typo in bulk restart query parameter

- contribs/src/main/java/com/netflix/conductor/contribs/listener/conductorqueue/ConductorQueueStatusPublisher.java
- contribs/src/main/java/com/netflix/conductor/contribs/listener/conductorqueue/ConductorQueueStatusPublisherProperties.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/listener/WorkflowStatusListener.java
- core/src/main/java/com/netflix/conductor/core/listener/WorkflowStatusListenerStub.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/java/com/netflix/conductor/test/listener/WorkflowStatusPublisherIntegrationTest.java
Workflow completion notification will be sent immediately after a workflow moves to COMPLETED state.
Workflow termination notification will be sent immediately after a workflow moves to TERMINATED/FAILED/TIMED_OUT state.
Workflow finalization notification will be sent after all the tasks within the workflow have been moved to an expected terminal state, the parent workflow (if any) has been updated, the failure workflow (if any) has been triggered and the workflow is cleaned up from the decider queue to stop any further evaluations.
> send notification on workflow finalization

- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateTaskSpec.groovy
- test-harness/src/test/java/com/netflix/conductor/test/utils/MockExternalPayloadStorage.java
- test-harness/src/test/resources/decision_and_terminate_integration_test.json
- Fixed case where task input data is not populated from external storage when sync system task is executed
- Fixed case where terminate task output from external storage is not applied to workflow
- Fixed case where lastRetriedTime of a workflow is not reset when a workflow is restarted
> Fix conditional sync system task with large payload

- common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java
- common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java
- common/src/main/java/com/netflix/conductor/common/utils/SummaryUtil.java
- common/src/test/java/com/netflix/conductor/common/utils/SummaryUtilTest.java
- core/src/main/java/com/netflix/conductor/core/config/Configuration.java
- docker/server/config/config.properties
- server/src/main/java/com/netflix/conductor/bootstrap/BootstrapUtil.java
- server/src/main/java/com/netflix/conductor/bootstrap/Main.java
- server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
- server/src/main/resources/server.properties
This feature allows for users to configure the string serialization method used for WorkflowSummary and TaskSummary Input/Output objects when *Summary classes are created either for storing in ElasticSearch or when being pulled back from ElasticSearch. 
For my company's current use-case, all of our microservices which interact with the conductor server API we have running are written in JavaScript, so having the *Summary class Input/Output strings be JSON-serialized means we can trivially interact with the *Summary types in JS instead of trying to hand-parse Java's toString() serialization. Searching for Workflows and Tasks by fields of the input still works as expected regardless of serialization mechanism.
The default Java toString() methodology is kept in place, so the change will not …
> Workflow/Task Summary Input/Output Json Serialization

- build.gradle
- common/build.gradle
- mysql-persistence/build.gradle
- postgres-persistence/build.gradle
- test-harness/build.gradle
This replaces jcenter with maven central
Also noticed that artifacts from net.andreinc.* are in use for some mantis samples and those are in jcenter only. I went ahead and create a backup in our own repos so when jcenter goes away, we will be fine
> Replace JCenter with Maven Central

- common/src/main/java/com/netflix/conductor/common/utils/ConstraintParamUtil.java
- common/src/test/java/com/netflix/conductor/common/utils/ConstraintParamUtilTest.java
- core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java
- core/src/test/java/com/netflix/conductor/core/execution/TestParametersUtils.java
- docs/docs/configuration/workflowdef.md
Hi, my first contribution here 👋🏻. We're evaluating Netflix conductor as a workflow executor for our custom automation. In our tests, we have a service that receives a template string like conductor expressions ```${variableName}```. So, we had to escape the expression to send it to our service. I think it's a simple and useful feature to start contributing here 🤩.
To escape an expression, prefix it with an extra _$_ character. So, as an example, the expression will be  ```$${variableName}```.
> add support for escaped expressions

- mysql-persistence/dependencies.lock
- mysql-persistence/src/main/java/com/netflix/conductor/mysql/MySQLConfiguration.java
- mysql-persistence/src/main/java/com/netflix/conductor/mysql/MySQLDataSourceProvider.java
- mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLDAOTestUtil.java
- postgres-persistence/dependencies.lock
- postgres-persistence/src/main/java/com/netflix/conductor/postgres/PostgresConfiguration.java
- postgres-persistence/src/main/java/com/netflix/conductor/postgres/PostgresDataSourceProvider.java
- postgres-persistence/src/test/java/com/netflix/conductor/dao/postgres/PostgresDAOTestUtil.java
- postgres-persistence/src/test/java/com/netflix/conductor/performance/PerformanceTest.java
- server/dependencies.lock
- test-harness/dependencies.lock
- versionsOfDependencies.gradle
Hi,
Our conductor setup consists of multiple instances. If we start the instances simultaneously, sometimes we got the following error:
```
2021-02-01 12:42:08,339 [main] ERROR error migration DB
org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
Script failed
-------------
SQL State  : 23505
Error Code : 0
Message    : ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
Detail: Key (typname, typnamespace)=(schema_version, 2200) already exists.
Line       : 17
Statement  : CREATE TABLE "public"."schema_version" (
"installed_rank" INT NOT NULL,
"version" VARCHAR(50),
"description" VARCHAR(200) NOT NULL,
"type" VARCHAR(20) NOT NULL,
"script" VARCHAR(1000) NOT NULL,
"checksum" INTEGER,
"installed_by" VARCHAR(100) NOT NULL,
"installed_on" TIMESTAMP …
```
> update flyway version

- server/src/main/java/com/netflix/conductor/jetty/server/JettyServer.java
- server/src/main/java/com/netflix/conductor/jetty/server/JettyServerConfiguration.java
- server/src/main/java/com/netflix/conductor/jetty/server/JettyServerProvider.java
- server/src/test/java/com/netflix/conductor/jetty/server/JettyServerTest.java
----
----
Externalize JettyServer thread pool configuration so that minThreads and maxThreads properties can be configured through configuration file
Issue #2162
> Enable modification of JettyServer thread pool configuration (for ver 2.x)

- redis-persistence/src/main/java/com/netflix/conductor/dyno/DynomiteConfiguration.java
- redis-persistence/src/main/java/com/netflix/conductor/jedis/DynomiteJedisProvider.java
Hi All
I have made the retries to acquire the connection and max time to wait when connection exhausted as configurable. I have followed the same approach as max connections per host. The default values are the same as the hardcoded in the dyno client library.
@kishorebanala   Can you please review this?
Thanks
Guru
> Bug/#2124 Make retry and max time to wait when connection exhausts  configurable

- core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowPoller.java
----
----
_A new property called `conductor.app.workflow-lease-duration` added with a default of 5 minutes. This property is used when `WorkflowPoller` pops workflow ids from the decider queue. A shorter lease duration ensures that workflow ids are expired and available for re-processing at a reasonable time._
> Customizable lease duration when popping workflow ids from decider queue

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
Here, onWorkflowFinalizedIfEnabled is better to be called before the workflow id is removed from the decider queue. So if it fails, it will be retried later.
----
----
onWorkflowFinalizedIfEnabled will be called before the workflow id is removed from the decider queue to give an at-least-once guarantee.
> Improve onWorkflowFinalizedIfEnabled

- .gitignore
- contribs/src/test/java/com/netflix/conductor/contribs/metrics/LoggingMetricsConfigurationTest.java
- contribs/src/test/java/com/netflix/conductor/contribs/metrics/PrometheusMetricsConfigurationTest.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/WorkflowSystemTaskStub.java
----
----
This change ensures that system tasks that are configured to be async complete are not response timed out. Such tasks are not expected to be monitored for completion by Conductor and hence, do not need to evaluated for response timeouts.
Re-enable ignored tests since the error may have been addressed.
> Ensure async complete system tasks are not response timed out

- .codecov.yml
- .travis.yml
While we were not affected by the https://about.codecov.io/security-update/
We suggest to move away from this pattern of curling codecov.io to get the bash script
This is to prevent potential problems in the future
> remove codecov

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskType.java
- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
----
----
_Code consolidation: The check to find if a task is a system task existed in two places. SystemTaskRegistry and TaskType. TaskType only considered hardcoded tasks  as system tasks whereas SystemTaskRegistry considered any instance of WorkflowSystemTask. Replacing the TaskType#isSystemTask with SystemTaskRegistry#isSystemTask fixes the possibility that some code is only executed hardcoded system tasks and not all. In places where TaskType#isSystemTask is used as a litmus test in task type String to Enum conversion, a new method TaskType#of is used._
> Removed TaskType#isSystemTask in favor SystemTaskRegistry#isSystemTask

- .dockerignore
- docker/docker-compose.yaml
- docker/server/Dockerfile
- docker/server/bin/startup.sh
- docker/server/config/config-mysql-grpc.properties
- docker/server/config/config-mysql.properties
- docker/server/config/config.properties
- server/src/main/java/com/netflix/conductor/Conductor.java
----
----
Issue # 1. Docker Builds are failing due to
1. Incorrect JDK & JRE versions - jdk8 & jre8. Whereas jdk11 and jre11 have to be used for conductor 3.x
2. Incorrect startup jar name in startup script is causing "No such file or directory" issue. The conductor-server-*-boot.jar has to be used for conductor 3.x instead of conductor-server-*-all.jar
Issue # 2. Docker Compose configuration missing out indexing property.
1. Docker Compose though specifies an elasticsearch container, misses out configuring the indexing property in config*.properties excluding config-local.properties.
All the above mentioned are fixed and tested.
Feature # Added Healtcheck to Dockerfile for conductor
----
No alternative possible as these are …
> Docker & Docker Compose fixes - 3.X

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
----
----
_Workflow id will be removed from the decider queue when a workflow is paused. Consequently, the workflow id will be added to the decider queue when a workflow is resumed. This prevents PAUSED workflows from being marked as TIMED_OUT. Additionally, the `lastRetriedTime` for a resumed workflow is reset so that the workflow is not TIMED_OUT when processing is resumed._
> Remove workflows from decider queue when paused; add when resumed

- grpc/build.gradle
----
----
_Remove the unused grpc health library that is hosted in bintray which got decommissioned_
> Remove the unused grpc health library

- redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisClusterConfiguration.java
----
----
Issue #2132 
Redis cluster configuration now gets all IP addresses for a cluster, rather than just the first IP address.
----
> Get all IP addresses for redis cluster

- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
----
----
_Updating fields in the workflow and the workflow consecutively that are performed as part of the updateTask operation are removed. Since these updates are performed out of band without acquiring the lock, these can lead to possible race conditions._
_Also, removed unused method - `skipTasksAffectedByTerminateTask`_
> Remove workflow operation from task update

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/WorkflowAndTaskConfigurationSpec.groovy
----
----
_Allow workflows that TIMED_OUT because of the timeoutSeconds configuration at the workflow level to be retried. In such workflows, there may not be any unsuccessful tasks, but the workflows should be able to be retried by the user._
_The workflow will be set to RUNNING state by the action and will be acted upon later by the sweeper._
> Allow retrying timed_out workflow with no unsuccessful tasks

- core/src/main/java/com/netflix/conductor/service/AdminServiceImpl.java
- server/build.gradle
----
----
In conductor 2.X the /admin/config API also returned the build info (version and time), which is used by the UI.
In version 3.X the conductor was upgraded to use SpringBoot and the build info is not included in the API which causes an error in the UI.
Before the fix:
After the fix:
> Add build properties to /admin/config API which is consumed by the UI

- mysql-persistence/src/main/resources/db/migration/V1__initial_schema.sql
- mysql-persistence/src/main/resources/db/migration/V2__queue_message_timestamps.sql
- mysql-persistence/src/main/resources/db/migration/V3__queue_add_priority.sql
- mysql-persistence/src/main/resources/db/migration/V4__1009_Fix_MySQLExecutionDAO_Index.sql
- mysql-persistence/src/main/resources/db/migration/V5__correlation_id_index.sql
- mysql-persistence/src/main/resources/db/migration/V6__new_qm_index_with_priority.sql
- mysql-persistence/src/main/resources/db/migration/V7__new_queue_message_pk.sql
- mysql-persistence/src/main/resources/db/migration/V8__update_pk.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V1__initial_schema.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V2__1009_Fix_PostgresExecutionDAO_Index.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V3__correlation_id_index.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V4__new_qm_index_with_priority.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V5__new_queue_message_pk.sql
- postgres-persistence/src/main/resources/db/migration_postgres/V6__update_pk.sql
----
- [ x] Bugfix
----
_In the 3.0 release, Flyway migration SQL files included the copyright notice which altered the checksum, resulting in issues for users migrating from 2.x to 3.0. This PR copies the SQL files from the 2.31 branch as-is, so the checksum remains the same._
Issue #2263
> #2263 SQL files are the same as 2.31

- client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
- rest/src/main/java/com/netflix/conductor/rest/controllers/WorkflowBulkResource.java
- ui/src/api/wfe.js
- ui/src/sagas/bulk.js
----
- [ x] Bugfix
----
_Bulk terminate API uses POST since Tomcat does not support DELETE requests with body._
> Bulk Terminate API uses POST instead of DELETE

- postgres-persistence/src/main/resources/db/migration_postgres/V7__new_qm_index_desc_priority.sql
change combo_queue_message index to use descending priority for huge performance increase on databases with millions of workflow and task rows
----
----When polling, the postgres implementation does a query that orders by descending priority. For databases with lots of workflows, an index created using ascending priority causes these queries to be extremely slow. Changing the index to use descending priority dramatically increases performance on those polling queries, especially with databases with millions of workflows/tasks.
----
> change combo_queue_message index to use descending priority for huge performance increase

- postgres-persistence/src/main/resources/db/migration_postgres/V7__new_qm_index_desc_priority.sql
add descending priority index to combo_queue_message index to make queue queries faster - 3.x
----
----
Issue #
----
> add descending priority index to combo_queue_message index to make queue queries faster - 3.x

- .github/workflows/ci.yml
- contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
- contribs/src/test/java/com/netflix/conductor/contribs/tasks/json/JsonJqTransformTest.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/main/java/com/netflix/conductor/metrics/WorkflowMonitor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
----
----
Disabled the `HttpTaskTest` temporarily. This test causes OOM errors; these are disabled so that releases are unblocked and a fix can be worked on in the interim.
Cleaned up `WorkflowMonitor` to use `MetadataService` instead of the `MetadataDAO`.
> disabled httptasktest; cleaned up WorkflowMonitor

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
- core/build.gradle
- core/src/main/java/com/netflix/conductor/core/execution/AsyncSystemTaskExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorker.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- core/src/test/groovy/com/netflix/conductor/core/execution/AsyncSystemTaskExecutorTest.groovy
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSubWorkflow.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskWorker.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskWorkerCoordinator.java
- test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractSpecification.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRestartSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRetrySpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateTaskSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/NestedForkJoinSubWorkflowSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRestartSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRetrySpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SystemTaskSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/TaskLimitsWorkflowSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
----
----
_On backend errors, clients are programmed to retry, but Conductor internally does not retry. For SubWorkflow, BACKEND_ERROR exceptions leave the task in SCHEDULED state, allowing it to retried by SystemTaskCoordinator at a later time._
> SubWorkflow task will be auto-retried on BACKEND_ERROR

- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
----
Rename meter-name of daoEventRequests in Monitors class
_Related Issue_
Issue #2375
----
No
> Rename dao event requests meter name to prevent duplicates

- contribs/dependencies.lock
- contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/AMQPObservableQueue.java
- contribs/src/test/java/com/netflix/conductor/contribs/queue/amqp/AMQPObservableQueueTest.java
- dependencies.gradle
- server/build.gradle
- server/dependencies.lock
- test-harness/build.gradle
- test-harness/dependencies.lock
----
After this PR amqp connection and channel will be created once instead of closing and opening channels each time there is a failure.
Upgrade amqp-client version to 5.13.0
Amqp connection/channel objects will be created once and amqp client will be responsible of restoring channels in case of a failure. 
After this PR Conductor will be able to acknowledge messages with delivery tags from previous channels and process those messages successfully
_Issue_ 
https://github.com/Netflix/conductor/issues/2382
----
No
> Fix amqp channel and connection creation in order to prevent "unknown delivery tag"

- docker/serverAndUI/bin/startup.sh
The server jar file name was wrong and has been corrected.
----
----
In the [Dockerfile](https://github.com/Netflix/conductor/blob/main/docker/serverAndUI/Dockerfile), the jar file is retrieved as follows.
```
&& mv ./server/build/libs/conductor-server-*-boot.jar /app/libs/ \
```
However, in the [shell script](https://github.com/Netflix/conductor/blob/main/docker/serverAndUI/bin/startup.sh), the server was started as follows.
```
nohup java -jar -DCONDUCTOR_CONFIG_FILE=$config_file conductor-server-*-all.jar 1>&2 > /app/logs/server.log
```
Therefore, I changed part of the file name from `all` to `boot`.
> fix serverAndUI docker setup script.

- docs/docs/gettingstarted/basicconcepts.md
- docs/docs/gettingstarted/client.md
- docs/mkdocs.yml
Changed the branch name from `dev` to `main` for links to files in the documentation.
----
----
Fixed a broken link to each GitHub file in the documentation due to a branch name change.
Changed the branch name from `dev` to `main`, and fixed the python client path.
----
The following command was executed to fix the problem. (macOS)
```shell
% find ./docs -type f | xargs grep '/dev/'
./docs/mkdocs.yml:edit_uri: edit/dev/docs/docs/
./docs/docs/gettingstarted/basicconcepts.md:	Conductor provides an API to create user defined tasks that are executed in the same JVM as the engine.	See [WorkflowSystemTask](https://github.com/Netflix/conductor/blob/dev/core/src/main/java/com/netflix/conductor/core/execution/tasks/WorkflowSystemTask.java …
```
> Corrected the branch name in the document

- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/utils/ParametersUtils.java
- core/src/test/java/com/netflix/conductor/core/utils/ParametersUtilsTest.java
- docs/docs/configuration/workflowdef.md
- grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
- grpc/src/main/proto/model/workflowdef.proto
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/WorkflowAndTaskConfigurationSpec.groovy
- test-harness/src/test/resources/simple_workflow_1_input_template_integration_test.json
----
----
This adds an `inputTemplate` configuration option to workflow definitions that functions similar to the [`inputTemplate` on task definitions ](https://netflix.github.io/conductor/configuration/taskdef/#using-inputtemplate). 
My current workaround is to define a `jq` task to do things like provide default variables but this does so more elegantly and maps to the current task modelling. 
----
- An entirely new field
- I like the fact that `inputTemplate` is consistent across tasks and workflows, but a new field could have been used here if we wanted to separate the implementations
Questions
---
1. Are there any other places I should add tests? The workflow integration tests seem to be the most logical, but please let me …
> feat: Add inputTemplate support to workflow metadata

- client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
- client/src/test/java/com/netflix/conductor/client/http/MetadataClientTest.java
----
----
Fix delete method. 
Currently, there is a duplicate call to delete causing this method always fail (the first deletes the workflow successfully, and the second one fails)
> fix client delete method

- docker/README.md
- docs/docs/architecture.md
- docs/docs/server.md
----
----
The docker-compose command is updated with the `-f` flag to start the database container also, and adds the `--remove-orphans` flag to ensure all the containers are removed properly
Issue #2464
> Doc: Updates docker-compose commands to start Database container

- .gitignore
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRerunSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowRerunSpec.groovy
----
- [x ] Bugfix
When a previously failed subworkflow is reran, the parent workflow state should be updated accordingly.
> Re-running a sub workflow should update the parent state

- core/build.gradle
- core/dependencies.lock
- dependencies.gradle
- server/build.gradle
The conductor has JAXB dependency on javax.* which should be migrated
to jakarta.*.
Signed-off-by: Tao Jiang <taoj@vmware.com>
----
----
The conductor has JAXB dependency on javax.* which should be migrated to jakarta.* due to [some legal issues](https://eclipse-foundation.blog/2019/05/03/jakarta-ee-java-trademarks/). We, VMware, use and build the conductor as a library into our own service for internal CI/CD requirements.  This change will also avoid library clashes. 
Issue #2495
----
Deploy vanilla Conductor as standalone service. However, we have totally replaced the API layer with our own implementation in order to support using ASL (Amazon State Language) as DSL …
> Migrate conductor JAXB dependency from javax. to jakarta

- core/src/main/java/com/netflix/conductor/core/utils/ParametersUtils.java
- core/src/test/java/com/netflix/conductor/core/utils/ParametersUtilsTest.java
Errors during variable replacement can fail the decide process and leave the workflow in a RUNNING state indefinitely
----
----
ParametersUtils defaults `${}` or `${   }` to empty string.
> Empty variable is defaulted to empty string

- contribs/src/main/java/com/netflix/conductor/contribs/tasks/json/JsonJqTransform.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/JsonJQTransformSpec.groovy
----
----
When rerun from task, if it's a synchronous system task, don't put it in the queue, start directly instead.
Issue #MWI-3456: rerunWorkflow places synchronous system tasks in the queue
----
> Fix rerunWorkflow places synchronous system tasks in the queue

- contribs/src/main/java/com/netflix/conductor/contribs/dao/index/NoopIndexDAO.java
- core/src/main/java/com/netflix/conductor/dao/IndexDAO.java
- es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchDAOV6.java
- es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchRestDAOV6.java
- es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchDAOV6.java
- es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchRestDAOV6.java
- es7-persistence/src/main/java/com/netflix/conductor/es7/dao/index/ElasticSearchRestDAOV7.java
- es7-persistence/src/test/java/com/netflix/conductor/es7/dao/index/TestElasticSearchRestDAOV7.java
----
----
Add getWorkflowCounts to IndexDao which uses the ES [Count API](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-count.html) to get workflow counts.
Issue #MWI-2922
workflow_running metric is populated using the ExecutionDAO.getPendingWorkflowCount(). The current implementation delegates it to IndexDAO.searchRunningWorkflowIds, which we cap the search size at 1000. The added API would allow the use of the ES Count API instead to get the actual count.
----
> Add getWorkflowCounts to IndexDao using ES count API

- polyglot-clients/go/conductorhttpclient.go
- polyglot-clients/go/conductorworker.go
----
----
- Removed ack step for go client
- Added constructor for Httpclient to allow token based auth
Based on Issue # https://github.com/Netflix/conductor/issues/1659, v3 no longer requires workers to ack tasks. The ack step in the go client prevents the worker from executing the task, and was therefore removed.
Authentication was added due to my own setup, where workers need to auth to perform any action on the api. The existing http client only took url, and so would not allow any auth.
> Remove ack from Go client + pass auth to go http client

- core/src/main/java/com/netflix/conductor/core/execution/tasks/Inline.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/InlineTest.java
Fix the broken inline task implementation. Added unit tests to validate for both value param and javascript evaluators
----
----
Fixes the Inline task validation implementation. Without this fix, inline task won't work.
Issue #2565
----
None
> Fixes #2565 - Fix the broken inline task implementation. Added unit tests for Inline task

- docker/server/config/config-local.properties
----
----
Change to 0 the `conductor.elasticsearch.indexReplicasCount` since when using default docker images only one ES instance is used.
[Issue #2589](https://github.com/Netflix/conductor/issues/2589)
----
Another alternative to consider is using a ES cluster of 2 instances. But I consider this can be unnecessary due to the purpose of the docker alternative.
> Fixing indexReplicaCount configuration for docker

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraExecutionDAO.java
----
----
The `CassandraExecutionDAO.removeTaskFromLimit` calls `DELETE from task_def_limit ...` twice. The second call is a wasteful no-op.
----
None
> Removed the extra delete statement from removeTaskFromLimit

- annotations-processor/src/main/java/com/netflix/conductor/annotationsprocessor/protogen/Message.java
- es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchBaseDAO.java
- es7-persistence/src/main/java/com/netflix/conductor/es7/dao/index/ElasticSearchBaseDAO.java
- [x ] Refactoring (no functional changes, no api changes)
----
Replacing StringBuffer objects used locally with StringBuilder.   StringBuilder does not synchronize and so will run faster.
This PR only improves performance
> Performance improvement by replacing StringBuffer with StringBuilder

- core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapperTest.java
----
----
Fix startdelay doesn't work for subworkflow task
Issue #
https://github.com/Netflix/conductor/discussions/2518
----
> Fix startdelay for subworkflow task

- build.gradle
----
- [ X] Other (please describe):
Security. Log4j discovered vulnerability: 
- https://www.lunasec.io/docs/blog/log4j-zero-day/ 
- https://news.ycombinator.com/item?id=29504755
----
Forces to upgrade transitive dependencies versions to use patched ones.
> Force log4j dep version to avoid 0-day exploit

- build.gradle
----
----
Update the version of log4j from 2.15 to 2.16 because the 2.15 contains a new vulnerability
sources: [here](https://www.techzine.eu/news/security/69795/log4j-2-15-is-not-foolproof-apache-publishes-second-emergency-patch/) or [on apache log4j project](https://logging.apache.org/log4j/2.x/index.html)
----
> Force log4j dep version to 2.16 to avoid a second exploit

- ui/src/pages/execution/TaskLogs.jsx
----
----
Issue: '/api' is already contained in root uri, UI can't fetch task logs right now.
Solution: remove '/api' from fetch task logs uri.
----
> [Fix] UI: fix fetching task logs uri

- cassandra-persistence/dependencies.lock
- client/dependencies.lock
- common/dependencies.lock
- contribs/dependencies.lock
- core/dependencies.lock
- dependencies.lock
- es5-persistence/dependencies.lock
- es6-persistence/dependencies.lock
- es7-persistence/dependencies.lock
- grpc-client/dependencies.lock
- grpc-server/dependencies.lock
- grpc/dependencies.lock
- jersey/dependencies.lock
- mysql-persistence/dependencies.lock
- postgres-persistence/dependencies.lock
- redis-lock/dependencies.lock
- redis-persistence/dependencies.lock
- server/dependencies.lock
- test-harness/dependencies.lock
- ui/dependencies.lock
- versionsOfDependencies.gradle
- zookeeper-lock/dependencies.lock
----
----
As explained in #2642, the Redisson version current being used in 2.31 branch has an issue where the schema part of the URL returns null. This is very easy to be reproduced outside of conductor:
* Create a simple java app;
* Add redisson in the classpath;
* Copy and paste the same block of code that conductor is using to connect to redis sentinel:
```java
Config redisConfig = new Config();
redisConfig.useSentinelServers()
.setScanInterval(2000)
.setMasterName("mymaster")
.addSentinelAddress("redis://localhost:7002") // This is a redis sentinel up and running on my machine
.setPassword("<PASSWORD>") // This is the redis sentinel password
.setTimeout(10000);
RedissonClient redisson = Redisson.create(redisConfig);
```
* In this simple Java app, …
> Fix for #2642: Bump Redisson dependency as current version has issue with schema resolution

- annotations-processor/dependencies.lock
- annotations/dependencies.lock
- azureblob-storage/dependencies.lock
- build.gradle
- cassandra-persistence/dependencies.lock
- client-spring/dependencies.lock
- client/dependencies.lock
- contribs/dependencies.lock
- core/dependencies.lock
- es6-persistence/dependencies.lock
- es7-persistence/dependencies.lock
- grpc-client/dependencies.lock
- grpc-server/dependencies.lock
- grpc/dependencies.lock
- mysql-persistence/dependencies.lock
- postgres-persistence/dependencies.lock
- redis-concurrency-limit/dependencies.lock
- redis-lock/dependencies.lock
- redis-persistence/dependencies.lock
- rest/dependencies.lock
- server/dependencies.lock
- test-harness/dependencies.lock
- zookeeper-lock/dependencies.lock
----
----
Update the version of log4j from 2.16 to 2.17 because the 2.16 contains a deny of service vulnerability
sources: [here](https://www.zdnet.com/article/apache-releases-new-2-17-0-patch-for-log4j-to-solve-denial-of-service-vulnerability/) and [on apache log4j project](https://logging.apache.org/log4j/2.x/index.html)
Edit:
dependency locks are updated
----
> update log4j to 2.17 to avoid DoS vulnerability

- client-spring/src/main/java/com/netflix/conductor/client/spring/ClientProperties.java
- client-spring/src/main/java/com/netflix/conductor/client/spring/ConductorClientAutoConfiguration.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskRunnerConfigurerTest.java
- docs/docs/gettingstarted/client.md
----
----
Add a new parameter 'shutdownGracePeriodSeconds' to TaskRunnerConfigurer which is the timeout of terminating worker thread pool. Default value is 10 seconds, and can't be changed.
A task may cost longer, so it is better to make users can specify the timeout.
Default value is still 10 seconds with this new feature.
Concern: 
I have removed shutdown() method from TaskPollExecutor, it is a default method, and not used by anywhere in this project, I can't see any reason to keep it, please correct me if there is potential problems, thanks.
----
> [Feature] Support to specify shutdown grace period time for worker

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraBaseDAO.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorker.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
----
- [ X] Bugfix
----
Update Monitors API to include new methods for use by the System task.  
Rework API to reduce possibility of empty values in tags.
Issue #2437, #2534 
----
Monitors toMap method will drop tags with empty values.  This could in the end cause an issue with a downstream metrics API.  Might need to consider defaulting tags with empty values to something like "unknown".
> Rework Metrics API to reduce possibility of empty values in tags

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java
- common/src/main/java/com/netflix/conductor/common/metadata/workflow/SkipTaskRequest.java
----
----
`Any` type is cpu intensive to introspect and could kill Swagger UI in some cases.
Issue #2694
----
None
> Hide com.google.protobuf.Any from Swagger introspection

- client-spring/src/main/java/com/netflix/conductor/client/spring/ClientProperties.java
- client-spring/src/main/java/com/netflix/conductor/client/spring/ConductorClientAutoConfiguration.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskRunnerConfigurerTest.java
----
----
Client can either specify different thread counts for different workers (task definitions) or continue to use the existing global shared thread counts.
Issue #
----
> Support task level thread counts

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- docs/docs/configuration/taskdef.md
- grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
- grpc/src/main/proto/model/taskdef.proto
* Support for retry with linear backoff.
* Scale factor added to control the slope of the linear backoff.
----
- [ X] Feature
----
Support for Retry with LINEAR_BACKOFF
Issue #
----
No alternatives available. This support is added just to have a certain retry behavior.
> Support for Retry with LINEAR_BACKOFF

- client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
- contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/config/AMQPEventQueueConfiguration.java
- contribs/src/main/java/com/netflix/conductor/contribs/queue/sqs/config/SQSEventQueueConfiguration.java
- contribs/src/test/java/com/netflix/conductor/contribs/queue/sqs/DefaultEventQueueProcessorTest.java
- core/src/main/java/com/netflix/conductor/core/dal/ModelMapper.java
- core/src/main/java/com/netflix/conductor/core/events/DefaultEventQueueManager.java
- core/src/main/java/com/netflix/conductor/core/events/queue/DefaultEventQueueProcessor.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SetVariable.java
- core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
- core/src/main/java/com/netflix/conductor/model/TaskModel.java
- core/src/test/groovy/com/netflix/conductor/core/dal/ModelMapperSpec.groovy
- rest/src/main/java/com/netflix/conductor/rest/controllers/QueueAdminResource.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SetVariableTaskSpec.groovy
----
----
Use domain models introduced in #2702 when creating and using default queues within the server.
Also, fixed the payload size units in error messages when payload exceeds permissible limit.
> use domain models in default queues

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/FailureWorkflowSpec.groovy
- test-harness/src/test/resources/test_task_failed_parent_workflow.json
- test-harness/src/test/resources/test_task_failed_sub_workflow.json
----
----
- fix correlationId for failure workflow
- add failure taskId to input
Issue # MWI-3508
----
> Fix for failure workflow

- .github/release-drafter.yml
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Terminate.java
- docs/docs/configuration/systask.md
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/FailureWorkflowSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/LambdaAndTerminateTaskSpec.groovy
- test-harness/src/test/resources/terminate_task_failed_workflow_integration.json
----
----
Add termination reason parameter to TERMINATE task. This will enable users to set workflow's reason for incompletion from within the TERMINATE task.
> add termination reason param to terminate task

- ui/src/pages/execution/TaskLogs.jsx
----
----
Changes:
1. Now, timestamp column uses 50% width in task log which wastes lots of area. In this chage, log time column is fixed to 180px which is enough to show timestamp.
2. Time entry doesn't support word wrap, for a log message contains \n, the UI table can't display it in a new line. This change also add css styles to support it.
----
Maybe there are other ways to approach the same target, this change can also be abandoned if there are better ways. But please consider the idea of this display improvement.
> [UI] Optimize display format of task logs

- docs/docs/architecture.md
----
----
`png` file for architecture diagram exists in `img` folder, but the link is incorrect. Fix is simply deleting the leading `/`.
> Fix the path to architecture diagram

- core/src/main/java/com/netflix/conductor/core/dal/ModelMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
- core/src/test/groovy/com/netflix/conductor/core/dal/ModelMapperSpec.groovy
- mysql-persistence/src/main/java/com/netflix/conductor/mysql/dao/MySQLExecutionDAO.java
- postgres-persistence/src/main/java/com/netflix/conductor/postgres/dao/PostgresExecutionDAO.java
- redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisExecutionDAO.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/WorkflowAndTaskConfigurationSpec.groovy
- test-harness/src/test/resources/workflow_with_synchronous_system_task.json
----
----
1. `ModelMapper.getLeanCopy()` copies tasks.
2. `WorkflowExecutor.scheduleTasks` use the full `TaskModel` when calling `WorkflowSystemTask.start()`.
> ModelMapper.getLeanCopy() copies tasks

- annotations-processor/dependencies.lock
- annotations/dependencies.lock
- azureblob-storage/dependencies.lock
- cassandra-persistence/dependencies.lock
- client-spring/dependencies.lock
- client/dependencies.lock
- common/dependencies.lock
- contribs/dependencies.lock
- core/dependencies.lock
- core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- dependencies.lock
- es6-persistence/dependencies.lock
- es7-persistence/dependencies.lock
- grpc-client/dependencies.lock
- grpc-server/dependencies.lock
- grpc/dependencies.lock
- mysql-persistence/dependencies.lock
- postgres-external-storage/dependencies.lock
- postgres-persistence/dependencies.lock
- redis-concurrency-limit/dependencies.lock
- redis-lock/dependencies.lock
- redis-persistence/dependencies.lock
- rest/dependencies.lock
- server/dependencies.lock
- test-harness/dependencies.lock
- zookeeper-lock/dependencies.lock
----
----
Add previousStatus to WorkflowModel so it can be used to capture status change
Issue #
----
> Add previousStatus filed to WorkflowModel

- contribs/src/main/java/com/netflix/conductor/contribs/lock/LocalOnlyLock.java
- contribs/src/test/java/com/netflix/conductor/contribs/lock/LocalOnlyLockTest.java
Cancel thread scheduled for stopping starvation in case of actually releasing a lock.
Background, 
As and when the lock is acquired, there is one [thread](https://github.com/Netflix/conductor/blob/main/contribs/src/main/java/com/netflix/conductor/contribs/lock/LocalOnlyLock.java#L78) is scheduled to release a lock. This is to stop the starvation scenario.
Now the issue is, when the operation is complete, the scheduled thread must be stopped otherwise after the interval it will take the lock preemptively.
----
----
Canceled the thread to stop the starvation in a normal scenario.
Issue #https://github.com/Netflix/conductor/issues/2368
----
_Describe alternative …
> Local only lock fix

- common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java
----
----
Changed to use StringUtil.equals to avoid NullPointerException
Issue #
To fix this exception throw
```
java.lang.NullPointerException: 
at com.netflix.conductor.common.run.WorkflowSummary.equals(WorkflowSummary.java:315)
```
----
> Fix NullPointerException for string compare

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskType.java
- common/src/main/java/com/netflix/conductor/common/utils/EnvUtils.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/StartWorkflowTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/StartWorkflow.java
- core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java
- core/src/test/groovy/com/netflix/conductor/core/execution/tasks/StartWorkflowSpec.groovy
- core/src/test/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapperTest.java
- docs/docs/configuration/workflowdef.md
- docs/docs/gettingstarted/startworkflow.md
- docs/docs/reference-docs/start-workflow-task.md
- docs/docs/reference-docs/sub-workflow-task.md
- docs/mkdocs.yml
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/StartWorkflowSpec.groovy
- test-harness/src/test/java/com/netflix/conductor/test/utils/MockExternalPayloadStorage.java
- test-harness/src/test/resources/simple_workflow_1_integration_test.json
- test-harness/src/test/resources/start_workflow_input.json
- test-harness/src/test/resources/workflow_that_starts_another_workflow.json
----
----
A new system task called `START_WORKFLOW` that starts a workflow using a `StartWorkflowRequest`.
> START_WORKFLOW system task

- core/src/main/java/com/netflix/conductor/core/events/SimpleActionProcessor.java
- core/src/test/java/com/netflix/conductor/core/events/TestSimpleActionProcessor.java
----
----
Whenever the tasks are being retrieved for the event handler, the loop over tasks does not come since they are being appended by iteration value. This change enables performing an action on loop over task using an event handler.
Issue https://github.com/Netflix/conductor/discussions/2873
> Event handler for loop over task.

- es6-persistence/src/main/java/com/netflix/conductor/es6/config/ElasticSearchProperties.java
- es6-persistence/src/main/java/com/netflix/conductor/es6/config/ElasticSearchV6Configuration.java
----
----
Added the username and password configuration for elasticsearch 6. Code was copied from the elasticsearch 7 configuration.
Issue #2896
> Fix credentials for es6

- docker/server/config/config-local.properties
----
----
Currently the local config actually enables ES which leads to issues when starting standalone. I don't think this is intentional, but let me know and I can create a separate `standalone` properties file.
When running `docker run -p 8080:8080 -d -t conductor:server` locally I see
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.7.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.7.0-SNAPSHOT.jar!/com/netflix/conductor/service/TaskServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error …
```
> Disable ES in local docker config

- core/src/main/java/com/netflix/conductor/model/TaskModel.java
- core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
- core/src/test/groovy/com/netflix/conductor/model/TaskModelSpec.groovy
- core/src/test/groovy/com/netflix/conductor/model/WorkflowModelSpec.groovy
----
----
_Introduced methods for reading input and output data during the serialization process. The existing getters have logic to check to where the payload exists and return them. During serialization, the getter returns the large payload which is then persisted along with the execution data._
Issue #2899
----
This is a temporary patch to fix the issue introduced in 3.6.0 and 3.6.1. A more elaborate fix is to refactor all references of `getInput` or `getOutput` methods to use a new method and remove the additional logic (of checking the external storage path) from them.
> Added dedicated methods to serialize/deserialize input/output data

- .github/workflows/publish.yml
- .github/workflows/release_draft.yml
- .github/workflows/stale.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> Set permissions for GitHub actions

- core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
----
----
_In ExecutionDAOFacade.getTaskModel(), it is possible in certain scenarios for TaskModel from the datastore to be null. Added a null check so callers upstream can appropriately handle the error_
Issue #2926 
----
_None_
> Reinstated the null check for TaskModel

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraMetadataDAO.java
- cassandra-persistence/src/test/groovy/com/netflix/conductor/cassandra/dao/CassandraMetadataDAOSpec.groovy
The `INDEX_DELIMITER` could be part of the workflow name.
----
----
When the workflow name contains a `/`, the `getAllWorkflowDefs()` call fails because the tokenization logic does not account for it. Now the logic is updated to account for it.
----
_Considered adding a validation error for workflow names containing `/`. But that would be artificial and not relevant for other persistence implementations._
> Corrected the tokenization logic in CassandraMetadataDAO

- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
----
----
When polling for tasks in batches, it currently does not sends an `ack` request for the queue, implying that it should be put again at the queue after some previously set timeout.
With that change, it will send an ack request for each valid polled task.
Issue #
----
This job could be done inside the above loop which add each task into the returned list, but it may happen that a server dies inside the loop, acknowledging some tasks that could not be returned.
Other possibility is to run the task ack in parallel, although, it may create an unnecessary thread layer and more responsibility to the class/method.
> Add an ack request for each task polled from queue, when polling in batches

- http-task/src/main/java/com/netflix/conductor/tasks/http/HttpTask.java
----
----
Fix NPE when optional headers like below are not provided.
```
"headers": {
"header1": "${workflow.input.header1}"
}
```
Issue #2884 
In the new version of conductor HTTP tasks fail with NPE is a header value is not provided. As HTTP task is generic it is a good practice to support header values which are defined in workflow but not sent while making a call to execute the workflow.
Also its good to note that this feature was working in 2.x version of conductor. 
----
No alternatives considered
> Fix for NPE when header values are null

- docs/docs/reference-docs/do-while-task.md
----
----
Update doc for do_while task. As of now nesting of do_while task is not supported but we can achieve similar functionality with sub_workflow task as any of loopOver task.
Issue #
----
> Update documentation for loop task (DO_WHILE)

- docs/docs/how-tos/redis.md
- redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisClusterConfiguration.java
- redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisSentinelConfiguration.java
- redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisStandaloneConfiguration.java
- server/src/main/resources/application.properties
----
----
Added Redis password authentication support for `conductor.db.type`
- `redis_standalone` 
- `redis_cluster`
- `redis_sentinel`
Issue #2533
---
The password is set as the 4th param in the host configuration. E.g.:
```properties
conductor.redis.hosts=localhost:6379:us-east-1c:my_str0ng_pazz
```
For Cluster and Sentinel configuration the password from the first host is used. 
In Sentinel configuration sentinels and redis nodes use the same password.
----
Considered changing `RedisProperties` to add a new password property un `conductor.redis`. That would have made it more explicit but since `host.getPassword()` already exists it seems like an OK alternative if documented properly.
> Redis password authentication support

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
----
----
Allow rerun only on terminal state workflows
> only allow rerun on terminal workflows

- client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
- core/src/main/java/com/netflix/conductor/core/utils/QueueUtils.java
- core/src/main/java/com/netflix/conductor/service/ExecutionService.java
- core/src/main/java/com/netflix/conductor/service/TaskService.java
- core/src/main/java/com/netflix/conductor/service/TaskServiceImpl.java
- rest/src/main/java/com/netflix/conductor/rest/controllers/TaskResource.java
----
----
_A new api that can query task queue sizes based on task type and domain_
----
_None_
> New api to query queue size based on task type and domain

- client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
- client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java
----
----
Fixes a bug where large payload location in task result was not being propagated as part of task result by the client.
> Fix update with large payload task result

- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
- ui/src/pages/execution/TaskSummary.jsx
----
Please remember to run `./gradlew :conductor-java-sdk:spotlessApply` to fix any format violations.
----
Add callbackAfterSeconds and pollCount in the task summary tab
Issue #
When worker updates task without completing it, the task is put back in queue for future poll. However, the workerId isn't reset, which makes it confusing as it appears to look like the task is still being processed by that worker. Adding callbackAfterSeconds and pollCount in the task summary tab to make it clear that the woerkerid just shows the instance that last processed the task
----
> task summary ui

- docs/docs/gettingstarted/client.md
- docs/docs/how-tos/clojure-sdk.md
- docs/docs/how-tos/csharp-sdk.md
- docs/docs/how-tos/go-sdk.md
- docs/docs/how-tos/java-sdk.md
- docs/docs/reference-docs/do-while-task.md
- docs/mkdocs.yml
----
- [ x] Other (please describe):
----
Docs updates:
1. added pages for the different conductor SDKs (copied from the Github Readme files).
2. "Polyglot SDKs" nav category to just "SDKs".
3. gettingstarted/client was the java SDK page - moved this content to a java-sdk.md, and then added links to all the SDKs in  place of the Java and Python examples.
> sdk documentation additions

- core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
----
----
Issue #
When we reach the input or output limit for task and workflow the current code returns the limit as the value configured by the user in the properties file which is in Kilobytes. This causes confusion because the actual size calculation is in bytes, so, in the end, we end up in a situation where we are comparing two different units. Also, for the particular message of the workflow limit the word **output** was being used for both scenarios: inpiut limit and output limit. Therefore, this PR also tries to address it by making the message generic for both cases.
cc: @v1r3n 
Alternatives …
> Improve message for payload size threshold calculation

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
----
Currently, tasks can have an arbitrary retry count. Since conductor stores history of task execution, this means that all retry attempt information is stored and for a large value of retryCount, this means that a large number of task executions are being stored.
The PR limits retryCount to a maximum value of 10 to new Task definitions. Going forward, the validation will also be checked when updating any TaskDef but won't impact reading of existing Tasks.
> Cap retryCount limit to 10

- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/main/java/com/netflix/conductor/service/ExecutionLockService.java
> Added metric for ExecutionLockService and the decide process, workflow_decision

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/config/CassandraConfiguration.java
- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/config/cache/CacheableEventHandlerDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/config/cache/CacheableMetadataDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraEventHandlerDAO.java
- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraMetadataDAO.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
- core/src/main/java/com/netflix/conductor/model/TaskModel.java
- core/src/test/groovy/com/netflix/conductor/core/execution/tasks/EventSpec.groovy
- core/src/test/groovy/com/netflix/conductor/core/execution/tasks/StartWorkflowSpec.groovy
- core/src/test/java/com/netflix/conductor/core/events/TestDefaultEventProcessor.java
----
----
_Caches for CassandraMetadataDAO and CassandraEventHandlerDAO are extracted into decorators, CacheableMetadataDAO and CacheableEventHandlerDAO respectively_
Issue: Including cache within the DAO makes it impossible to opt-out of it. 
----
_None_
> Cassandra metadata cache

- core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java
- core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
----
----
Set size limit for task exec log and add metrics
Issue #
----
> Set size limit for task exec log and add metrics

- core/src/main/java/com/netflix/conductor/core/execution/evaluators/JavascriptEvaluator.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Inline.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/InlineTest.java
----
----
_The error message from the evaluation engine is sent in the TerminateWorkflowException message by the Evaluator implementation. The same is set in the reasonForIncompletion field._
----
_Throwing TerminateWorkflowException from Evaluator breaks the encapsulation. The ideal fix is to have Evaluator throw a custom exception and let the caller decide if the workflow should be terminated._
> For INLINE task, reasonForIncompletion field includes the script evaluation error message

- client/src/main/java/com/netflix/conductor/client/http/MetadataClient.java
- common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
- core/src/main/java/com/netflix/conductor/service/MetadataService.java
- core/src/main/java/com/netflix/conductor/service/MetadataServiceImpl.java
- core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
- grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/MetadataServiceImpl.java
- grpc/src/main/proto/grpc/metadata_service.proto
- rest/src/main/java/com/netflix/conductor/rest/controllers/MetadataResource.java
- rest/src/test/java/com/netflix/conductor/rest/controllers/MetadataResourceTest.java
----
----
_This API allows static analysis tools and the UI to validate a workflow definition without attempting to persisting it._
> API (/workflow/validate) to validate a workflow definition

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
----
----
_When a task is updated, the workflow is loaded along with all of its tasks. For workflows with large number of tasks, this could substantially increase the updateTask latency_
> When a task is updated only the workflow is loaded, not all of its tasks

- grpc/build.gradle
----
----
Corrected maven repository URL -- the old one 502s
Issue #3121
> Adjust maven repostiory URL for grpc.

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DecisionTaskSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SwitchTaskSpec.groovy
- test-harness/src/test/resources/terminate_task_parent_workflow.json
> do not synchronously eval workflow during update task for select criteria

- core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
----
- [] Refactoring (no functional changes, no api changes)
----
Issue #
----
> add `removeWorkflowWithExpiry` back to ExecutionDAOFacade

- docker/server/Dockerfile
----
----
OpenJDK Docker base images are now deprecated and as such these are replaced in this PR by [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin/) Docker base images that are now considered as the official OpenJDK images.
This PR uses jdk11/jre11 with Ubuntu Focal (20.04.4LTS) tags, as this version of Linux comes geared out of the box with the necessary dependencies to build Conductor (most issues with Alpine tags are the lack of dependencies to build `protoc` complied artifacts)
Issue #3090 
----
> eclipse temurin replacing openjdk base images

- docs/docs/architecture/tasklifecycle.md
Corrected the mis-spelled word 'fom' to 'from'
----
----
Issue #
Corrected the mis-spelled word 'fom' to 'from'
----
> Updated tasklifecycle.md - mis-spelled word

- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
- core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java
----
----
Fixes the case when the subworkflow task could become inconsistent with the subworkflow execution.
> Repair inconsistent subworkflow task

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Event.java
- core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
- core/src/test/groovy/com/netflix/conductor/core/execution/tasks/EventSpec.groovy
- core/src/test/java/com/netflix/conductor/core/execution/tasks/EventQueueResolutionTest.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/EventTaskSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/util/WorkflowTestUtil.groovy
----
----
Fixes a race condition where a COMPLETED asyncComplete event task could move back to IN_PROGRESS if task update is received before task creation occurs.
> Split event system task implementation between start and execute

- common/src/main/java/com/netflix/conductor/common/run/Workflow.java
- common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- es6-persistence/src/main/resources/mappings_docType_workflow.json
- es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchDAOV6.java
- es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchRestDAOV6.java
- grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
- grpc/src/main/proto/model/workflow.proto
- grpc/src/main/proto/model/workflowsummary.proto
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
----
----
Add field `failedTaskNames` to `Workflow` and `WorkflowSummary`, to be indexed in ES enabling workflows to be queried for by the TaskDef names of the failed tasks.
----
Modifying
> Failed task names

- json-jq-task/src/main/java/com/netflix/conductor/tasks/json/JsonJqTransform.java
- json-jq-task/src/test/java/com/netflix/conductor/tasks/json/JsonJqTransformTest.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/JsonJQTransformSpec.groovy
- test-harness/src/test/resources/sequential_json_jq_transform_integration_test.json
----
----
Issue #
Nested json object in taskModel output is not resolved properly [here](https://github.com/Netflix/conductor/blob/33062f3ae506e49947bd11157dce279254f00347/core/src/main/java/com/netflix/conductor/core/utils/ParametersUtils.java#L244), so extract the map body out and put that into taskModel output instead.
----
> Extract map body from json_jq output

- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SwitchTaskSpec.groovy
- test-harness/src/test/resources/switch_with_no_default_case_integration_test.json
----
----
Revert changes done to SwitchTaskMapper introduced by [this PR](https://github.com/Netflix/conductor/commit/2d514690eb7a52ec6140677a1bf083f6f940443d#diff-c3a45903d808c1c4aa854c8fd387310c24e9d8fcee276392093ca40168e18f88), and add test case to verify the fix.
Issue #
https://github.com/Netflix/conductor/issues/3089#issuecomment-1224034537
----
> Fix next task not scheduled after switch completes

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
----
----
_A recent refactoring caused **decide during startWorkflow** to be performed outside a lock. This caused decide to be performed concurrently on two threads. This typically results in the first task of the workflow to be scheduled twice._
----
_None_
> During start, decide is performed inside a lock

- json-jq-task/src/main/java/com/netflix/conductor/tasks/json/JsonJqTransform.java
- json-jq-task/src/test/java/com/netflix/conductor/tasks/json/JsonJqTransformTest.java
----
----
Handle null result from json jq script evaluation.
> Handle null results in json jq task script evaluation

- core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
- core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java
----
----
As part of the repair process, also update subworkflow task output with subworkflow output.
> Fix subworkflow output during repair

- core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
----
----
Workflow has a field called updateTime, whereas WorkflowModel has a field called update**d**Time, which is why it isn't copied over when converting, this PR fixes that.
> Fix missing updateTime because of different field names in WorkflowModel and Workflow

- core/src/main/java/com/netflix/conductor/core/events/SimpleActionProcessor.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Event.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Inline.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Lambda.java
- core/src/main/java/com/netflix/conductor/model/TaskModel.java
- core/src/main/java/com/netflix/conductor/model/WorkflowModel.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/EventQueueResolutionTest.java
- core/src/test/java/com/netflix/conductor/dao/ExecutionDAOTest.java
- http-task/src/main/java/com/netflix/conductor/tasks/http/HttpTask.java
----
----
_Instead of TaskModel.getOutputData().put(), the code now uses TaskModel.addOutput(). Using "get" methods to mutate a field in the class is unconventional. It makes it hard to track the mutations of that field._
Issue #
----
_None_
> Removed usages of TaskModel#getOutputData().put()

- core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
- core/src/test/groovy/com/netflix/conductor/core/execution/tasks/DoWhileSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
- test-harness/src/test/resources/do_while_set_variable_fix.json
----
----
Do-While condition evaluation flow does not rely on parameterutils so compute the task input. Doing so will result in an inconsistent state when `set_variable` task is used as one of `loopOver` task and its output is used in `loopCondition`.
In fact, in all the tasks we need parameterUtils to be injected/used because any task can use input that relies on workflow variables.
> Adding parameterUtils in do-while task to compute input at each iteration.

- docs/docs/gettingstarted/docker.md
Fixed small yet important typo in documentation.
----
----
Issue #
----
> Fixed small yet important typo in documentation.

- core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java
- core/src/main/java/com/netflix/conductor/core/execution/AsyncSystemTaskExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorker.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSystemTaskWorker.java
----
----
_AsyncSystemTaskExecutor used TaskDefName when recording queue wait times. For system tasks, the task def name is meaningless and has high cardinality. To measure and alert on queue delays task type is ideal_
----
_None_
> AsyncSystemTaskExecutor uses the correct value for taskType tag

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraExecutionDAO.java
----
- [ X] Refactoring (no functional changes, no api changes)
----
We have our own CassandraExecutionDAO that we use that overrides some of the behavior in the regular CassandraExecutionDAO. We want to be able to extend the CassandraExecutionDAO, and still make use of fields and methods from the DAO.
> Make fields and methods protected for CassandraExecutionDAO for extensibility 

- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
----
----
Fix the issue that uncaught exception thrown when the task input of FORK_JOIN_DYNAMIC is invalid, and task seem to be stuck. Also startWorkflow will fail with 500 in this case if FORK_JOIN_DYNAMIC task is synchronous evaluated when workflow starts.
Issue #
----
> Fail workflow if input to dynamic fork join task is invalid

- core/src/main/java/com/netflix/conductor/core/config/ConductorCoreConfiguration.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/DoWhileTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/DynamicTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/EventTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/ExclusiveJoinTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/HTTPTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/HumanTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/InlineTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/JoinTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/JsonJQTransformTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/KafkaPublishTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/LambdaTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SetVariableTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SimpleTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/StartWorkflowTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/TaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/TerminateTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/UserDefinedTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/WaitTaskMapper.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
- core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
----
Using String task to enable custom tasks and taskMapper to be implemented in future.
> Change TaskType to be string in order to define custom task and taskMappers

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraMetadataDAO.java
- cassandra-persistence/src/test/groovy/com/netflix/conductor/cassandra/dao/CassandraMetadataDAOSpec.groovy
- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowSweeper.java
- core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowSweeper.java
- core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
- redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisMetadataDAO.java
- redis-persistence/src/test/java/com/netflix/conductor/redis/dao/RedisMetadataDAOTest.java
----
Set unack/postpone duration based on task state. 
For workflows with a task in IN_PROGRESS state, the postpone duration is set as (responseTimeoutSeconds + 1). Multiple tasks in IN_PROGRESS state, use the first task. If responseTimeoutSeconds is 0, use a default non-zero value as postpone duration.
For workflows with a task in SCHEDULED state, the postpone duration is set as (pollTimeoutSeconds + 1). If pollTimeoutSeconds is not set, the workflowDef.timeoutSeconds is used for postponeDuration. If the workflowDef.timeoutSeconds is not set, a default non-zero value is used the postpone duration. …
> Set unack/postpone duration based on task state

- cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/util/Statements.java
- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Join.java
- core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
- core/src/test/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtilsTest.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DecisionTaskSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRerunSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRestartSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/HierarchicalForkJoinSubworkflowRetrySpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/NestedForkJoinSubWorkflowSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SwitchTaskSpec.groovy
----
----
The JOIN task is made async and will be evaluated by the async system task executor and the system task workers off the JOIN task queue. This improves the efficiency of workflow evaluations because the workflow will now be evaluated only after the JOIN task reaches a terminal state rather than for every forked task update leading to empty evaluations.
> JOIN task is made async

- docs/docs/configuration/workerdef.md
----
----
fix a typo in docs
Issue # N/A
----
N/A
N/A
> typo fix in docs (workerdef)

- docs/docs/how-tos/Workflows/debugging-workflows.md
- docs/docs/how-tos/Workflows/starting-workflows.md
----
----
Fixed code formatting in `starting-workflows.md`, and links in `debugging-workflows.md`.
----
> [Docs] Small docs fixes

- docker/serverAndUI/Dockerfile
- docs/docs/gettingstarted/docker.md
Set the correct startup script so that the UI is served.
----
----
Updated the Dockerfile for the combined server and UI combined image.
The front end was not being served. The Dockerfile now uses the correct startup script.
----
> Updated serverAndUI Dockerfile to set the correct startup script

- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowSweeper.java
- core/src/main/java/com/netflix/conductor/metrics/Monitors.java
- core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowSweeper.java
----
Add a jitter to the default wokflowOffsettime to spread out the load on the queue.
Issue #
----
> Add jitter to workflowoffset time

- client/src/main/java/com/netflix/conductor/client/automator/PollingSemaphore.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
- client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
- client/src/main/java/com/netflix/conductor/client/worker/Worker.java
- client/src/test/java/com/netflix/conductor/client/automator/PollingSemaphoreTest.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
- client/src/test/java/com/netflix/conductor/client/automator/TaskRunnerConfigurerTest.java
----
----
Issue #
Support to batch polling tasks in client
----
> batch polling in client

- core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java
- core/src/test/groovy/com/netflix/conductor/core/execution/tasks/DoWhileSpec.groovy
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
- test-harness/src/test/resources/do_while_with_decision_task.json
----
----
Issue #https://github.com/Netflix/conductor/issues/3271
There was error in calculating the relevant task for do_while task.
> Do_while task relevant loop over task calculation fix

- java-sdk/testing_framework.md
- java-sdk/worker_sdk.md
- java-sdk/workflow_sdk.md
Fixed the 404 error for the existing task input link and some minor updates on the content.
----
----
Issue #
----
> doc updates.md

- grpc/build.gradle
----
----
Fix builds for m1 mac.
Issue #
----
> add support compilation on m1 mac

- docs/docs/how-tos/Workers/build-a-java-task-worker.md
----
- Documented the missing `com.netflix.conductor.conductor-common` dependency.
- Healed numerous MD issues
> Improve Java Worker documentation

- docs/docs/externalpayloadstorage.md
----
----
The documentation page for external payload storage was out of sync with the actual properties used to configure this feature in the code.
> Update the docs for external payload storage to match the code

- common/src/main/java/com/netflix/conductor/common/utils/ExternalPayloadStorage.java
- core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
- core/src/test/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtilsTest.java
Signed-off-by: Simon Misencik <simon.misencik@gmail.com>
----
----
Discussion: https://github.com/Netflix/conductor/discussions/3384
This PR adds an option to add payloadBytes variable into the getLocation method. These payloadBytes are then used in externalStorage to calculate the digest. This digest is then used to determine whether the same data is already stored in the database.
----
> feature: Add option to add payloadBytes into getLocation method

- ui/src/components/diagram/WorkflowGraph.jsx
----
----
Event.path is deprecated in chrome as of the last update https://chromestatus.com/feature/5726124632965120. This is causing a bug when clicking on a task in the UI. This is also see in safari: https://github.com/Netflix/conductor/issues/3330. Updating to use composedPath() instead per guidance.
This is compatible with all browsers:
https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath
See the error we are seeing in the Chrome UI below
Issue #
https://github.com/Netflix/conductor/issues/3330
> Task details not showing in UI

- annotations-processor/dependencies.lock
- annotations/dependencies.lock
- awss3-storage/dependencies.lock
- awssqs-event-queue/dependencies.lock
- build.gradle
- cassandra-persistence/dependencies.lock
- client-spring/dependencies.lock
- client/dependencies.lock
- common/dependencies.lock
- core/dependencies.lock
- dependencies.lock
- es6-persistence/dependencies.lock
- grpc-client/dependencies.lock
- grpc-server/dependencies.lock
- grpc/dependencies.lock
- http-task/dependencies.lock
- java-sdk/dependencies.lock
- json-jq-task/dependencies.lock
- redis-concurrency-limit/dependencies.lock
- redis-lock/dependencies.lock
- redis-persistence/dependencies.lock
- rest/dependencies.lock
- server/dependencies.lock
- test-harness/dependencies.lock
----
- [ X] Bugfix
----
Upgrade log4j and also loosen the constraint so that people that use the libraries, such as `common` or `client` can upgrade their log4j on their end to **future** versions. 
The current strictness constraint on log4j does not allow people that use Conductor to upgrade log4j on their end. This should make it a minimum to be 2.17.2, but also allow for people to move further ahead if they need to as well.
> Allow for an upgrade of log4j2 versions by loosening constraint

- docs/docs/gettingstarted/docker.md
----
Made the FAQ/Problems section a bit less confusing.
> Improve Elasticsearch-related problems description

- core/src/main/java/com/netflix/conductor/core/sync/local/LocalOnlyLock.java
- core/src/test/java/com/netflix/conductor/core/sync/local/LocalOnlyLockTest.java
----
- [ X] Bugfix
----
It did not support reentrancy.
This was a problem at least in following case:
worker -> updateTask -> throw new TerminateWorkflowException -> terminateWorkflow
The lock was acquired twice during above execution order. With no reentrancy, the second lock (wf terminateion) failed and sweeper had to wait until the first lock (task update) was released and only then workflow could be terminated.
----
No alternatives, this was a clear break of the API contract as defined in the Lock service
> Make LocalOnlyLock reentrant

- awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/config/SQSEventQueueConfiguration.java
- awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/config/SQSEventQueueProperties.java
----
----
When testing workflows, it's good to be able to spin up everything in Docker in CI and run them. This enables the endpoint for SQS to be configured so that it's possible to run SQS against something like Localstack
> Enable the endpoint to be configured for SQS

- build.gradle
- client-spring/build.gradle
- client-spring/src/main/java/com/netflix/conductor/client/spring/ConductorClientAutoConfiguration.java
- client-spring/src/main/java/com/netflix/conductor/client/spring/ConductorWorkerAutoConfiguration.java
- client-spring/src/main/java/com/netflix/conductor/client/spring/SpringWorkerConfiguration.java
- client-spring/src/test/java/com/netflix/conductor/client/spring/Workers.java
- client-spring/src/test/resources/application.properties
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/WorkflowExecutor.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorker.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerExecutor.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/NonRetryableException.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/TaskContext.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/WorkerConfiguration.java
- java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerTests.java
- java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/executor/task/TestWorkerConfig.java
----
----
1. Make it possible to add `@Component` to the classes that has worker methods and they will get auto-initialized.
2. Allow more control in the annotated workers so users can use `callbackAfter` for long running tasks
3. New exception that allows user to indicate the task has failed and should not be retried
4. Ability to control polling interval - useful for long running tasks
5.  `TaskContext` allows getting access to the task and task result for inspecting task level information
Issue #
----
> Add spring support for annotated workers

- docs/docs/reference-docs/switch-task.md
Fix one word in `Switch` `defaultCase` description.
----
> [docs]: Update switch-task.md

- json-jq-task/src/main/java/com/netflix/conductor/tasks/json/JsonJqTransform.java
----
----
System tasks that are executed synchronously, should have `execute` method implemented to start them if it failed previously.
We noticed that during unclean shutdown of the servers, at times JQ task could get terminated and remains in progress without completion. 
This fix addresses that case and `restarts` the task, which should be safe to do since JQ is idempotent.
Issue #
----
> Call execute in case JQ execution failed to start

- docs/docs/labs/eventhandlers.md
An `ownerEmail` field is required to successfully submit the workflow to the API.
----
----
The workflow definitions in this tutorial fail due to an `ownerEmail` field not being present. The API will return a 400 with this error if it is currently submitted in the format defined in the documentation.
----
N/A
> Add `ownerEmail` to eventhandlers.md

- core/src/main/java/com/netflix/conductor/core/events/DefaultEventProcessor.java
- core/src/main/java/com/netflix/conductor/core/events/queue/ObservableQueue.java
----
----
Support Nack functionality for avoiding loosing messages when handling messages and getting unexpected errors
> Support Nack functionality for avoiding loosing messages on errors

- awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/config/SQSEventQueueConfiguration.java
----
----
When using SQS it's necessary to add an AWS Credentials Provider to the queue configuration. It seemed sensible to do this by default since most people will need this and they can modify it if necessary. It also means that if you build the server from the community repository, which imports the exported packages from the conductor core, it will now work, whereas previously it failed to start the server, rendering SQS unusable from the community server.
> Add in a default AWS credentials provider

- docker/docker-compose-postgres.yaml
Changing the docker file to use the elastic search with postgres and Redis.  The image will contain ES and Reids and based on configuration either both or none or one is required.
> elastic search with postgres.

- redis-lock/src/main/java/com/netflix/conductor/redislock/config/RedisLockConfiguration.java
- redis-lock/src/main/java/com/netflix/conductor/redislock/config/RedisLockProperties.java
----
- [ X ] Bugfix
----
We found it necessary for us to be able to change the connection allocation for our Redis Cluster Locking. This adds configurable properties so you can change Cluster connection settings through Redisson. The defaults are the defaults used by Redisson.
> Add Redis Cluster connection properties for Locking

- docs/docs/how-tos/clojure-sdk.md
----
----
fix document.
```
programatically -> programmatically
```
> fix typo in clojure-sdk.md

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/FailureWorkflowSpec.groovy
----
1. Pass complete failedWorkflow as input to failure workflow so that it does not require to have extra API calls to know more about the failure.
2. There will be a duplicate set of attributes since we were passing a few attributes already. They are kept as-is because if they are removed then it will require for workflow definition to change.
> Pass complete workflow as input to failure workflow.

- client-spring/src/main/java/com/netflix/conductor/client/spring/SpringWorkerConfiguration.java
- client-spring/src/test/resources/application.properties
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerExecutor.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/WorkerConfiguration.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/task/WorkerTask.java
----
- [x ] Feature
----
Allow adding domain as WorkerTask annotation.
e.g. 
```java
@WorkerTask(value = "hello_worker", pollingInterval = 100, domain="test")
```
Issue #
----
> Support task domains in the worker spring configuration

- ui/src/components/diagram/WorkflowGraph.jsx
----
----
Issue #3442 
Users can't click on the task at the flow diagram to open the right-side panel while using Firefox or Chrome browser.
Issue #3442 - Updated the code base to fix the task.
> fixed task card open in Chrome and Firefox

- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
----
- [ X ] Bugfix
----
Fixes an NPE for when a workflow can't be found for verify. If we throw the exception, it will be removed from the queue.
> Fix NPE for verify and repair if workflow not found

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
PR for https://github.com/Netflix/conductor/issues/3611
----
----
Issue #
----
> Issue-3611: TaskDef validation: Print actual value that is being validated

- client/src/main/java/com/netflix/conductor/client/http/EventClient.java
- core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
- java-sdk/src/main/java/com/netflix/conductor/sdk/testing/LocalServerRunner.java
- test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
----
----
In case reason for in-completion of a terminated task was null. Exception message would be set to null producing confusing entry in the log (just stating "null"). This commit makes it clearer what happened from the logs.
----
> Avoid exception message set to 'null'

- CHANGELOG.md
- core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java
- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowReconciler.java
----
----
Adds a new property to configure the timeout that the sweeper thread will poll for workflows to sweep.
It was hard coded as 2000 ms, which for certain environments can lead to an increase in the overall duration of a workflow execution, as seen with @marosmars.
This is especially relevant for environments with low amounts of workflows executing at a given time, coupled with moderate to high CPU count, and in workflows with several SUB_WORKFLOW tasks.
Issue #
----
> Add property for the timeout of sweeper polling for workflows

- core/src/main/java/com/netflix/conductor/core/execution/AsyncSystemTaskExecutor.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Join.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/WorkflowSystemTask.java
- core/src/test/groovy/com/netflix/conductor/core/execution/AsyncSystemTaskExecutorTest.groovy
----
The implemented approach of exponential backoff in join task calbackDuration.
Issue #
https://github.com/Netflix/conductor/discussions/3436
> Join task callBackDuration

- core/src/main/java/com/netflix/conductor/core/execution/AsyncSystemTaskExecutor.java
----
----
Removing dead messages from queue for non-existing tasks
Issue #3022
It'd be nice to understand why that happens, when everything is setup (lock). We have several evns and errors about non-existing tasks appeared after we updated conductor (it restarted).
```
ERROR|2023-06-08T06:41:41.822Z|[system-task-worker-8]|||c.n.c.c.e.AsyncSystemTaskExecutor.execute|TaskId: c52b3a28-c53a-4acf-8bff-d558d2ab7f8d could not be found while executing HTTP
```
> removing dead tasks from queue message

- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowSweeper.java
- core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowSweeper.java
> Fix WAIT task is not working properly (after v3.13.0)

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
----
----
When the task is updated we have put a performance improvement where we lazy evaluate the workflow state. This change was introduced in #3146 . Now when one of the forked tasks fails we should evaluate the workflow state immediately since the task can have a retry which is not exhausted. 
Issue #
Lazily evaluate workflow only in case the task is successful.
----
Alternative #3640  was raised
> Lazy evaluate workflow only in case of task is successful. 

- core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapperTest.java
----
Issue
----
Switch Task remains in PENDING state when the evaluator throws an exception
----
1. Now Switch Task will be in FAILED state, when Evaluator throws an exception during the evaluation of switchCase expression.
2. Added Unit test for the failure case.
> FIX: Switch Task remains in PENDING state when evaluator throws exception

- awss3-storage/src/main/java/com/netflix/conductor/s3/config/S3Configuration.java
- awss3-storage/src/main/java/com/netflix/conductor/s3/storage/S3PayloadStorage.java
----
----
_I've added ability to initialize AmazonS3 Client  as a separate Bean._ 
If someone use a S3 compatible storage (e.g. [Pure Storage](https://support.purestorage.com/FlashBlade/Purity_FB/PurityFB_REST_API/S3_Object_Store_REST_API/FlashBlade_S3_Object_Store_Documentation)), they will be able to initialize AmazonS3 in their @Configuration like in the example below and this client will be used for initializing [S3PayloadStorage](https://github.com/Netflix/conductor/blob/v3.13.7/awss3-storage/src/main/java/com/netflix/conductor/s3/storage/S3PayloadStorage.java#L55)
**Disable default client:** 
```yml
conductor.external-payload-storage.s3.use_default_client: …
```
> Added the ability to inject a custom AmazonS3 client

- ui/src/components/diagram/WorkflowDAG.js
----
----
See the error we are seeing in the UI below
The cause of the problem is that the Switch nodes and Fork nodes are not in  Do-While list.
<details><summary>Click to see, Workflow Definitions</summary>
<p>
```json
{
"createTime": 1687948608035,
"updateTime": 1687949526700,
"accessPolicy": {},
"name": "loop_and_switch",
"description": "loop_and_switch",
"version": 7,
"tasks": [
{
"name": "Loop Task",
"taskReferenceName": "LoopTask",
"inputParameters": {
"value": "${workflow.input.value}"
},
"type": "DO_WHILE",
"startDelay": 0,
"optional": false,
"asyncComplete": false,
"loopCondition": "if ( ($.LoopTask['iteration'] < $.value ) ) { true; } else { false; }", …
```
> Fix timeline not show when using the DO_WHILE loop.

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
----
Removed the TaskDef retryCount Cap that was set to 10
Issue #
Some of the workflows and the architecture is designed to work on the high retryCount. Capping it to 10 is breaking things on our side.
Instead of removing the Cap, making it configurable.
> Removing TaskDef retryCount cap of 10.

- docker/grpc/docker-compose.yaml
- docker/server/config/config-local.properties
- docker/server/config/config-mysql-grpc.properties
- docker/server/config/config-mysql.properties
- docker/server/config/config-postgres.properties
----
----
Added orkes related parameters to docker config properties.
Issue #https://github.com/Netflix/conductor/issues/3536
----
> Fix docker builds.

- core/src/main/java/com/netflix/conductor/core/utils/ParametersUtils.java
- core/src/test/java/com/netflix/conductor/core/utils/ParametersUtilsTest.java
----
----
https://github.com/Netflix/conductor/discussions/3760
Issue # If part of the path is another input, there is no way to use that currently. Specifically for array values. Instead of making a inline function that extracts out an item from an array. It would be nice todo this with just an Jsonpath expression.
----
> feature support nested jsonpath expressions

- .github/workflows/ci.yml
- java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/def/WorkflowCreationTests.java
1. Disable WorkflowCreationTest since it brings up a server and with JDK17, the test will not pass until a JDK17+ build is published.
2. Clean up the ci.yaml
----
- [x ] Other (please describe):
Fixes to the tests to support JDK17 move.
----
Issue #
----
> Fix test runs

- core/src/main/java/com/netflix/conductor/core/execution/mapper/WaitTaskMapper.java
----
----
Do not add 1 in until calculation.
Issue #
https://github.com/Netflix/conductor/pull/3775#pullrequestreview-1645749399
> Wait until calculation fix.

- ui/src/pages/definition/SaveTaskDialog.jsx
- ui/src/pages/definition/SaveWorkflowDialog.jsx
----
----
In workflow/task editor, the UI does not display the error message well when saving fails.
After fixing the bug, the UI can display detailed error message:
----
> Fix validation error handling in workflow/task editor

- core/src/main/java/com/netflix/conductor/core/storage/DummyPayloadStorage.java
- core/src/test/java/com/netflix/conductor/core/storage/DummyPayloadStorageTest.java
----
----
Implemented the incorrect or empty methods implementation in the `DummyPayloadStorage` class, such as `getLocation()`, `upload()`, and `download()`. These methods now utilize Disk based approach to store and retrieve data. Prior to this implementation, these methods were either empty or returning null, which led to NullPointerExceptions and caused HTTP workers to become stuck
----
We can create another Storage class and change the default value of `conductor.external-payload-storage.type` property pointing to that class, right now value of …
> issue-3719: Fix for http task stuck due to NPE

- common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskType.java
- core/src/main/java/com/netflix/conductor/core/execution/mapper/NoopTaskMapper.java
- core/src/main/java/com/netflix/conductor/core/execution/tasks/Noop.java
- core/src/test/java/com/netflix/conductor/core/execution/mapper/NoopTaskMapperTest.java
- core/src/test/java/com/netflix/conductor/core/execution/tasks/TestNoop.java
----
----
Added Noop Task
Added Noop Task Mapper
Purpose:
When using Switch tasks in usecases where we want a consistent set of decision case branches across all workflows, but some workflows make use of a sub-set of all decision cases, then some decision cases will not have tasks. Because of the constraint to always have tasks in decision cases, this Noop task is required. This task is a system task and autocompletes.
> Introducing a Noop task to allow for switch decision cases to have "no" tasks

- build.gradle
----
----
The constraints that Conductor does on log4j is causing issues in conjunction with the Nebula publishing plugin that locks the version to 2.17.2. 
We should just drop the constraints from Conductor, since it's already just depending on Spring Boot for log4j which brings in 2.17.2 for you. This unlocks anyone who depends on the conductor-client and conductor-common published libraries.
> Remove log4j constraints for downstream users of client and common

- core/src/main/java/com/netflix/conductor/core/utils/ParametersUtils.java
- core/src/test/java/com/netflix/conductor/core/utils/ParametersUtilsTest.java
----
----
Issue #3804
This is because by default, the regular expression . matches any character except the line terminator: https://github.com/openjdk/jdk/blob/2edf9c3f1e968779c6e92b3e25d780db68ace5cc/src/java.base/share/classes/java/util/regex/Pattern.java#L890
----
> Fix JSONPath replace failed with line terminator

- redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisEventHandlerDAO.java
----
----
1. If one event handler gets updated to listen on a new event, remove its previous index of event handlers by events
To resolve #3842
----
> Bugfix/Data inconsistency caused by updateEventHandler

- core/src/main/java/com/netflix/conductor/core/execution/AsyncSystemTaskExecutor.java
EDIT: there's another race condition somewhere that we haven't been able to pinpoint. The reasoning below still holds, but does not fully solve the problem described.
----
----
Issue Summary:
There's a race condition in the system involving async system tasks and the WorkflowRepairService. For example, when a SUB_WORKFLOW task starts, the WorkflowRepairService sometimes erroneously reinserts the task into the processing queue because it perceives the task as out-of-sync between the ExecutorDAO and the queueDAO. This issue stems from the AsyncSystemTaskExecutor updating a task's status only after it removes it from the queue, creating a window where the …
> Fix double execution of Async system tasks when RepairService is enabled

- core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
- core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowSweeper.java
- core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowSweeper.java
----
----
Added a dependency to executorDaoFacade in WorkflowSweeper.
Added overloaded method in WorkflowRepairService - verifyAndRepairWorkflowTasks(WorkflowModel workflow)
Added overloaded method in WorkflowExecutor - decideWithLock(WorkflowModel workflow)
WorkflowSweeper now calls executorDaoFacade to get the workflow once and then passes is to the overloaded methods.
The new behaviour reduces the stress on the datastore during heavy loads. We have observed absurd loads on our redis instance comming from constant sweeping from the workflowSweeper ( more than 10GBps )
> Optimizing reading from datastore during WorkflowSweeper#sweep

- docs/docs/how-tos/Workers/build-a-golang-task-worker.md
----
----
Fix typo `provies` -> `provides`
----
N/A
> Fix typo in build-a-golang-task-worker.md

- redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisProperties.java
- redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisSentinelConfiguration.java
- redis-persistence/src/main/java/com/netflix/conductor/redis/config/RedisStandaloneConfiguration.java
----
Feature
----
This adds properties for database index and username to the redis properties for standalone and sentinel.
Issue/Discussion
----
https://github.com/Netflix/conductor/discussions/3713
> Adding Redis db index and username properties

- ui/src/pages/workbench/WorkbenchForm.jsx
----
----
On the Workflow Workbench page, when the 'Task to Domain (JSON)' field of Run History has a value filled in, the field is not echoed after refreshing the page.
----
> Fix taskToDomain field not being echoed

- .gitattributes
----
- [ x] Bugfix
- [ x] Build related changes (Please run `./gradlew generateLock saveLock` to refresh dependencies)
----
When pulling the repository to a windows machine git will automatically convert the files line ending to windows format (CRLF). This however is not compatible with Gradle. To prevent git from automatically changing these when the repository is pulled, the .gitattribute file has been updated and the below lines have been added.
```gradlew eol=lf
*.gradle eol=lf
*.java eol=lf
*.groovy eol=lf
spring.factories eol=lf
*.sh eol=lf
```
----
_Describe alternative …
> Add support for building on windows

- core/src/main/java/com/netflix/conductor/service/MetadataServiceImpl.java
- core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
- core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
While adding a workflow definition, its required to validate the javascript snippet added in the decision/switch task. This will help to avoid the errors in switch task during workflow execution.
----
----
Issue #
----
> ISICO-15108: javascript validation done on updating w/d

- README.md
----
----
Updated 2 links in README to match the new https://conductor.netflix.com/ URLs caused by the split of docs into the conductor-docs repo.
Also removes the link to https://artifacts.netflix.net/ since the site is no longer available.
This change is needed because broken links make for a poor onboarding experience.
> Update links in README to match conductor-docs changes

- ui/src/components/NavLink.jsx
- ui/src/plugins/AppLogo.jsx
- ui/src/plugins/fetch.js
----
----
Issue #
- Fixing redundant slash that cause the proxy fail when calling API
Slack reference: https://orkes-conductor.slack.com/archives/C02KJ820XPW/p1701315386966159
----
> [Hot-fix] fix: remove redundant slash that cause proxy fail
