docs/intro/index.md
docs/metadata/index.md
docs/metadata/task.md

Really interesting project y'all 😄 . Just spotted a few minor typos while reading through the docs.
Happy to squash all the commits down to one, if you prefer.

Minor Documentation Fixes

---

docker/README.md
docker/server/README.md
docker/serverAndUI/README.md
docker/ui/README.md

Updates the `docker run` commands in the READMEs to include ports

Docker readme update

---

build.gradle
client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java
client/src/test/java/com/netflix/conductor/client/sample/Main.java
client/src/test/java/com/netflix/conductor/client/sample/SampleWorker.java
client/src/test/java/com/netflix/conductor/client/worker/TestPropertyFactory.java
client/src/test/python/wfclientUnitTests.py
common/src/main/java/com/netflix/conductor/common/metadata/events/EventHandler.java
common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskExecLog.java
core/src/main/java/com/netflix/conductor/core/events/ActionProcessor.java
core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java
core/src/main/java/com/netflix/conductor/core/execution/SystemTask.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/core/execution/tasks/Event.java
core/src/main/java/com/netflix/conductor/service/ExecutionService.java
core/src/test/java/com/netflix/conductor/core/events/MockObservableQueue.java
core/src/test/java/com/netflix/conductor/core/events/TestActionProcessor.java
core/src/test/java/com/netflix/conductor/core/events/TestEventProcessor.java
core/src/test/java/com/netflix/conductor/core/events/TestScriptEval.java
core/src/test/java/com/netflix/conductor/core/execution/tasks/TestEvent.java
jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java
redis-persistence/src/main/java/com/netflix/conductor/dao/index/ElasticSearchDAO.java
redis-persistence/src/main/resources/archive.json
redis-persistence/src/main/resources/task_log.json
redis-persistence/src/main/resources/template.json
redis-persistence/src/main/resources/wfe_type.json

* Minor Fixes
* Ability to expand inline JSON docs
* Task complete actions
* Task.java has backward compatible field 'taskStatus'

Eventing Support

---

docs/docs/metadata/index.md

Hello,
Just a tiny fix regarding the doc, probably more useful PRs to come!
Nicolas

Fix documentation typo

---

server/src/main/resources/swagger-ui/index.html

e.g :  http://127.0.0.1:8080/?url=192.168.1.12:8080

Fix swagger-ui by parameter access

---

contribs/src/main/java/com/netflix/conductor/contribs/json/JsonJqTransform.java
server/src/main/java/com/netflix/conductor/server/ServerModule.java

See comments being addressed on PR https://github.com/Netflix/conductor/pull/227#issuecomment-310746406
Ping @tommack @v1r3n

Address code review comments from @tommack on pull request #227

---

client/python/conductor/ConductorWorker.py

1. Made the thread a daemon so that the entire process exits on Ctrl+C
2. Added a sleep(1) so that the waiting thread does not hog cpu resources.

Fix threading and cpu issues

---

client/python/conductor/ConductorWorker.py

fixed error where ConductorWorker had an ImportError in python 2.7

fix import error in python 2.7

---

mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java

After merging PR #315, there was a new API that was added on the QueueDAO that was missing when the PR was merged.
This PR is to add the missing API.

Add Missing Queue DAO API

---

mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java

With the current MySQL Queue DAO implementation, tasks sometimes get executed multiple times even if the first attempt ends in success.
This PR is to fix that issue

Fix tasks getting executed multiple times with MySQL storage backend

---

es5-persistence/build.gradle

Solved #346, NoClassDefFoundError: org/apache/logging/log4j/util/Refl…

Solved #346

---

es5-persistence/README.md
es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAO.java
jersey/src/main/java/com/netflix/conductor/server/resources/MetadataResource.java
mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java

Some bug fixed ,e.g. Don't to index an empty task exec log

Minimal adjust, Don't to index an empty task exec log and more things

---

mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java
mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLQueueDAOTest.java

Reworked **pollMessages** to peek message IDs (instead of pop), retrieve the Messages from persistence, _then_ pop the message IDs in a single transaction.
**peekMessages** was overloaded to accept a **Connection** to allow it to be part of a single transaction. 
Methods that call the original **peekMessages(String, int)** method will behave normally, as that starts a new transaction and calls **peekMessages(Connection, String, int)**
**readMessages(String, int)** was refactored to **readMessages(Connection, String, int)** as the only caller was **pollMessages** which now needs to call **readMessages** in the context of the transaction it started.

Fix MySQL queue message polling (#399)

---

es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAO.java
jersey/src/main/java/com/netflix/conductor/server/resources/MetadataResource.java
mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java

@grfeng  These changes are not backward compatible. Please do create a PR with the backward compatible changes.

Revert "Minimal adjust, Don't to index an empty task exec log and more things"

---

core/build.gradle
core/src/main/java/com/netflix/conductor/core/events/ActionProcessor.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/core/execution/tasks/SystemTaskWorkerCoordinator.java
core/src/main/java/com/netflix/conductor/core/utils/RetryUtil.java
core/src/main/java/com/netflix/conductor/dao/IndexDAO.java
core/src/main/java/com/netflix/conductor/service/ExecutionService.java
es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAO.java
gradle/wrapper/gradle-wrapper.properties
mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisExecutionDAO.java
redis-persistence/src/main/java/com/netflix/conductor/dao/index/ElasticSearchDAO.java
test-harness/src/test/java/com/netflix/conductor/tests/utils/MockIndexDAO.java
versionsOfDependencies.gradle

This PR has a RetryUtility to be used in flaky function execution scenarios.
Tests will follow soon on the same PR

Seperate out Async/sync execution of indexing methods to fix the archival errors

---

buildViaTravis.sh
client/build.gradle
client/dependencies.lock
client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java
client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskMetrics.java
client/src/main/java/com/netflix/conductor/client/worker/PropertyFactory.java
client/src/main/java/com/netflix/conductor/client/worker/Worker.java
client/src/test/java/com/netflix/conductor/client/sample/SampleWorker.java
client/src/test/java/com/netflix/conductor/client/task/WorkflowTaskCoordinatorTests.java
jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/End2EndTests.java
versionsOfDependencies.gradle

Client:
- Added javadocs
- Improved logging
- Improved exception handling

added javadocs, logging and exception handling to client

---

redis-persistence/src/main/resources/wfe_type.json

The workflow mapping file (`wfe_type.json`) is missing the `archived` field. Add that in as a `boolean`.

Add a field mapping for archived

---

client/python/.gitignore
client/python/conductor/ConductorWorker.py
client/python/conductor/conductor.py
client/python/test_conductor.py

* Added ability to do long-polling via python client (/poll/batch)
* Added ability to specify taskDomain via python client
* minor pep8 cleanup

python client improvements

---

client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java
client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskMetrics.java
client/src/test/java/com/netflix/conductor/client/task/WorkflowTaskCoordinatorTests.java
core/src/main/java/com/netflix/conductor/core/config/Configuration.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/metrics/Monitors.java
core/src/main/java/com/netflix/conductor/service/ExecutionService.java
core/src/test/java/com/netflix/conductor/core/execution/TestConfiguration.java
jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java
mysql-persistence/src/test/java/com/netflix/conductor/config/TestConfiguration.java
redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/BaseDynoDAO.java
redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisExecutionDAO.java
redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisMetadataDAO.java
redis-persistence/src/test/java/com/netflix/conductor/config/TestConfiguration.java
server/src/main/java/com/netflix/conductor/server/ConductorConfig.java
server/src/main/java/com/netflix/conductor/server/ConductorServer.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/End2EndTests.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/WorkflowServiceTest.java

Also added a bug fix for FAILED_WITH_TERMINAL_ERROR Workflow output

Added the barriers to fail the task and workflows with large output

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/WorkflowServiceTest.java

Revert "Fix for scheduling tasks after executing system tasks"

---

mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java

- Updated column name from 'execution_event' to 'event_name' in updateEventExecution method in MySQLExecutionDAO.java

Fixed the column name in MySQLExecutionDAO.java

---

test-harness/src/test/java/com/netflix/conductor/tests/utils/MockIndexDAO.java

fix invalid signature in the mock file

---

mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java
mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAOTest.java

https://github.com/Netflix/conductor/issues/576
As per the issue mentioned, I have fixed the deadlock issue.
I wrote a multi threaded test case with 10 concurrent requests. Please review and let me know if code can be merged. I have changed the below two files. All of the tests succeed after these changes
https://github.com/jvemugunta/conductor/blob/4b721c5b42177f068da88ff3d70abacb64db8d61/mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAO.java#L811-L818
https://github.com/jvemugunta/conductor/blob/9a378b70164f401e8c496c7bf2e1931836a7627f/mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLExecutionDAOTest.java#L144-L180

Fixed Deadlock issue with MySQL database

---

client/python/conductor/conductor.py

I created a pull request for the dev branch again.  
Please check the following for details.
* https://github.com/Netflix/conductor/pull/530
* https://github.com/Netflix/conductor/pull/529
* https://github.com/Netflix/conductor/pull/514
* https://github.com/Netflix/conductor/pull/513

Update and fix bugs for python sdk

---

client/go/conductorhttpclient.go
client/python/conductor/conductor.py
client/src/main/java/com/netflix/conductor/client/http/MetadataClient.java
client/src/test/java/com/netflix/conductor/client/http/MetadataClientTest.java
client/src/test/java/com/netflix/conductor/client/metadata/workflow/TestWorkflowTask.java
core/src/main/java/com/netflix/conductor/dao/MetadataDAO.java
core/src/main/java/com/netflix/conductor/service/MetadataService.java
jersey/src/main/java/com/netflix/conductor/server/resources/MetadataResource.java
mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAO.java
mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAOTest.java
redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisMetadataDAO.java
redis-persistence/src/test/java/com/netflix/conductor/dao/dynomite/RedisMetadataDAOTest.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/End2EndTests.java

Description:
API to delete workflow definition. 
Sample curl call:
```curl -X DELETE "http://localhost:8080/metadata/workflow/kitchensinkTest?version=1" -H "accept: application/json"```

API to delete workflow definition

---

common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java
core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/TaskMapperContext.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/UserDefinedTaskMapper.java
core/src/main/java/com/netflix/conductor/service/DummyRateLimitingService.java
core/src/main/java/com/netflix/conductor/service/MetadataService.java
core/src/main/java/com/netflix/conductor/service/RateLimitingService.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/DynamicTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/EventTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/ForkJoinTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/JoinTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/SimpleTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/UserDefinedTaskMapperTest.java
core/src/test/java/com/netflix/conductor/core/execution/mapper/WaitTaskMapperTest.java
redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisMetadataDAO.java
redis-persistence/src/test/java/com/netflix/conductor/dao/dynomite/RedisMetadataDAOTest.java

The Rate limiting configuration abstraction is currently at the TaskDef level and the rate limit is evaluated before starting execution in the WorkflowExecutor.
The Dummy implementation of the rate limit is provided by the `DummyRateLimitingService.java`

Rate Limiting Abstraction for Tasks

---

core/src/main/java/com/netflix/conductor/core/events/ActionProcessor.java
core/src/main/java/com/netflix/conductor/core/events/EventProcessor.java

fix json payload handling in the event processor

Event processor json payload fix

---

core/src/main/java/com/netflix/conductor/metrics/Monitors.java
jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java

Description:
- Added task poll count metric.

Add task poll count metric

---

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
grpc/src/main/proto/model/workflowtask.proto

This field was added without being marked/annotated as a protofield and therefore wasn't added to the proto files and corresponding models.

Fix missing ProtoField.

---

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractEndToEndTest.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/End2EndGrpcTests.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/End2EndTests.java

- Added missing tests for creating workflow executions with {ephemeral,stored} tasks

Grpc integration tests for ephemeral workflows and tasks

---

.gitignore
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java

This is in reference to the issue #780
@v1r3n and @cyzhao - Can you please review this PR when you get a chance

Fixed the timeout issue when retryCount > 0 on the taskdefinition

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java

@cyzhao - This was the correct code snipped for the PR #781.
Please accept this code

change made for the closed PR #781

---

contribs/src/main/java/com/netflix/conductor/contribs/ContribsModule.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/sqs/SQSObservableQueue.java
contribs/src/main/java/com/netflix/conductor/core/events/sqs/SQSEventQueueProvider.java
contribs/src/test/java/com/netflix/conductor/core/events/sqs/TestSQSEventQueueProvider.java
core/src/main/java/com/netflix/conductor/core/events/EventProcessor.java
core/src/main/java/com/netflix/conductor/metrics/Monitors.java

- Updated SQSEventQueueProvider options to be configurable. 
- Added metric to track the rate at which event messages are handled.

Updated SQSEventQueueProvider options to be configurable. 

---

docs/docs/runtime/index.md

This is tiny change to correct typo in docs.

correct typo in doc

---

client/src/main/java/com/netflix/conductor/client/http/MetadataClient.java
client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
common/src/main/java/com/netflix/conductor/common/metadata/workflow/StartWorkflowRequest.java
core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
core/src/main/java/com/netflix/conductor/core/events/ActionProcessor.java
core/src/main/java/com/netflix/conductor/core/events/EventProcessor.java
core/src/test/java/com/netflix/conductor/core/events/TestActionProcessor.java
core/src/test/java/com/netflix/conductor/core/events/TestEventProcessor.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/End2EndTests.java

- Removed deprecated client APIs
- Fixed start workflow based on event action
- Moved JsonUtils to provider

remove deprecated client APIs and fix start workflow from event

---

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
common/src/main/java/com/netflix/conductor/common/run/Workflow.java

Revert "fix compatibility with 1.x"

---

core/src/main/java/com/netflix/conductor/core/config/Configuration.java
docs/docs/server/index.md
redis-persistence/src/main/java/com/netflix/conductor/jedis/JedisClusterSentinel.java
redis-persistence/src/main/java/com/netflix/conductor/jedis/RedisSentinelJedisProvider.java
redis-persistence/src/test/java/com/netflix/conductor/jedis/JedisClusterSentinelTest.java
server/README.md
server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
server/src/main/java/com/netflix/conductor/server/RedisSentinelModule.java

New RedisSentinelJedisProvider class which uses the
JedisSentinelPool to do all the magic.
Also a new config option to choose the redis_sentinel as DB type.

Adds support for redis sentinel deployments

---

redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/RedisExecutionDAO.java

If Task already scheduled, skipping setScheduledTime!

Set Task scheduledTime only after successful added!

---

redis-persistence/src/main/java/com/netflix/conductor/jedis/TokenMapSupplierProvider.java

fix for token supplier provider with multiple dyno hosts

---

common/src/main/java/com/netflix/conductor/common/utils/ConstraintParamUtil.java
common/src/test/java/com/netflix/conductor/common/utils/ConstraintParamUtilTest.java

Description:
Disable predefine environment variable validation.

(fix): disable predefine environment variables validation

---

client/go/conductorhttpclient.go
client/go/conductorworker.go
client/go/httpclient/httpclient.go

1) Acktask now calls the right endpoint, and checks the response
2) Http methods now check status codes for errors
3) PollAndExecute now parses the task, and then ack's
4) Execute now takes in a parsed Task

Acktask fixed, PollAndExecute modified

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/service/ExecutionService.java
server/src/main/java/com/netflix/conductor/server/ServerModule.java

- catch exception during polls
- init sweeper by default
- check nulls when updating task

catch exception during polls, init sweeper by default, check nulls when updating task

---

core/src/main/java/com/netflix/conductor/service/WorkflowBulkServiceImpl.java

remove duplicated code produced after fa35779916b3ce544ac728750b990e26e27a82f7 merge commit

remove duplicated code 

---

common/src/main/java/com/netflix/conductor/common/metadata/workflow/TaskType.java
common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java
core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
core/src/main/java/com/netflix/conductor/core/execution/SystemTaskType.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/ExclusiveJoinTaskMapper.java
core/src/main/java/com/netflix/conductor/core/execution/tasks/ExclusiveJoin.java
grpc/src/main/proto/model/workflowtask.proto
test-harness/src/test/java/com/netflix/conductor/tests/integration/ExclusiveJoinEndToEndTest.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/model/TaskWrapper.java
test-harness/src/test/java/com/netflix/conductor/tests/utils/JsonUtils.java
test-harness/src/test/resources/integration/scenarios/legacy/ExclusiveJoinTaskDef.json
test-harness/src/test/resources/integration/scenarios/legacy/ExclusiveJoinWorkflowDef.json
ui/src/api/wfegraph.js

Exclusive join takes output from one of the previous successful task based on the configuration. 
If the scenario is T1 -> [T2/T3] -> EJ -> T4 then, based on the decision T1 is followed by T2 or T3. If the decision cases are setup to execute T2 on true and T3 on false then, here is the outcome.
true  => T1 -> T2 -> EJ -> T4. EJ will produce the output of T2
false => T1 -> T3 -> EJ -> T4. EJ will produce the output of T3
null . => T1 -> EJ -> T4. EJ will produce the output of T1. Here the output of EJ is the result of the defaultExclusiveJoinTask configuration.
Ex:
```
{
"name": "exclusive_join",
"taskReferenceName": "exclusiveJoin",
"type": "EXCLUSIVE_JOIN",
"joinOn": [
"task2",
"task3"
],
"defaultExclusiveJoinTask": [
"task1"
]
}
```

Task output of last executed task

---

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
test-harness/src/test/resources/integration/scenarios/legacy/optional_task_wf.json

Hello, 
after the discussion #1060 about the possibility to enable retry in case of optional tasks, I did this PR.
Let me know if I missed something, or if you expect some refactoring.
Thank you

Enable retry on optional tasks

---

ui/package-lock.json

Fix the UI docker-compose build step

---

CONTRIBUTING.md
server/src/main/resources/swagger-ui/lib/handlebars-4.0.5.js

Fixed two links, old links are 404

Fixed some links

---

core/build.gradle
core/src/main/java/com/netflix/conductor/core/config/Configuration.java
core/src/main/java/com/netflix/conductor/core/config/CoreModule.java
core/src/main/java/com/netflix/conductor/core/config/NoopLockModule.java
core/src/main/java/com/netflix/conductor/core/config/SystemPropertiesConfiguration.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/core/utils/Lock.java
core/src/main/java/com/netflix/conductor/core/utils/NoopLock.java
core/src/main/java/com/netflix/conductor/service/ExecutionLockService.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
server/build.gradle
server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java
server/src/main/resources/server.properties
settings.gradle
test-harness/src/test/java/com/netflix/conductor/tests/utils/MySQLTestModule.java
test-harness/src/test/java/com/netflix/conductor/tests/utils/TestModule.java
zookeeper-lock/build.gradle
zookeeper-lock/src/main/java/com/netflix/conductor/zookeeper/ZkLock.java
zookeeper-lock/src/main/java/com/netflix/conductor/zookeeper/config/SystemPropertiesZookeeperConfiguration.java
zookeeper-lock/src/main/java/com/netflix/conductor/zookeeper/config/ZookeeperConfiguration.java
zookeeper-lock/src/main/java/com/netflix/conductor/zookeeper/config/ZookeeperModule.java
zookeeper-lock/src/test/java/com/netflix/conductor/zookeeper/TestZkLock.java

Zookeeper lock implementation.
@kishorebanala @apanicker-nflx @cyzhao

Lock implementation using Zookeeper

---

ui/src/reducers/workflow.js
ui/test/reducers/workflow.test.js

Fixed typo in `workflow` reducer and added basic test for `REQUEST_ERROR` action

Fixed typo in reducer and added test

---

.travis.yml
common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
core/src/main/java/com/netflix/conductor/core/metadata/MetadataMapperService.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
core/src/test/java/com/netflix/conductor/core/metadata/MetadataMapperServiceTest.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
test-harness/src/test/resources/integration/scenarios/legacy/test_wait_timeout.json

allow adding task definitions for system tasks to configure timeouts etc

---

docs/docs/configuration/systask.md

Updating the documentation to contain complete task payload for Kafka task. 
@kishorebanala please take a look. Related to issue: https://github.com/Netflix/conductor/issues/1295

Updates kafka documentation

---

ui/src/components/workflow/executions/WorkflowSearch.js

Added back the getWorkflowDefs

Added back getWorkflowDefs

---

server/build.gradle
server/src/main/java/com/netflix/conductor/bootstrap/Main.java
server/src/main/java/com/netflix/conductor/jetty/server/JettyServer.java

Optionally register MBeanContainer on startup to enable JMX metric reports.
Fix dangling java docs.

optional MBeanContainer registration

---

core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java
core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java

Fix the bug #1371 addording to the [using inputTemplate](https://netflix.github.io/conductor/configuration/taskdef/#using-inputtemplate) document.

fix for using inputTemplate bug (#1371).

---

client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
client/src/main/java/com/netflix/conductor/client/http/TaskClient.java
client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java

fix task poll NPE

---

docs/docs/configuration/systask.md

In particular, add the type of each parameter for a DECISION, and document its output.

Update DECISION task documentation

---

README.md
RELATED.md

The objective of this page is to collect some Conductor related projects that could help people using Conductor in real operations.

Adding RELATED page with some community projects related to Conductor

---

docs/docs/architecture.md

Also, try to make it clear that ui and server are both in the root directory.

Add missing npm i

---

common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskDef.java
core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
docs/docs/configuration/taskdef.md

As explained here: https://github.com/Netflix/conductor/issues/407

Add a new task def attribute to support task poll timeout

---

azureblob-storage/src/test/java/com/netflix/conductor/config/InvalidTestConfiguration.java
azureblob-storage/src/test/java/com/netflix/conductor/config/TestConfiguration.java

* Update Configuration for tests: Add isEventMessageIndexingEnabled

[AzureBlobStorage] Follow up: Optional Event message indexing (#1462)

---

ui/src/api/wfe.js

...by reading subworkflowId directly from task object.

Fixed Subworkflow pane rendering

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java

Fix for Subworkflow task to render large payload location

---

es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchDAOV5.java
es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java
es5-persistence/src/test/java/com/netflix/conductor/dao/es5/index/TestElasticSearchRestDAOV5.java

Those tests may fail due to time zone, e.g. after 6PM in the pacific time zone.

fix a few ES tests due to time zone issue

---

docs/docs/configuration/systask.md

@elisherer: thanks for spotting it in https://github.com/Netflix/conductor/pull/1674.

doc: remove workflowInput from Sub workflow tasks documentation

---

common/src/main/java/com/netflix/conductor/common/metadata/workflow/SubWorkflowParams.java
common/src/test/java/com/netflix/conductor/common/workflow/SubWorkflowParamsTest.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java
core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
core/src/test/java/com/netflix/conductor/core/execution/tasks/TestSubWorkflow.java
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
grpc/src/main/proto/model/subworkflowparams.proto
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/WorkflowServiceTest.java
test-harness/src/test/java/com/netflix/conductor/tests/utils/MockConfiguration.java

This PR adds the inline subworkflow definition support to subworkflow task.

support inline subworkflow definition

---

core/src/main/java/com/netflix/conductor/service/WorkflowMonitor.java

Please consider adding the `task_queue_depth` for system task queues as well as it will be helpful to tune the `workflow.system.task.worker.thread.count` parameter and monitor system in high throughput scenarios.

Monitor task queue depth for async system tasks

---

postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresQueueDAO.java

I like the new logic from PR #1355 and the postgres_persistence module can benefit from the same changes.

Postgres queues: reduce the impact of racing by popping the queue 1 by 1

---

azureblob-storage/src/test/java/com/netflix/conductor/config/InvalidTestConfiguration.java
azureblob-storage/src/test/java/com/netflix/conductor/config/TestConfiguration.java

* Update Configuration for tests: Add isEventExecutionIndexingEnabled

[AzureBlobStorage] Follow up: Optional event execution indexing (#1720)

---

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
test-harness/src/test/groovy/com/netflix/conductor/test/util/WorkflowTestUtil.groovy
test-harness/src/test/groovy/com/netflix/counductor/integration/test/ForkJoinSpec.groovy
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
test-harness/src/test/resources/fork_join_sub_workflow.json

- Honor task definition for subworkflow task when used within a fork/join
- SUB_WORKFLOW task should not response timeout

fix subworkflow task def use within fork join

---

redis-lock/src/main/java/com/netflix/conductor/locking/redis/config/RedisLockConfiguration.java
redis-lock/src/main/java/com/netflix/conductor/locking/redis/config/RedisLockModule.java
server/src/main/resources/server.properties

fixes https://github.com/Netflix/conductor/issues/1700

1770 add master name to redisson config

---

core/src/main/java/com/netflix/conductor/core/execution/mapper/LambdaTaskMapper.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/SimpleTaskMapper.java
core/src/main/java/com/netflix/conductor/metrics/Monitors.java
core/src/main/java/com/netflix/conductor/service/ExecutionService.java
test-harness/src/test/groovy/com/netflix/conductor/test/util/WorkflowTestUtil.groovy
test-harness/src/test/groovy/com/netflix/counductor/integration/test/TaskLimitsWorkflowSpec.groovy
test-harness/src/test/resources/rate_limited_simple_task_workflow_integration_test.json
test-harness/src/test/resources/rate_limited_system_task_workflow_integration_test.json

- Enable rate limiting for simple tasks
- Fix start time for lambda task
- Remove usage of deprecated method for gauge initialization

extend rate limit feature to simple tasks; fix start time for lambda task

---

ui/src/api/wfegraph.js

DO_WHILE task in conductor UI was shown as a simple task. Its inner tasks was not shown in graph.
Add support for DO_WHILE task in wfegraph.js.

DO_WHILE: expand DO_WHILE task in conductor UI

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java

- Reset failure reason from previous build to default
when workflow is rerun

Fix for #1782

---

core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinTaskMapper.java
core/src/main/java/com/netflix/conductor/dao/ExecutionDAO.java
core/src/main/java/com/netflix/conductor/dao/IndexDAO.java
server/src/main/resources/swagger-ui/swagger-ui.js

This fixes repetitions like "the the", "is is" etc.

fix consecutive word repetitions

---

common/src/main/java/com/netflix/conductor/common/metadata/workflow/StartWorkflowRequest.java
core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java
grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImpl.java

Use the priority parameter to start workflow, the priority parameter does not take effect.

fix priority bug

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java

on priority Integer autoboxing (introduced in v2.29.1)

Fixing errors in start workflow due to npe

---

client/python/conductor/conductor.py

post request error occurs when task json contains non-english world.

encode body to utf8

---

cassandra-persistence/dependencies.lock
client/dependencies.lock
common/dependencies.lock
contribs/dependencies.lock
contribs/src/main/java/com/netflix/conductor/contribs/json/JsonJqTransform.java
core/dependencies.lock
dependencies.lock
es5-persistence/dependencies.lock
es6-persistence/dependencies.lock
grpc-client/dependencies.lock
grpc-server/dependencies.lock
grpc/dependencies.lock
jersey/dependencies.lock
mysql-persistence/dependencies.lock
postgres-persistence/dependencies.lock
redis-lock/dependencies.lock
redis-persistence/dependencies.lock
server/dependencies.lock
test-harness/dependencies.lock
ui/dependencies.lock
versionsOfDependencies.gradle
zookeeper-lock/dependencies.lock

Hello @apanicker-nflx, I completely agree about the comment that you left here: #1867 
However, there is a newer stable version, so please take in consideration this PR. Thanks

Update jq dependency to latest stable version

---

grpc-server/build.gradle
mysql-persistence/build.gradle
mysql-persistence/dependencies.lock
mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLBaseDAO.java
mysql-persistence/src/test/java/com/netflix/conductor/dao/mysql/MySQLMetadataDAOTest.java
postgres-persistence/build.gradle
postgres-persistence/dependencies.lock
postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresBaseDAO.java
postgres-persistence/src/test/java/com/netflix/conductor/dao/postgres/PostgresMetadataDAOTest.java
versionsOfDependencies.gradle

Fix for bug #1961 - fix response codes in posgres and mysql

---

core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java

Subworkflow doesn't return output #1849

Subworkflow doesn't return output

---

docs/docs/configuration/taskdef.md
docs/docs/configuration/workflowdef.md

Updated Task definition and Workflow definition documentation to include ownerEmail field which has been mandatory since v2.25.9.

Updated docs with ownerEmail example.

---

docs/docs/apispec.md
docs/docs/configuration/taskdef.md
docs/docs/configuration/workflowdef.md

update the docs of taskdef and workflowdef

Update taskdef and workflow def docs

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/service/WorkflowBulkServiceImpl.java
core/src/main/java/com/netflix/conductor/service/WorkflowService.java
core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
core/src/test/java/com/netflix/conductor/service/WorkflowBulkServiceTest.java
core/src/test/java/com/netflix/conductor/service/WorkflowServiceTest.java
grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImpl.java
grpc-server/src/test/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImplTest.java
grpc/src/main/proto/grpc/workflow_service.proto
jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
jersey/src/test/java/com/netflix/conductor/server/resources/WorkflowResourceTest.java
test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy
test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy
test-harness/src/test/groovy/com/netflix/conductor/test/integration/SubWorkflowSpec.groovy
test-harness/src/test/groovy/com/netflix/conductor/test/integration/WorkflowAndTaskConfigurationSpec.groovy
test-harness/src/test/groovy/com/netflix/conductor/test/resiliency/QueueResiliencySpec.groovy
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
ui/src/actions/WorkflowActions.js
ui/src/api/wfe.js
ui/src/components/workflow/executions/WorkflowAction.js

Issue #2026: 
The requested changes from the previous Pull Request are made: 
Pull Request #2025 Fixed the retry mechanism for subworkflows so that retry starts from the last failed task. 
co-authors: @grkn @azb96
Please guide through the contribution process @kishorebanala @apanicker-nflx @aravindanr @jfernandez

Issue #2026 Retry Subworkflow Mechanism

---

docs/docs/configuration/eventhandlers.md

Fix 404 in docs

---

cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/config/CassandraConfiguration.java
cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraExecutionDAO.java
cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraPollDataDAO.java

PollDataDAO implementation in C* persistence is extracted to its own class

PollDataDAO implementation is extracted to its own class

---

build.gradle
common/build.gradle

replace jcenter with maven central

---

contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/AMQPObservableQueue.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/config/AMQPEventQueueProvider.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/NATSAbstractQueue.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/config/NATSEventQueueProvider.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/config/NATSStreamEventQueueProvider.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/sqs/SQSObservableQueue.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/sqs/config/SQSEventQueueProvider.java
core/src/main/java/com/netflix/conductor/core/LifecycleAwareComponent.java
core/src/main/java/com/netflix/conductor/core/events/SimpleEventProcessor.java
core/src/main/java/com/netflix/conductor/core/events/queue/ConductorEventQueueProvider.java
core/src/main/java/com/netflix/conductor/core/events/queue/ConductorObservableQueue.java
core/src/main/java/com/netflix/conductor/core/events/queue/ObservableQueue.java
core/src/main/java/com/netflix/conductor/core/utils/JsonUtils.java
core/src/test/java/com/netflix/conductor/core/events/MockObservableQueue.java
core/src/test/java/com/netflix/conductor/core/utils/JsonUtilsTest.java
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java

- wire observable queue implementations with lifecycle to start/stop based on component lifecycle
- prevent implicit type-casting in json utils

wire observable queues with lifecycle

---

ui/src/api/wfe.js

This PR fixes [#1972](https://github.com/Netflix/conductor/issues/1972) issue.

Fetch subworkflow def when inline def is not available (#1972)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_question.md
.github/workflows/ci.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

----
----
- Added issue templates
- Added Code of Conduct
- Updated Contributing guide
- Updated ReadMe

added issue templates

---

client/python/conductor/ConductorWorker.py
client/python/kitchensink_workers.py

hi,
i'm adding new way to create task result with clearly structure and adding enumerate task status on python client for newbie choose the correct status of task after processed

update python client with structuring task result

---

.github/workflows/ci.yml
.github/workflows/publish.yml
build.gradle
core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchRestDAOV6.java
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractResiliencySpecification.groovy
test-harness/src/test/groovy/com/netflix/conductor/test/base/AbstractSpecification.groovy
test-harness/src/test/resources/application-integrationtest.properties

----
----
Upload and publish test-results from CI workflow

upload test artifacts and publish test results

---

.github/workflows/ci.yml
azureblob-storage/dependencies.lock
build.gradle
cassandra-persistence/dependencies.lock
client-spring/dependencies.lock
client/dependencies.lock
common/dependencies.lock
contribs/dependencies.lock
core/dependencies.lock
dependencies.lock
es6-persistence/dependencies.lock
grpc-client/dependencies.lock
grpc-server/dependencies.lock
grpc/dependencies.lock
mysql-persistence/dependencies.lock
postgres-persistence/dependencies.lock
redis-lock/dependencies.lock
redis-persistence/dependencies.lock
rest/dependencies.lock
server/dependencies.lock
test-harness/dependencies.lock
zookeeper-lock/dependencies.lock

----
----
Added sonar to PR builds.

Adds sonar to PR builds

---

RELATED.md

Adding the New Angular Based Web UI for Conductor for
- Medatadata Maganement
- Workflow Management
- Configuration Overview etc.
For more deyails - https://github.com/maheshyaddanapudi/conductor-ng-ui/blob/main/README.md
----
New Angular Based Web UI for Conductor
The idea is to build a single production grade Angular Web UI, to let the user interact with Conductor API, for the following
• Task definitions - Create / View / Update / Delete / Requeue Task / See Polling Data
• Workflow definitions - View / Execute / Delete
• Workflow Executions - View / Pause / Resume / Terminate / Retry / Restart / Archive / Delete
----
To avoid the pain points of
• Referring to documentation manually and then develop / write Request JSONs for API requests.
• Better …

Adding the New Angular Based Web UI for Conductor

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowRepairService.java

----
----
`verifyAndRepairWorkflowTasks` might be called when the workflow has already been removed.

Fix WorkflowRepairService if the workflow is removed

---

common/build.gradle
common/src/main/java/com/netflix/conductor/common/metadata/events/EventHandler.java
common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java
server/build.gradle

----
----
- Added the `springdoc-openapi-ui` dependency in "conductor/common/build.gradle".
- Updated the following entity classes(added the `@Hidden` annotation to `inputMessage` and `outputMessage` fields )
1. EventHandler
2. Task
Issue #2174

fixed the issue some endpoints not working in swagger-ui

---

server/build.gradle

----
----
Added missing dependency in the server for Postgres

add postgres missing dependency

---

.github/release-drafter.yml
contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
core/src/main/java/com/netflix/conductor/core/config/SchedulerConfiguration.java
core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/main/java/com/netflix/conductor/metrics/WorkflowMonitor.java
core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java
core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java

----
----
_Resource constrained environments can now limit the number of tasks in a workflow_

Added check for max tasks limit

---

README.md

----
----
_Instructions for running Conductor_

Added instructions to run Conductor

---

client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
client/src/test/java/com/netflix/conductor/client/http/WorkflowClientTest.java
core/src/main/java/com/netflix/conductor/service/ExecutionService.java
core/src/main/java/com/netflix/conductor/service/WorkflowService.java
core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java
core/src/test/java/com/netflix/conductor/service/ExecutionServiceTest.java
core/src/test/java/com/netflix/conductor/service/WorkflowServiceTest.java
grpc-client/src/main/java/com/netflix/conductor/client/grpc/WorkflowClient.java
grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImpl.java
grpc-server/src/test/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImplTest.java
grpc/src/main/proto/grpc/workflow_service.proto
jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
jersey/src/test/java/com/netflix/conductor/server/resources/WorkflowResourceTest.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractGrpcEndToEndTest.java
test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractHttpEndToEndTest.java

Issue #1992 add search api that returns Workflow instead of WorkflowSummary

Issue #1992 add search api that returns Workflow instead of WorkflowSummary

---

core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java

----
----
_Subworkflow tasks that may be in an inconsistent state will be auto-repaired by the WorkflowRepairService. Also, fixes parent workflow id that may be absent from decider queue as part of the sub workflow evaluation._

Improve repair service to auto-repair subworkflow

---

CHANGELOG.md

----
----
Update changelog with latest Postgres and MySQL properties.

Update changelog with latest Postgres and MySQL properties

---

RELATED.md

----
----
- Supports MongoDB Database version > 3.6.23+ - Tested well with 4.4.6
- Updated Dockerfile's startup.sh script (java -jar .... | tee server.log) to write logs to both Docker container as well as server.log file.
Feature
--
1. Mongo Persistence / Option to use Mongo Database as persistence unit.
2. Docker Compose example with MongoDB Container.
----
Many other persistence alternatives like Cassandra, MySQL, Postgres already exist. This is just an addition to persistence options.

Mongo Persistence Feature - Community Projects (RELATED.md)

---

docker/README.md

Some helpful tips for people using docker, which may encounter some issue that i faced. This is to provide a little helpful suggestion for them.
----
Added guide

Added troubleshooting guide for docker

---

RELATED.md

----
----
- Supports Oracle Database version > 12.2 - Tested well with 19C
- Updated Dockerfile's startup.sh script (java -jar .... | tee server.log) to write logs to both Docker container as well as server.log file.
Feature
--
1. Oracle Persistence / Option to use Oracle Database as persistence unit.
2. Docker Compose example with Oracle Container.
Technical Note
--
1. Utilizes Oracle Database version 11G for Unit Tests 
> Due to GuitHub GI Container disk space limitation, no version > 11G can be used for Unit Tests. 
Can be easily upgraded to 18 XE or 19C Enterprise once GitHub Action updates size capacity which they are apparantly working on).
2. Due to a technical version dependency, spring.flyway.locations cannot be automatically set to …

Oracle Persistence Feature - Community Projects (RELATED.md)

---

docker/grpc/docker-compose.yaml

----
----
Fix for discussion: https://github.com/Netflix/conductor/discussions/2303
* fix incorrect MySQL password.
* update MySQL version, as MySQL 5.6 is no longer supported by Flyway Community Edition.
* add a missing link from conductor server to elasticsearch.
* update elasticsearch version.

fix grpc docker compose

---

client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
rest/src/main/java/com/netflix/conductor/rest/controllers/WorkflowBulkResource.java
ui/src/api/wfe.js
ui/src/sagas/bulk.js

Switch bulk terminate to post

---

azureblob-storage/dependencies.lock
build.gradle
cassandra-persistence/dependencies.lock
client-spring/dependencies.lock
client/dependencies.lock
common/dependencies.lock
contribs/dependencies.lock
contribs/src/test/java/com/netflix/conductor/contribs/tasks/http/HttpTaskTest.java
core/dependencies.lock
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/metrics/Monitors.java
dependencies.gradle
dependencies.lock
es6-persistence/dependencies.lock
grpc-client/dependencies.lock
grpc-server/dependencies.lock
grpc/dependencies.lock
mysql-persistence/dependencies.lock
postgres-persistence/dependencies.lock
redis-lock/dependencies.lock
redis-persistence/dependencies.lock
rest/dependencies.lock
server/dependencies.lock
test-harness/dependencies.lock
test-harness/src/test/groovy/com/netflix/conductor/test/integration/DynamicForkJoinSpec.groovy
zookeeper-lock/dependencies.lock

----
----
- Retrying subworkflows that are within a dynamic fork join will correctly update parent workflow state
- Upgrade to SpringBoot 2.3.12.RELEASE
- Added a metric for tracking workflow starts
- Updated testcontainers version

fix for retrying subworkflows within dynamic fork join

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java

----
----
Ensure that workflow creation precedes any other action on the workflow by acquiring and holding the lock till creation is done.

acquire lock when creating workflow

---

postgres-persistence/src/main/java/com/netflix/conductor/dao/postgres/PostgresQueueDAO.java

Redoing previous pull request due to too many issues merging. This will change the way unacks are reset so that they will be processed again.
----
----
Issue #
----

Fix  bug in processUnacks, processAllUnacks for postgres - redo of previous pull request

---

common/src/main/java/com/netflix/conductor/common/metadata/workflow/DynamicForkJoinTaskList.java
common/src/test/java/com/netflix/conductor/common/utils/SummaryUtilTest.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java
es6-persistence/src/main/java/com/netflix/conductor/es6/dao/query/parser/internal/AbstractNode.java
grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/WorkflowServiceImpl.java
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisExecutionDAO.java
redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisMetadataDAO.java
redis-persistence/src/main/java/com/netflix/conductor/redis/jedis/JedisMock.java
redis-persistence/src/test/java/com/netflix/conductor/redis/jedis/JedisClusterTest.java
redis-persistence/src/test/java/com/netflix/conductor/redis/jedis/JedisSentinelTest.java

Co-authored-by: Moderne <team@moderne.io>
----
- [x ] Refactoring (no functional changes, no api changes)
----
Just helping clean up old generics uses to use the diamond operator where possible. Thanks!

refactor: use diamond operator

---

polyglot-clients/python/conductor/ConductorWorker.py

----
----
Added callbackAfterSeconds field for python client Conductor workers
----

Add callbackAfterSeconds for python client

---

docs/docs/configuration/systask.md

As explained on answer at https://github.com/Netflix/conductor/discussions/2379
----

docs(systask): specify queue name conductor sink

---

redis-persistence/src/main/java/com/netflix/conductor/redis/dao/RedisExecutionDAO.java

Prevent workflow_to_tasks mapping from being deleted  immediately during archiving when using archive with ttl  (Redis execution DAO only)
----
Separate removeTask logic when using archiving with TTL or without TTL
Set TTL to WORKFLOW_TO_TASKS entry instead of deleting it
Issue #2398
This issue is important because if a long TTL is configured in the server,  no tasks execution information  will available until the TTL is reached
No

[redis-persistence] Prevent workflow to tasks mapping from being deleted  immediately during archiving

---

README.md

----
Update the links with MVN repository
Issue #2457

Fix Conductor Artifacts Link

---

core/src/main/java/com/netflix/conductor/core/execution/tasks/WorkflowSystemTask.java

----
Code comment update. (due to my better understand of the matter, started in https://github.com/Netflix/conductor/discussions/2450)
Just to make it clearer what "start" and "execute" mean when someone wants to extend WorkflowSystemTask.
Also, any reason why WorkflowSystemTask is an abstract class, instead of an interface?

doc: expand comments in WorkflowSystemTask

---

contribs/dependencies.lock
dependencies.gradle
server/dependencies.lock
test-harness/dependencies.lock

----
----
`jackson-jq` is upgraded to the latest stable version `0.0.13`

jackson-jq upgrade

---

docker/ui/Dockerfile

See https://github.com/Netflix/conductor/discussions/2490#discussioncomment-1646442
----
----
Fixes: `docker/ui/Dockerfile` apk command error
Closes Issue #2576

Update ui/Dockerfile to address build failure

---

ui/src/components/diagram/WorkflowGraph.jsx
ui/src/pages/execution/Execution.jsx

----
- [ x] Feature
----
Workflow graph central alignment upon opening the Task panel 
Draggable and adjustable Task panel width

PR for #2548 [FEATURE]: [UI] Adjustable width task panel

---

ui/src/pages/execution/Execution.jsx

----
- [ x] Bugfix
Bugfix #2573

bug fix 2573

---

ui/src/components/diagram/WorkflowDAG.js

[UI] Task json fix: Removed start and finish task from json

---

cassandra-persistence/src/main/java/com/netflix/conductor/cassandra/dao/CassandraExecutionDAO.java
redis-concurrency-limit/src/main/java/com/netflix/conductor/redis/limit/RedisConcurrentExecutionLimitDAO.java
redis-concurrency-limit/src/main/java/com/netflix/conductor/redis/limit/config/RedisConcurrentExecutionLimitProperties.java
redis-concurrency-limit/src/test/groovy/com/netflix/conductor/redis/limit/RedisConcurrentExecutionLimitDAOSpec.groovy

----
----
No new features have been added. The `RedisConcurrentExecutionLimitDAO` was missing error handling, documentation and some key metrics, they were added.

Added metrics, error handling and documentation for RedisConcurrentExecutionLimitDAO

---

docker/server/Dockerfile
docker/server/bin/startup.sh
docker/server/config/config-local.properties

- pipe output to console in addition to logfile via tee
- Accept ES color yellow
- show stacktrace in build
----
----
Issue #
----

Adjust dockerfile and associated scripts

---

ui/src/pages/executions/ResultsTable.jsx

fix null point exception!
----
----
fix null point exception in src/pages/executions/ResultsTable, a null pointer exception will occur here when resultObj.results is nil.
Issue #
https://github.com/Netflix/conductor/issues/2604

fix NPE for ResultsTable.jsx

---

README.md
docs/docs/architecture.md
docs/docs/configuration/taskdef.md
docs/docs/configuration/workflowdef.md
docs/docs/gettingstarted/basicconcepts.md

----
----
Minor documentation changes to help new devs in getting things up & running.

[DOC] Minor documentation changes

---

contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/config/NATSStreamConfiguration.java
contribs/src/main/java/com/netflix/conductor/contribs/queue/nats/config/NATSStreamProperties.java
contribs/src/main/resources/META-INF/additional-spring-configuration-metadata.json

----
----
Added support of nats streaming server for WAIT task. It is similar to SQS implementation.

added nats stream support for WAIT task queues

---

polyglot-clients/python/conductor/ConductorWorker.py
polyglot-clients/python/conductor/conductor.py
polyglot-clients/python/test_conductor.py

----
- [x ] Bugfix
Removed task acking
Issue #
Task acking is deprectaed and should be reflected by the python client library
----

removed deprecated task acking

---

ui/README.md
ui/src/components/DataTable.jsx
ui/src/components/DateRangePicker.jsx
ui/src/components/Input.jsx
ui/src/components/KeyValueTable.jsx
ui/src/components/NavLink.jsx
ui/src/pages/definition/Workflow.jsx
ui/src/pages/definitions/Task.jsx
ui/src/pages/definitions/Workflow.jsx
ui/src/pages/execution/ActionModule.jsx
ui/src/pages/execution/Execution.jsx
ui/src/pages/execution/TaskList.jsx
ui/src/pages/executions/ResultsTable.jsx
ui/src/pages/executions/TaskSearch.jsx
ui/src/pages/executions/WorkflowSearch.jsx
ui/src/plugins/customTypeRenderers.jsx
ui/src/plugins/fetch.js
ui/src/theme/theme.js
ui/src/utils/query.js

----
----
Run prettier on UI code. Strictly cosmetic.
----

Run prettier on UI code. Strictly cosmetic.

---

annotations-processor/dependencies.lock
annotations/dependencies.lock
azureblob-storage/dependencies.lock
cassandra-persistence/dependencies.lock
client-spring/dependencies.lock
client/dependencies.lock
common/dependencies.lock
contribs/dependencies.lock
core/dependencies.lock
dependencies.gradle
dependencies.lock
es6-persistence/dependencies.lock
es7-persistence/dependencies.lock
grpc-client/dependencies.lock
grpc-server/dependencies.lock
grpc/dependencies.lock
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
grpc/src/main/proto/model/taskdef.proto
mysql-persistence/dependencies.lock
postgres-persistence/dependencies.lock
redis-concurrency-limit/dependencies.lock
redis-lock/dependencies.lock
redis-persistence/dependencies.lock
rest/dependencies.lock
server/dependencies.lock
test-harness/dependencies.lock
zookeeper-lock/dependencies.lock

----
----
Updated openapi to latest version

Updated openapi version to 1.6.+

---

WHOSUSING.md

----
----
added company info to WHOSUSING.md
----

added to WHOSUSING.md

---

WHOSUSING.md

add company info

---

WHOSUSING.md

----
- [✓] WHOSUSING.md
Added organization name

1.Added organization name in WHOSUSING.md

---

WHOSUSING.md

Signed-off-by: Tao Jiang <taoj@vmware.com>
----
----
Issue #2554
----

Add vmware as conductor user

---

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java

----
----
- When a sub workflow reaches a terminal state, the id of the parent workflow is pushed to the _deciderQueue_, if its not present. Previously, if the parent workflow id is present, it was _postponed_ which creates a race condition with other threads who maybe already processing the parent workflow.
- The _reasonForIncompletion_ is reset when a workflow is retried. This prevents the red error banner in the UI for completed workflows.
----
_N/A_

Sub workflow / parent workflow interaction fix

---

docs/docs/apispec.md

Remove mentions of deprecated ack API
----
----
Removing ack API listing in documentation as it is deprecated.
----

Update apispec.md - remove ack API mention

---

core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
test-harness/src/test/resources/do_while_sub_workflow_integration_test.json

Initial cut
----
Removed the constraint and added an integration test.
----
Issue #https://github.com/Netflix/conductor/pull/1435
----

Added support for sub workflow in loop task

---

core/src/main/java/com/netflix/conductor/core/execution/tasks/DoWhile.java

Wait and check only for the current iteration task to get completed.
----
- [] Refactoring (no functional changes, no api changes)
As of now, DoWhile task check the status of all previous iteration loopOver tasks. Ideally, we should wait and check only for current iteration loopOver tasks.
Issue #
NA
Sample logs,
```
[DEBUG] 2022-03-02 11:16:17.210 [system-task-worker-0] DoWhile - Workflow 5d297b62-2be5-4bb3-97a7-65436916713b waiting for tasks [first_task__1, second_task__1] to complete iteration 1
[DEBUG] 2022-03-02 11:16:17.558 [system-task-worker-0] DoWhile - Workflow 5d297b62-2be5-4bb3-97a7-65436916713b waiting for tasks [first_task__1, second_task__1, …
```

DO_WHILE improvement - Check only for current iteration task to get completed.

---

polyglot-clients/go/conductorhttpclient.go
polyglot-clients/go/conductorworker.go
polyglot-clients/go/go.mod
polyglot-clients/go/go.sum
polyglot-clients/go/httpclient/httpclient.go
polyglot-clients/go/startclient/startclient.go
polyglot-clients/go/task/sample/task_1_exec.go
polyglot-clients/go/task/taskresult.go

1. Use logrus for logging and add example on how to configure logging
2. Update logging to use logrus
3. Minor fixes
----
- [X ] Feature
----
1. Update logging to use logrus (https://github.com/sirupsen/logrus) - A popular golang logging library with options to configure format and logging level
2. Added example to show to configure logging
3. Fix to handle null LogMessage
Note: applied `go fmt` which has changed formatting.
----
n/a

Golang client updates

---

ui/package.json
ui/src/components/ReactJson.jsx
ui/src/components/diagram/WorkflowDAG.js
ui/src/components/diagram/WorkflowGraph.jsx
ui/src/hooks/useTime.js
ui/src/pages/execution/Execution.jsx
ui/src/pages/execution/ExecutionInputOutput.jsx
ui/src/pages/execution/ExecutionJson.jsx
ui/src/pages/execution/RightPanel.jsx
ui/src/pages/execution/TaskLogs.jsx
ui/src/pages/execution/TaskSummary.jsx
ui/src/pages/executions/ResultsTable.jsx
ui/src/pages/executions/WorkflowSearch.jsx
ui/src/setupProxy.js

----
----
- Add CRA proxy rewrite /api => / as backend no longer supports the former
- Replace react-json-view with Monaco editor
- Do not shift graph on side panel appearance
- Persisted selected task
- Fix wrong icon in retry dropdown
- Show elapsed time for currently running tasks
- Fix workflow search sort order not restored from URL

Merge Netflix internal UI changes

---

test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
test-harness/src/test/java/com/netflix/conductor/test/utils/MockExternalPayloadStorage.java
test-harness/src/test/resources/dynamic_fork_join_integration_test.json

integ test for dynamic fork with subworkflow external storage

---

client/build.gradle
client/spotbugsExclude.xml

ignore codes raised by new spotbugs

---

docs/docs/architecture.md

----
----
Updated stale links in the architecture page.
Issue #2913

#2913 fixed dead links

---

docs/docs/reference-docs/event-task.md

SQL to SQS eventing name
----
----
Issue #
----

SQL to SQS eventing name

---

RELATED.md

----
- [ x] Other (please describe):
Updated client SDKs
Issue #
----

Updated related.md to add conductor sdks

---

docs/docs/configuration/workflowdef.md

fixed typos

---

ui/src/components/diagram/WorkflowDAG.js
ui/src/components/diagram/WorkflowGraph.jsx
ui/src/components/diagram/diagram.scss
ui/src/pages/execution/Timeline.jsx

----
----
Issue https://github.com/Netflix/conductor/issues/2725
This shows a new UI for the Loop including the internal items as shown here:

Add visual Loop representation.

---

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java

----
Log workflow failures
Issue #
----

Log workflow failures

---

WHOSUSING.md

Add Supercharge

---

.github/pull_request_template.md
client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
client/src/main/java/com/netflix/conductor/client/http/jersey/JerseyRequestHandler.java
java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/WorkflowExecutor.java
java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/def/WorkflowCreationTests.java

----
Please remember to run `./gradlew :conductor-java-sdk:spotlessApply` to fix any format violations.
----
_Additional constructors in JerseyRequestHandler_

Additional constructors in JerseyRequestHandler to simplify its creation

---

docs/docs/gettingstarted/source.md
docs/docs/index.md
docs/docs/reference-docs/azureblob-storage.md

----
----
Fixes a typo that's on the project's home page, among other places.
----
N/A

Fix typo: persistance → persistence

---

common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java
es6-persistence/src/main/resources/mappings_docType_task.json
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
grpc/src/main/proto/model/tasksummary.proto

----
----
Add task domain to the indexed document in elasticsearch to enable searching task executions by domain.

Add task domain to the index

---

client/src/main/java/com/netflix/conductor/client/automator/TaskPollExecutor.java
client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java
client/src/main/java/com/netflix/conductor/client/telemetry/MetricsContainer.java
client/src/main/java/com/netflix/conductor/client/worker/Worker.java
client/src/test/java/com/netflix/conductor/client/automator/TaskPollExecutorTest.java
common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java
core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
core/src/main/java/com/netflix/conductor/metrics/Monitors.java
core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java

----
----
Add ability for long running tasks to extend lease so it can keep processing without getting response timeout
Issue #
----

task lease extend

---

docs/docs/configuration/workflowdef.md
docs/docs/resources/contributing.md
ui/README.md

----
----
Issue #
Corrected Language issues.
----

[Docs] Fixed Language issues.

---

json-jq-task/src/main/java/com/netflix/conductor/tasks/json/JsonJqTransform.java
json-jq-task/src/test/java/com/netflix/conductor/tasks/json/JsonJqTransformTest.java
test-harness/src/test/groovy/com/netflix/conductor/test/integration/JsonJQTransformSpec.groovy
test-harness/src/test/resources/json_jq_transform_result_integration_test.json

----
----
Extract json node body from Json_JQ task to be put in taskModel's output
Issue #
----

Extract json node body from json_jq task output

---

common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java
core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
core/src/main/java/com/netflix/conductor/core/index/NoopIndexDAO.java
core/src/main/java/com/netflix/conductor/dao/IndexDAO.java
core/src/main/java/com/netflix/conductor/service/ExecutionService.java
core/src/test/java/com/netflix/conductor/service/ExecutionServiceTest.java
es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchDAOV6.java
es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchRestDAOV6.java
es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchDAOV6.java
es6-persistence/src/test/java/com/netflix/conductor/es6/dao/index/TestElasticSearchRestDAOV6.java

…ts from ES directly
----
----
Issue #
----

Refactor task search v1 and workflow search v1 APIs to return doc from ES directly

---

docs/mkdocs.yml

----
----
Fixed a typo
Issue # N/A
----
N/A

📝 Fix typo in website nav menu

---

docs/docs/index.md

----
----
Fix typo in home page of the docs: Desiging → Designing
----
N/A

Fix typo in docs: Desiging → Designing

---

ui/src/components/formik/FormikInput.jsx

----
- [ X] Bugfix
----
Issue #
----

fix a spell mistake

---

awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/config/SQSEventQueueConfiguration.java
awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/config/SQSEventQueueProvider.java
awssqs-event-queue/src/main/java/com/netflix/conductor/sqs/eventqueue/SQSObservableQueue.java
awssqs-event-queue/src/test/java/com/netflix/conductor/sqs/eventqueue/SQSObservableQueueTest.java

Use AmazonSQS instead of AmazonSQSClient

---

README.md

----
- [x ] Other (please describe):
----
Update to readme.
Issue #
----

Update README to include reference to workflow as code

---

docker/docker-compose.yaml

Updated to make it work on Apple Mac M1
----
- [x ] Bugfix
----
Issue #
----

Updated to make it work on Apple Mac M1

---

docs/docs/reference-docs/join-task.md

[docs]: update join-task.md

---

docs/docs/reference-docs/fork-task.md
docs/docs/reference-docs/inline-task.md

----
Fixed documentation issues.
----
Issue #
----

[docs] Minor issue fixes

---

docker/docker-compose.yaml

Curl is not available in the rabbitmq image

---

core/src/main/java/com/netflix/conductor/core/events/DefaultEventProcessor.java
core/src/main/java/com/netflix/conductor/core/events/queue/ObservableQueue.java

----
- [x ] Other (please describe):
Apply formatting.
----
Issue #
----

Apply spotless

---

docker/docker-compose-postgres.yaml
docker/docker-compose.yaml
docker/server/config/config-local.properties

----
Fix docker compose.
----
Issue #
----

Fix docker builds

---

core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java

----
- [x ] Feature
----
Include inputs to the switch task as inputs, which makes it easy to debug.
Issue #
----

Include inputs to the switch task

---

README.md

----
----
change link from `http://conductor.netflix.com` to `https://conductor.netflix.com`
Issue #3604 
----

update the link of Main Documentation Site

---

WHOSUSING.md

----
Added Clari as the user of conductor
Issue #
----

Adding Clari as user of the Conductor

---

README.md

----
- [ x] Other (please describe):
----
README updates.
Issue #
----

update to add star and fork count

---

README.md

----
- [ x] Other (please describe):
----
Updated readme with resources
Issue #
----

Updates to readme with resources

---

.gitignore
awss3-storage/dependencies.lock
awssqs-event-queue/dependencies.lock
cassandra-persistence/dependencies.lock
client-spring/dependencies.lock
client/dependencies.lock
common/dependencies.lock
core/dependencies.lock
dependencies.gradle
es6-persistence/dependencies.lock
grpc-client/dependencies.lock
grpc-server/dependencies.lock
grpc/build.gradle
grpc/dependencies.lock
http-task/dependencies.lock
java-sdk/dependencies.lock
json-jq-task/dependencies.lock
redis-concurrency-limit/dependencies.lock
redis-lock/dependencies.lock
redis-persistence/dependencies.lock
rest/dependencies.lock
server/dependencies.lock
test-harness/dependencies.lock

----
----
Google protobuf is failing vulnerability checks for my company's pipeline, and we need this fixed to deploy.
Issue #
New version of Google protobuf
----
N/A

Update google protobuf to pass security checks

---

docker/server/Dockerfile
docker/ui/Dockerfile

----
----
Fixed bugs when building docker images
Issue #3632

Fixed Docker issues
